/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_common_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This is part of the IHMC Common message package.
<p>Source (ihmc_common_msgs/Capsule3DMessage):
<pre>{@code
# This is part of the IHMC Common message package.

# Position of the capsule, see Capsule3D.
geometry_msgs/Point position

# Axis of the capsule, see Capsule3D.
geometry_msgs/Vector3 axis

# Radius of the capsule, see Capsule3D.
float64 radius

# Length of the capsule, see Capsule3D.
float64 length}</pre>
*/
public class Capsule3DMessage implements ROS2Message<Capsule3DMessage>
{
   public static final java.lang.String name = "ihmc_common_msgs::msg::dds_::Capsule3DMessage_";

   /**
      Position of the capsule, see Capsule3D.
   */
   private final geometry_msgs.msg.dds.Point position_;
   /**
      Axis of the capsule, see Capsule3D.
   */
   private final geometry_msgs.msg.dds.Vector3 axis_;
   /**
      Radius of the capsule, see Capsule3D.
   */
   private double radius_;
   /**
      Length of the capsule, see Capsule3D.
   */
   private double length_;

   public Capsule3DMessage()
   {
      position_ = new geometry_msgs.msg.dds.Point();
      axis_ = new geometry_msgs.msg.dds.Vector3();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += position_.calculateSizeBytes(currentAlignment);
      currentAlignment += axis_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // radius_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // length_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      position_.serialize(buffer);
      axis_.serialize(buffer);
      buffer.writeDouble(radius_);
      buffer.writeDouble(length_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      position_.deserialize(buffer);
      axis_.deserialize(buffer);
      radius_ = buffer.readDouble();
      length_ = buffer.readDouble();

   }

   @Override
   public void set(Capsule3DMessage from)
   {
      position_.set(from.position_);
      axis_.set(from.axis_);
      radius_ = from.radius_;
      length_ = from.length_;

   }

   public geometry_msgs.msg.dds.Point getPosition()
   {
      return position_;
   }

   public geometry_msgs.msg.dds.Vector3 getAxis()
   {
      return axis_;
   }

   public double getRadius()
   {
      return radius_;
   }

   public void setRadius(double radius_)
   {
      this.radius_ = radius_;
   }

   public double getLength()
   {
      return length_;
   }

   public void setLength(double length_)
   {
      this.length_ = length_;
   }


}