/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_common_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (ihmc_common_msgs/Point2DMessage):
<pre>{@code
# x coordinate
float64 x

# y coordinate
float64 y}</pre>
*/
public class Point2DMessage implements ROS2Message<Point2DMessage>
{
   public static final java.lang.String name = "ihmc_common_msgs::msg::dds_::Point2DMessage_";

   /**
      x coordinate
   */
   private double x_;
   /**
      y coordinate
   */
   private double y_;

   public Point2DMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // x_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // y_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(x_);
      buffer.writeDouble(y_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      x_ = buffer.readDouble();
      y_ = buffer.readDouble();

   }

   @Override
   public void set(Point2DMessage from)
   {
      x_ = from.x_;
      y_ = from.y_;

   }

   public double getX()
   {
      return x_;
   }

   public void setX(double x_)
   {
      this.x_ = x_;
   }

   public double getY()
   {
      return y_;
   }

   public void setY(double y_)
   {
      this.y_ = y_;
   }


}