/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_common_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (ihmc_common_msgs/PoseListMessage):
<pre>{@code
# A list of poses
geometry_msgs/Pose[] poses}</pre>
*/
public class PoseListMessage implements ROS2Message<PoseListMessage>
{
   public static final java.lang.String name = "ihmc_common_msgs::msg::dds_::PoseListMessage_";

   /**
      A list of poses
   */
   private final IDLObjectSequence<geometry_msgs.msg.dds.Pose> poses_;

   public PoseListMessage()
   {
      poses_ = new IDLObjectSequence<geometry_msgs.msg.dds.Pose>(geometry_msgs.msg.dds.Pose.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += poses_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      poses_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      poses_.deserialize(buffer);

   }

   @Override
   public void set(PoseListMessage from)
   {
      poses_.set(from.poses_);

   }

   public IDLObjectSequence<geometry_msgs.msg.dds.Pose> getPoses()
   {
      return poses_;
   }


}