/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/AI2RNavigationMessage):
<pre>{@code
# SPATIAL RELATION TYPE
byte DEFAULT = 0
byte FRONT = 1
byte BEHIND = 2
byte LEFT = 3
byte RIGHT = 4

# The type of spatial relation with the secondary reference object as defined above
byte spatial_relation

# Point of view object. Secondary reference frame (object) used as the point of view that defines the spatial relation with the object
string pov_object

# Target reference frame (object) to go to
string target_object

# The distance to the reference frame (located at the object's centroid)
float64 distance_to_object}</pre>
*/
public class AI2RNavigationMessage implements ROS2Message<AI2RNavigationMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::AI2RNavigationMessage_";

   /**
      SPATIAL RELATION TYPE
   */
   public static final byte DEFAULT = 0;
   public static final byte FRONT = 1;
   public static final byte BEHIND = 2;
   public static final byte LEFT = 3;
   public static final byte RIGHT = 4;
   /**
      The type of spatial relation with the secondary reference object as defined above
   */
   private byte spatial_relation_;
   /**
      Point of view object. Secondary reference frame (object) used as the point of view that defines the spatial relation with the object
   */
   private final StringBuilder pov_object_;
   /**
      Target reference frame (object) to go to
   */
   private final StringBuilder target_object_;
   /**
      The distance to the reference frame (located at the object's centroid)
   */
   private double distance_to_object_;

   public AI2RNavigationMessage()
   {
      pov_object_ = new StringBuilder();
      target_object_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // spatial_relation_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * pov_object_.length()) + 1; // pov_object_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * target_object_.length()) + 1; // target_object_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // distance_to_object_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(spatial_relation_);
      buffer.writeString(pov_object_);
      buffer.writeString(target_object_);
      buffer.writeDouble(distance_to_object_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      spatial_relation_ = buffer.readByte();
      buffer.readString(pov_object_);
      buffer.readString(target_object_);
      distance_to_object_ = buffer.readDouble();

   }

   @Override
   public void set(AI2RNavigationMessage from)
   {
      spatial_relation_ = from.spatial_relation_;
      pov_object_.delete(0, pov_object_.length());
      pov_object_.insert(0, from.pov_object_);
      target_object_.delete(0, target_object_.length());
      target_object_.insert(0, from.target_object_);
      distance_to_object_ = from.distance_to_object_;

   }

   public byte getSpatialRelation()
   {
      return spatial_relation_;
   }

   public void setSpatialRelation(byte spatial_relation_)
   {
      this.spatial_relation_ = spatial_relation_;
   }

   public StringBuilder getPovObject()
   {
      return pov_object_;
   }

   public StringBuilder getTargetObject()
   {
      return target_object_;
   }

   public double getDistanceToObject()
   {
      return distance_to_object_;
   }

   public void setDistanceToObject(double distance_to_object_)
   {
      this.distance_to_object_ = distance_to_object_;
   }


}