/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/AI2RCommandMessage):
<pre>{@code
# Behavior to execute (checkpoint to jump to in the pre-loaded behavior collection)
string behavior_to_execute

bool adapting_behavior false

behavior_msgs/AI2RHandPoseAdaptationMessage hand_pose_adaptation

behavior_msgs/AI2RNavigationMessage navigation

behavior_msgs/AI2RReceiveObjectMessage receive_object

behavior_msgs/AI2RPickUpObjectMessage pickup_object}</pre>
*/
public class AI2RCommandMessage implements ROS2Message<AI2RCommandMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::AI2RCommandMessage_";

   /**
      Behavior to execute (checkpoint to jump to in the pre-loaded behavior collection)
   */
   private final StringBuilder behavior_to_execute_;
   private boolean adapting_behavior_;
   private final behavior_msgs.msg.dds.AI2RHandPoseAdaptationMessage hand_pose_adaptation_;
   private final behavior_msgs.msg.dds.AI2RNavigationMessage navigation_;
   private final behavior_msgs.msg.dds.AI2RReceiveObjectMessage receive_object_;
   private final behavior_msgs.msg.dds.AI2RPickUpObjectMessage pickup_object_;

   public AI2RCommandMessage()
   {
      behavior_to_execute_ = new StringBuilder();
      adapting_behavior_ = (boolean) false;
      hand_pose_adaptation_ = new behavior_msgs.msg.dds.AI2RHandPoseAdaptationMessage();
      navigation_ = new behavior_msgs.msg.dds.AI2RNavigationMessage();
      receive_object_ = new behavior_msgs.msg.dds.AI2RReceiveObjectMessage();
      pickup_object_ = new behavior_msgs.msg.dds.AI2RPickUpObjectMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * behavior_to_execute_.length()) + 1; // behavior_to_execute_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // adapting_behavior_
      currentAlignment += hand_pose_adaptation_.calculateSizeBytes(currentAlignment);
      currentAlignment += navigation_.calculateSizeBytes(currentAlignment);
      currentAlignment += receive_object_.calculateSizeBytes(currentAlignment);
      currentAlignment += pickup_object_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(behavior_to_execute_);
      buffer.writeBoolean(adapting_behavior_);
      hand_pose_adaptation_.serialize(buffer);
      navigation_.serialize(buffer);
      receive_object_.serialize(buffer);
      pickup_object_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(behavior_to_execute_);
      adapting_behavior_ = buffer.readBoolean();
      hand_pose_adaptation_.deserialize(buffer);
      navigation_.deserialize(buffer);
      receive_object_.deserialize(buffer);
      pickup_object_.deserialize(buffer);

   }

   @Override
   public void set(AI2RCommandMessage from)
   {
      behavior_to_execute_.delete(0, behavior_to_execute_.length());
      behavior_to_execute_.insert(0, from.behavior_to_execute_);
      adapting_behavior_ = from.adapting_behavior_;
      hand_pose_adaptation_.set(from.hand_pose_adaptation_);
      navigation_.set(from.navigation_);
      receive_object_.set(from.receive_object_);
      pickup_object_.set(from.pickup_object_);

   }

   public StringBuilder getBehaviorToExecute()
   {
      return behavior_to_execute_;
   }

   public boolean getAdaptingBehavior()
   {
      return adapting_behavior_;
   }

   public void setAdaptingBehavior(boolean adapting_behavior_)
   {
      this.adapting_behavior_ = adapting_behavior_;
   }

   public behavior_msgs.msg.dds.AI2RHandPoseAdaptationMessage getHandPoseAdaptation()
   {
      return hand_pose_adaptation_;
   }

   public behavior_msgs.msg.dds.AI2RNavigationMessage getNavigation()
   {
      return navigation_;
   }

   public behavior_msgs.msg.dds.AI2RReceiveObjectMessage getReceiveObject()
   {
      return receive_object_;
   }

   public behavior_msgs.msg.dds.AI2RPickUpObjectMessage getPickupObject()
   {
      return pickup_object_;
   }


}