/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/AI2RPickUpObjectMessage):
<pre>{@code
# Reference frame (object) to pick up
string object_name}</pre>
*/
public class AI2RPickUpObjectMessage implements ROS2Message<AI2RPickUpObjectMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::AI2RPickUpObjectMessage_";

   /**
      Reference frame (object) to pick up
   */
   private final StringBuilder object_name_;

   public AI2RPickUpObjectMessage()
   {
      object_name_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * object_name_.length()) + 1; // object_name_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(object_name_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(object_name_);

   }

   @Override
   public void set(AI2RPickUpObjectMessage from)
   {
      object_name_.delete(0, object_name_.length());
      object_name_.insert(0, from.object_name_);

   }

   public StringBuilder getObjectName()
   {
      return object_name_;
   }


}