/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Gives the current state of the complete collection of behavior tree nodes.
Publishing all behavior tree nodes in one message can simplify synchronization and
reduce the complexity of logic in figuring out when nodes are currently under
consideration.
<p>Source (behavior_msgs/BehaviorTreeStateMessage):
<pre>{@code
# Gives the current state of the complete collection of behavior tree nodes.
# Publishing all behavior tree nodes in one message can simplify synchronization and
# reduce the complexity of logic in figuring out when nodes are currently under
# consideration.

# Used to minimize bandwidth, nodes that are send
# without their full data.
byte PARTIAL_DATA = 0

byte ROOT_NODE = 1
byte BASIC_NODE = 2
byte ACTION_SEQUENCE = 3
byte FALLBACK_NODE = 4
byte CONDITION_NODE = 5
byte GOTO_NODE = 6
byte CHECKPOINT_NODE = 7
byte SCENE_ACTION = 8
byte AI2R_NODE = 9
byte DOOR_TRAVERSAL = 10
byte BUILDING_EXPLORATION = 11

byte CHEST_ORIENTATION_ACTION = 12
byte FOOTSTEP_PLAN_ACTION = 13
byte SAKE_HAND_COMMAND_ACTION = 14
byte ABILITY_HAND_ACTION = 15
byte HAND_POSE_ACTION = 16
byte HAND_WRENCH_ACTION = 17
byte SCREW_PRIMITIVE_ACTION = 18
byte PELVIS_HEIGHT_ORIENTATION_ACTION = 19
byte WAIT_DURATION_ACTION = 20
byte FOOT_POSE_ACTION = 21

# Monotonically increasing message ID that matches the CRDTInfo update number
uint64 sequence_id

# The ID to assign to the next instantiated node
uint32 next_id

# The timestamp and modifier ID of the most recent time the root node was replaced or removed
ihmc_common_msgs/LatestModificationMessage latest_modification_to_root_reference

# The timestamp and modifier ID of the latest modification of the tree data fields
ihmc_common_msgs/LatestModificationMessage latest_modification_to_data

# Scene
behavior_msgs/BehaviorTreeSceneStateMessage scene

# A depth first ordered list of types.
byte[<=1000] behavior_tree_types

# A depth first ordered list of node indexes.
# The index is of that node in it's respective list for
# it's type.
uint32[<=1000] behavior_tree_indices

behavior_msgs/BasicNodeStateMessage[<=300] partial_data_nodes

behavior_msgs/BehaviorTreeRootNodeStateMessage[<=1] root_nodes

behavior_msgs/BasicNodeStateMessage[<=120] basic_nodes

behavior_msgs/ActionSequenceStateMessage[<=120] action_sequences

behavior_msgs/FallbackNodeStateMessage[<=120] fallback_nodes

behavior_msgs/ConditionNodeStateMessage[<=120] condition_nodes

behavior_msgs/GotoNodeStateMessage[<=120] goto_nodes

behavior_msgs/CheckPointNodeStateMessage[<=120] checkpoint_nodes

behavior_msgs/SceneActionNodeStateMessage[<=120] scene_actions

behavior_msgs/AI2RNodeStateMessage[<=1] ai2r_nodes

behavior_msgs/DoorTraversalStateMessage[<=120] door_traversals

behavior_msgs/BuildingExplorationStateMessage[<=120] building_explorations

behavior_msgs/ChestOrientationActionStateMessage[<=120] chest_orientation_actions

behavior_msgs/FootstepPlanActionStateMessage[<=120] footstep_plan_actions

behavior_msgs/SakeHandCommandActionStateMessage[<=120] sake_hand_command_actions

behavior_msgs/AbilityHandActionStateMessage[<=120] ability_hand_actions

behavior_msgs/HandPoseActionStateMessage[<=120] hand_pose_actions

behavior_msgs/HandWrenchActionStateMessage[<=120] hand_wrench_actions

behavior_msgs/ScrewPrimitiveActionStateMessage[<=120] screw_primitive_actions

behavior_msgs/PelvisHeightOrientationActionStateMessage[<=120] pelvis_height_actions

behavior_msgs/WaitDurationActionStateMessage[<=120] wait_duration_actions

behavior_msgs/FootPoseActionStateMessage[<=120] foot_pose_actions
}</pre>
*/
public class BehaviorTreeStateMessage implements ROS2Message<BehaviorTreeStateMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::BehaviorTreeStateMessage_";

   /**
      Used to minimize bandwidth, nodes that are send
      without their full data.
   */
   public static final byte PARTIAL_DATA = 0;
   public static final byte ROOT_NODE = 1;
   public static final byte BASIC_NODE = 2;
   public static final byte ACTION_SEQUENCE = 3;
   public static final byte FALLBACK_NODE = 4;
   public static final byte CONDITION_NODE = 5;
   public static final byte GOTO_NODE = 6;
   public static final byte CHECKPOINT_NODE = 7;
   public static final byte SCENE_ACTION = 8;
   public static final byte AI2R_NODE = 9;
   public static final byte DOOR_TRAVERSAL = 10;
   public static final byte BUILDING_EXPLORATION = 11;
   public static final byte CHEST_ORIENTATION_ACTION = 12;
   public static final byte FOOTSTEP_PLAN_ACTION = 13;
   public static final byte SAKE_HAND_COMMAND_ACTION = 14;
   public static final byte ABILITY_HAND_ACTION = 15;
   public static final byte HAND_POSE_ACTION = 16;
   public static final byte HAND_WRENCH_ACTION = 17;
   public static final byte SCREW_PRIMITIVE_ACTION = 18;
   public static final byte PELVIS_HEIGHT_ORIENTATION_ACTION = 19;
   public static final byte WAIT_DURATION_ACTION = 20;
   public static final byte FOOT_POSE_ACTION = 21;
   /**
      Monotonically increasing message ID that matches the CRDTInfo update number
   */
   private long sequence_id_;
   /**
      The ID to assign to the next instantiated node
   */
   private int next_id_;
   /**
      The timestamp and modifier ID of the most recent time the root node was replaced or removed
   */
   private final ihmc_common_msgs.msg.dds.LatestModificationMessage latest_modification_to_root_reference_;
   /**
      The timestamp and modifier ID of the latest modification of the tree data fields
   */
   private final ihmc_common_msgs.msg.dds.LatestModificationMessage latest_modification_to_data_;
   /**
      Scene
   */
   private final behavior_msgs.msg.dds.BehaviorTreeSceneStateMessage scene_;
   /**
      A depth first ordered list of types.
   */
   private final IDLByteSequence behavior_tree_types_;
   /**
      A depth first ordered list of node indexes.
      The index is of that node in it's respective list for
      it's type.
   */
   private final IDLIntSequence behavior_tree_indices_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.BasicNodeStateMessage> partial_data_nodes_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.BehaviorTreeRootNodeStateMessage> root_nodes_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.BasicNodeStateMessage> basic_nodes_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.ActionSequenceStateMessage> action_sequences_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.FallbackNodeStateMessage> fallback_nodes_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.ConditionNodeStateMessage> condition_nodes_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.GotoNodeStateMessage> goto_nodes_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.CheckPointNodeStateMessage> checkpoint_nodes_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.SceneActionNodeStateMessage> scene_actions_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.AI2RNodeStateMessage> ai2r_nodes_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.DoorTraversalStateMessage> door_traversals_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.BuildingExplorationStateMessage> building_explorations_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.ChestOrientationActionStateMessage> chest_orientation_actions_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.FootstepPlanActionStateMessage> footstep_plan_actions_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.SakeHandCommandActionStateMessage> sake_hand_command_actions_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.AbilityHandActionStateMessage> ability_hand_actions_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.HandPoseActionStateMessage> hand_pose_actions_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.HandWrenchActionStateMessage> hand_wrench_actions_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.ScrewPrimitiveActionStateMessage> screw_primitive_actions_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.PelvisHeightOrientationActionStateMessage> pelvis_height_actions_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.WaitDurationActionStateMessage> wait_duration_actions_;
   private final IDLObjectSequence<behavior_msgs.msg.dds.FootPoseActionStateMessage> foot_pose_actions_;

   public BehaviorTreeStateMessage()
   {
      latest_modification_to_root_reference_ = new ihmc_common_msgs.msg.dds.LatestModificationMessage();
      latest_modification_to_data_ = new ihmc_common_msgs.msg.dds.LatestModificationMessage();
      scene_ = new behavior_msgs.msg.dds.BehaviorTreeSceneStateMessage();
      behavior_tree_types_ = new IDLByteSequence(1000);
      behavior_tree_indices_ = new IDLIntSequence(1000);
      partial_data_nodes_ = new IDLObjectSequence<behavior_msgs.msg.dds.BasicNodeStateMessage>(300, behavior_msgs.msg.dds.BasicNodeStateMessage.class);
      root_nodes_ = new IDLObjectSequence<behavior_msgs.msg.dds.BehaviorTreeRootNodeStateMessage>(1, behavior_msgs.msg.dds.BehaviorTreeRootNodeStateMessage.class);
      basic_nodes_ = new IDLObjectSequence<behavior_msgs.msg.dds.BasicNodeStateMessage>(120, behavior_msgs.msg.dds.BasicNodeStateMessage.class);
      action_sequences_ = new IDLObjectSequence<behavior_msgs.msg.dds.ActionSequenceStateMessage>(120, behavior_msgs.msg.dds.ActionSequenceStateMessage.class);
      fallback_nodes_ = new IDLObjectSequence<behavior_msgs.msg.dds.FallbackNodeStateMessage>(120, behavior_msgs.msg.dds.FallbackNodeStateMessage.class);
      condition_nodes_ = new IDLObjectSequence<behavior_msgs.msg.dds.ConditionNodeStateMessage>(120, behavior_msgs.msg.dds.ConditionNodeStateMessage.class);
      goto_nodes_ = new IDLObjectSequence<behavior_msgs.msg.dds.GotoNodeStateMessage>(120, behavior_msgs.msg.dds.GotoNodeStateMessage.class);
      checkpoint_nodes_ = new IDLObjectSequence<behavior_msgs.msg.dds.CheckPointNodeStateMessage>(120, behavior_msgs.msg.dds.CheckPointNodeStateMessage.class);
      scene_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.SceneActionNodeStateMessage>(120, behavior_msgs.msg.dds.SceneActionNodeStateMessage.class);
      ai2r_nodes_ = new IDLObjectSequence<behavior_msgs.msg.dds.AI2RNodeStateMessage>(1, behavior_msgs.msg.dds.AI2RNodeStateMessage.class);
      door_traversals_ = new IDLObjectSequence<behavior_msgs.msg.dds.DoorTraversalStateMessage>(120, behavior_msgs.msg.dds.DoorTraversalStateMessage.class);
      building_explorations_ = new IDLObjectSequence<behavior_msgs.msg.dds.BuildingExplorationStateMessage>(120, behavior_msgs.msg.dds.BuildingExplorationStateMessage.class);
      chest_orientation_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.ChestOrientationActionStateMessage>(120, behavior_msgs.msg.dds.ChestOrientationActionStateMessage.class);
      footstep_plan_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.FootstepPlanActionStateMessage>(120, behavior_msgs.msg.dds.FootstepPlanActionStateMessage.class);
      sake_hand_command_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.SakeHandCommandActionStateMessage>(120, behavior_msgs.msg.dds.SakeHandCommandActionStateMessage.class);
      ability_hand_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.AbilityHandActionStateMessage>(120, behavior_msgs.msg.dds.AbilityHandActionStateMessage.class);
      hand_pose_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.HandPoseActionStateMessage>(120, behavior_msgs.msg.dds.HandPoseActionStateMessage.class);
      hand_wrench_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.HandWrenchActionStateMessage>(120, behavior_msgs.msg.dds.HandWrenchActionStateMessage.class);
      screw_primitive_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.ScrewPrimitiveActionStateMessage>(120, behavior_msgs.msg.dds.ScrewPrimitiveActionStateMessage.class);
      pelvis_height_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.PelvisHeightOrientationActionStateMessage>(120, behavior_msgs.msg.dds.PelvisHeightOrientationActionStateMessage.class);
      wait_duration_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.WaitDurationActionStateMessage>(120, behavior_msgs.msg.dds.WaitDurationActionStateMessage.class);
      foot_pose_actions_ = new IDLObjectSequence<behavior_msgs.msg.dds.FootPoseActionStateMessage>(120, behavior_msgs.msg.dds.FootPoseActionStateMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // next_id_
      currentAlignment += latest_modification_to_root_reference_.calculateSizeBytes(currentAlignment);
      currentAlignment += latest_modification_to_data_.calculateSizeBytes(currentAlignment);
      currentAlignment += scene_.calculateSizeBytes(currentAlignment);
      currentAlignment += behavior_tree_types_.calculateSizeBytes(currentAlignment);
      currentAlignment += behavior_tree_indices_.calculateSizeBytes(currentAlignment);
      currentAlignment += partial_data_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += root_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += basic_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += action_sequences_.calculateSizeBytes(currentAlignment);
      currentAlignment += fallback_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += condition_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += goto_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += checkpoint_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += scene_actions_.calculateSizeBytes(currentAlignment);
      currentAlignment += ai2r_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += door_traversals_.calculateSizeBytes(currentAlignment);
      currentAlignment += building_explorations_.calculateSizeBytes(currentAlignment);
      currentAlignment += chest_orientation_actions_.calculateSizeBytes(currentAlignment);
      currentAlignment += footstep_plan_actions_.calculateSizeBytes(currentAlignment);
      currentAlignment += sake_hand_command_actions_.calculateSizeBytes(currentAlignment);
      currentAlignment += ability_hand_actions_.calculateSizeBytes(currentAlignment);
      currentAlignment += hand_pose_actions_.calculateSizeBytes(currentAlignment);
      currentAlignment += hand_wrench_actions_.calculateSizeBytes(currentAlignment);
      currentAlignment += screw_primitive_actions_.calculateSizeBytes(currentAlignment);
      currentAlignment += pelvis_height_actions_.calculateSizeBytes(currentAlignment);
      currentAlignment += wait_duration_actions_.calculateSizeBytes(currentAlignment);
      currentAlignment += foot_pose_actions_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeInt(next_id_);
      latest_modification_to_root_reference_.serialize(buffer);
      latest_modification_to_data_.serialize(buffer);
      scene_.serialize(buffer);
      behavior_tree_types_.serialize(buffer);
      behavior_tree_indices_.serialize(buffer);
      partial_data_nodes_.serialize(buffer);
      root_nodes_.serialize(buffer);
      basic_nodes_.serialize(buffer);
      action_sequences_.serialize(buffer);
      fallback_nodes_.serialize(buffer);
      condition_nodes_.serialize(buffer);
      goto_nodes_.serialize(buffer);
      checkpoint_nodes_.serialize(buffer);
      scene_actions_.serialize(buffer);
      ai2r_nodes_.serialize(buffer);
      door_traversals_.serialize(buffer);
      building_explorations_.serialize(buffer);
      chest_orientation_actions_.serialize(buffer);
      footstep_plan_actions_.serialize(buffer);
      sake_hand_command_actions_.serialize(buffer);
      ability_hand_actions_.serialize(buffer);
      hand_pose_actions_.serialize(buffer);
      hand_wrench_actions_.serialize(buffer);
      screw_primitive_actions_.serialize(buffer);
      pelvis_height_actions_.serialize(buffer);
      wait_duration_actions_.serialize(buffer);
      foot_pose_actions_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      next_id_ = buffer.readInt();
      latest_modification_to_root_reference_.deserialize(buffer);
      latest_modification_to_data_.deserialize(buffer);
      scene_.deserialize(buffer);
      behavior_tree_types_.deserialize(buffer);
      behavior_tree_indices_.deserialize(buffer);
      partial_data_nodes_.deserialize(buffer);
      root_nodes_.deserialize(buffer);
      basic_nodes_.deserialize(buffer);
      action_sequences_.deserialize(buffer);
      fallback_nodes_.deserialize(buffer);
      condition_nodes_.deserialize(buffer);
      goto_nodes_.deserialize(buffer);
      checkpoint_nodes_.deserialize(buffer);
      scene_actions_.deserialize(buffer);
      ai2r_nodes_.deserialize(buffer);
      door_traversals_.deserialize(buffer);
      building_explorations_.deserialize(buffer);
      chest_orientation_actions_.deserialize(buffer);
      footstep_plan_actions_.deserialize(buffer);
      sake_hand_command_actions_.deserialize(buffer);
      ability_hand_actions_.deserialize(buffer);
      hand_pose_actions_.deserialize(buffer);
      hand_wrench_actions_.deserialize(buffer);
      screw_primitive_actions_.deserialize(buffer);
      pelvis_height_actions_.deserialize(buffer);
      wait_duration_actions_.deserialize(buffer);
      foot_pose_actions_.deserialize(buffer);

   }

   @Override
   public void set(BehaviorTreeStateMessage from)
   {
      sequence_id_ = from.sequence_id_;
      next_id_ = from.next_id_;
      latest_modification_to_root_reference_.set(from.latest_modification_to_root_reference_);
      latest_modification_to_data_.set(from.latest_modification_to_data_);
      scene_.set(from.scene_);
      behavior_tree_types_.set(from.behavior_tree_types_);
      behavior_tree_indices_.set(from.behavior_tree_indices_);
      partial_data_nodes_.set(from.partial_data_nodes_);
      root_nodes_.set(from.root_nodes_);
      basic_nodes_.set(from.basic_nodes_);
      action_sequences_.set(from.action_sequences_);
      fallback_nodes_.set(from.fallback_nodes_);
      condition_nodes_.set(from.condition_nodes_);
      goto_nodes_.set(from.goto_nodes_);
      checkpoint_nodes_.set(from.checkpoint_nodes_);
      scene_actions_.set(from.scene_actions_);
      ai2r_nodes_.set(from.ai2r_nodes_);
      door_traversals_.set(from.door_traversals_);
      building_explorations_.set(from.building_explorations_);
      chest_orientation_actions_.set(from.chest_orientation_actions_);
      footstep_plan_actions_.set(from.footstep_plan_actions_);
      sake_hand_command_actions_.set(from.sake_hand_command_actions_);
      ability_hand_actions_.set(from.ability_hand_actions_);
      hand_pose_actions_.set(from.hand_pose_actions_);
      hand_wrench_actions_.set(from.hand_wrench_actions_);
      screw_primitive_actions_.set(from.screw_primitive_actions_);
      pelvis_height_actions_.set(from.pelvis_height_actions_);
      wait_duration_actions_.set(from.wait_duration_actions_);
      foot_pose_actions_.set(from.foot_pose_actions_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public int getNextId()
   {
      return next_id_;
   }

   public void setNextId(int next_id_)
   {
      this.next_id_ = next_id_;
   }

   public ihmc_common_msgs.msg.dds.LatestModificationMessage getLatestModificationToRootReference()
   {
      return latest_modification_to_root_reference_;
   }

   public ihmc_common_msgs.msg.dds.LatestModificationMessage getLatestModificationToData()
   {
      return latest_modification_to_data_;
   }

   public behavior_msgs.msg.dds.BehaviorTreeSceneStateMessage getScene()
   {
      return scene_;
   }

   public IDLByteSequence getBehaviorTreeTypes()
   {
      return behavior_tree_types_;
   }

   public IDLIntSequence getBehaviorTreeIndices()
   {
      return behavior_tree_indices_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.BasicNodeStateMessage> getPartialDataNodes()
   {
      return partial_data_nodes_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.BehaviorTreeRootNodeStateMessage> getRootNodes()
   {
      return root_nodes_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.BasicNodeStateMessage> getBasicNodes()
   {
      return basic_nodes_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.ActionSequenceStateMessage> getActionSequences()
   {
      return action_sequences_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.FallbackNodeStateMessage> getFallbackNodes()
   {
      return fallback_nodes_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.ConditionNodeStateMessage> getConditionNodes()
   {
      return condition_nodes_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.GotoNodeStateMessage> getGotoNodes()
   {
      return goto_nodes_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.CheckPointNodeStateMessage> getCheckpointNodes()
   {
      return checkpoint_nodes_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.SceneActionNodeStateMessage> getSceneActions()
   {
      return scene_actions_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.AI2RNodeStateMessage> getAi2rNodes()
   {
      return ai2r_nodes_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.DoorTraversalStateMessage> getDoorTraversals()
   {
      return door_traversals_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.BuildingExplorationStateMessage> getBuildingExplorations()
   {
      return building_explorations_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.ChestOrientationActionStateMessage> getChestOrientationActions()
   {
      return chest_orientation_actions_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.FootstepPlanActionStateMessage> getFootstepPlanActions()
   {
      return footstep_plan_actions_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.SakeHandCommandActionStateMessage> getSakeHandCommandActions()
   {
      return sake_hand_command_actions_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.AbilityHandActionStateMessage> getAbilityHandActions()
   {
      return ability_hand_actions_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.HandPoseActionStateMessage> getHandPoseActions()
   {
      return hand_pose_actions_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.HandWrenchActionStateMessage> getHandWrenchActions()
   {
      return hand_wrench_actions_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.ScrewPrimitiveActionStateMessage> getScrewPrimitiveActions()
   {
      return screw_primitive_actions_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.PelvisHeightOrientationActionStateMessage> getPelvisHeightActions()
   {
      return pelvis_height_actions_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.WaitDurationActionStateMessage> getWaitDurationActions()
   {
      return wait_duration_actions_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.FootPoseActionStateMessage> getFootPoseActions()
   {
      return foot_pose_actions_;
   }


}