/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A behavior tree scene object
<p>Source (behavior_msgs/BehaviorTreeSceneObjectStateMessage):
<pre>{@code
# A behavior tree scene object

# The timestamp and modifier ID of the latest modification to this object's data fields
ihmc_common_msgs/LatestModificationMessage latest_modification_to_data

# The object's unique ID
uint32 id

# Persistent detection associated with this object
behavior_msgs/PersistentDetectionStatusMessage persistent_detection

# Object type (IsaacROSFoundationPoseObject ordinal)
int32 object_type

# Transform of the object frame to world frame
controller_msgs/RigidBodyTransformMessage transform_to_world
}</pre>
*/
public class BehaviorTreeSceneObjectStateMessage implements ROS2Message<BehaviorTreeSceneObjectStateMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::BehaviorTreeSceneObjectStateMessage_";

   /**
      The timestamp and modifier ID of the latest modification to this object's data fields
   */
   private final ihmc_common_msgs.msg.dds.LatestModificationMessage latest_modification_to_data_;
   /**
      The object's unique ID
   */
   private int id_;
   /**
      Persistent detection associated with this object
   */
   private final behavior_msgs.msg.dds.PersistentDetectionStatusMessage persistent_detection_;
   /**
      Object type (IsaacROSFoundationPoseObject ordinal)
   */
   private int object_type_;
   /**
      Transform of the object frame to world frame
   */
   private final controller_msgs.msg.dds.RigidBodyTransformMessage transform_to_world_;

   public BehaviorTreeSceneObjectStateMessage()
   {
      latest_modification_to_data_ = new ihmc_common_msgs.msg.dds.LatestModificationMessage();
      persistent_detection_ = new behavior_msgs.msg.dds.PersistentDetectionStatusMessage();
      transform_to_world_ = new controller_msgs.msg.dds.RigidBodyTransformMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += latest_modification_to_data_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // id_
      currentAlignment += persistent_detection_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // object_type_
      currentAlignment += transform_to_world_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      latest_modification_to_data_.serialize(buffer);
      buffer.writeInt(id_);
      persistent_detection_.serialize(buffer);
      buffer.writeInt(object_type_);
      transform_to_world_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      latest_modification_to_data_.deserialize(buffer);
      id_ = buffer.readInt();
      persistent_detection_.deserialize(buffer);
      object_type_ = buffer.readInt();
      transform_to_world_.deserialize(buffer);

   }

   @Override
   public void set(BehaviorTreeSceneObjectStateMessage from)
   {
      latest_modification_to_data_.set(from.latest_modification_to_data_);
      id_ = from.id_;
      persistent_detection_.set(from.persistent_detection_);
      object_type_ = from.object_type_;
      transform_to_world_.set(from.transform_to_world_);

   }

   public ihmc_common_msgs.msg.dds.LatestModificationMessage getLatestModificationToData()
   {
      return latest_modification_to_data_;
   }

   public int getId()
   {
      return id_;
   }

   public void setId(int id_)
   {
      this.id_ = id_;
   }

   public behavior_msgs.msg.dds.PersistentDetectionStatusMessage getPersistentDetection()
   {
      return persistent_detection_;
   }

   public int getObjectType()
   {
      return object_type_;
   }

   public void setObjectType(int object_type_)
   {
      this.object_type_ = object_type_;
   }

   public controller_msgs.msg.dds.RigidBodyTransformMessage getTransformToWorld()
   {
      return transform_to_world_;
   }


}