/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/BehaviorTreeRootNodeStateMessage):
<pre>{@code
# Parent state fields
behavior_msgs/BehaviorTreeNodeStateMessage state

# Definition
behavior_msgs/BehaviorTreeRootNodeDefinitionMessage definition

# If the sequence is currently set to proceed automatically
bool automatic_execution

# The index of the action that is set to execute next
uint16 execution_next_index

# Request manual execution of the next action
bool manual_execution_requested

# Allows the operator to disable concurrency during authoring
bool concurrency_enabled

# Request failures reset
bool failure_reset_requested}</pre>
*/
public class BehaviorTreeRootNodeStateMessage implements ROS2Message<BehaviorTreeRootNodeStateMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::BehaviorTreeRootNodeStateMessage_";

   /**
      Parent state fields
   */
   private final behavior_msgs.msg.dds.BehaviorTreeNodeStateMessage state_;
   /**
      Definition
   */
   private final behavior_msgs.msg.dds.BehaviorTreeRootNodeDefinitionMessage definition_;
   /**
      If the sequence is currently set to proceed automatically
   */
   private boolean automatic_execution_;
   /**
      The index of the action that is set to execute next
   */
   private short execution_next_index_;
   /**
      Request manual execution of the next action
   */
   private boolean manual_execution_requested_;
   /**
      Allows the operator to disable concurrency during authoring
   */
   private boolean concurrency_enabled_;
   /**
      Request failures reset
   */
   private boolean failure_reset_requested_;

   public BehaviorTreeRootNodeStateMessage()
   {
      state_ = new behavior_msgs.msg.dds.BehaviorTreeNodeStateMessage();
      definition_ = new behavior_msgs.msg.dds.BehaviorTreeRootNodeDefinitionMessage();
      automatic_execution_ = (boolean) false;
      manual_execution_requested_ = (boolean) false;
      concurrency_enabled_ = (boolean) false;
      failure_reset_requested_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += state_.calculateSizeBytes(currentAlignment);
      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // automatic_execution_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // execution_next_index_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // manual_execution_requested_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // concurrency_enabled_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // failure_reset_requested_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      state_.serialize(buffer);
      definition_.serialize(buffer);
      buffer.writeBoolean(automatic_execution_);
      buffer.writeShort(execution_next_index_);
      buffer.writeBoolean(manual_execution_requested_);
      buffer.writeBoolean(concurrency_enabled_);
      buffer.writeBoolean(failure_reset_requested_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      state_.deserialize(buffer);
      definition_.deserialize(buffer);
      automatic_execution_ = buffer.readBoolean();
      execution_next_index_ = buffer.readShort();
      manual_execution_requested_ = buffer.readBoolean();
      concurrency_enabled_ = buffer.readBoolean();
      failure_reset_requested_ = buffer.readBoolean();

   }

   @Override
   public void set(BehaviorTreeRootNodeStateMessage from)
   {
      state_.set(from.state_);
      definition_.set(from.definition_);
      automatic_execution_ = from.automatic_execution_;
      execution_next_index_ = from.execution_next_index_;
      manual_execution_requested_ = from.manual_execution_requested_;
      concurrency_enabled_ = from.concurrency_enabled_;
      failure_reset_requested_ = from.failure_reset_requested_;

   }

   public behavior_msgs.msg.dds.BehaviorTreeNodeStateMessage getState()
   {
      return state_;
   }

   public behavior_msgs.msg.dds.BehaviorTreeRootNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public boolean getAutomaticExecution()
   {
      return automatic_execution_;
   }

   public void setAutomaticExecution(boolean automatic_execution_)
   {
      this.automatic_execution_ = automatic_execution_;
   }

   public short getExecutionNextIndex()
   {
      return execution_next_index_;
   }

   public void setExecutionNextIndex(short execution_next_index_)
   {
      this.execution_next_index_ = execution_next_index_;
   }

   public boolean getManualExecutionRequested()
   {
      return manual_execution_requested_;
   }

   public void setManualExecutionRequested(boolean manual_execution_requested_)
   {
      this.manual_execution_requested_ = manual_execution_requested_;
   }

   public boolean getConcurrencyEnabled()
   {
      return concurrency_enabled_;
   }

   public void setConcurrencyEnabled(boolean concurrency_enabled_)
   {
      this.concurrency_enabled_ = concurrency_enabled_;
   }

   public boolean getFailureResetRequested()
   {
      return failure_reset_requested_;
   }

   public void setFailureResetRequested(boolean failure_reset_requested_)
   {
      this.failure_reset_requested_ = failure_reset_requested_;
   }


}