/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/CheckPointNodeStateMessage):
<pre>{@code
# Parent state fields
behavior_msgs/LeafNodeStateMessage state

# Definition
behavior_msgs/CheckPointNodeDefinitionMessage definition
}</pre>
*/
public class CheckPointNodeStateMessage implements ROS2Message<CheckPointNodeStateMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::CheckPointNodeStateMessage_";

   /**
      Parent state fields
   */
   private final behavior_msgs.msg.dds.LeafNodeStateMessage state_;
   /**
      Definition
   */
   private final behavior_msgs.msg.dds.CheckPointNodeDefinitionMessage definition_;

   public CheckPointNodeStateMessage()
   {
      state_ = new behavior_msgs.msg.dds.LeafNodeStateMessage();
      definition_ = new behavior_msgs.msg.dds.CheckPointNodeDefinitionMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += state_.calculateSizeBytes(currentAlignment);
      currentAlignment += definition_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      state_.serialize(buffer);
      definition_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      state_.deserialize(buffer);
      definition_.deserialize(buffer);

   }

   @Override
   public void set(CheckPointNodeStateMessage from)
   {
      state_.set(from.state_);
      definition_.set(from.definition_);

   }

   public behavior_msgs.msg.dds.LeafNodeStateMessage getState()
   {
      return state_;
   }

   public behavior_msgs.msg.dds.CheckPointNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }


}