/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/ChestOrientationActionDefinitionMessage):
<pre>{@code
# Parent definition fields
behavior_msgs/ActionNodeDefinitionMessage definition

# Name of the frame the this action is expressed in
string parent_frame_name

# Transform that expresses the chest pose in the parent frame
controller_msgs/RigidBodyTransformMessage chest_transform_to_parent

# Duration of the trajectory
float64 trajectory_duration

# Whether maintaining the rigid body controlled in world after the action is complete
bool hold_pose_in_world}</pre>
*/
public class ChestOrientationActionDefinitionMessage implements ROS2Message<ChestOrientationActionDefinitionMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::ChestOrientationActionDefinitionMessage_";

   /**
      Parent definition fields
   */
   private final behavior_msgs.msg.dds.ActionNodeDefinitionMessage definition_;
   /**
      Name of the frame the this action is expressed in
   */
   private final StringBuilder parent_frame_name_;
   /**
      Transform that expresses the chest pose in the parent frame
   */
   private final controller_msgs.msg.dds.RigidBodyTransformMessage chest_transform_to_parent_;
   /**
      Duration of the trajectory
   */
   private double trajectory_duration_;
   /**
      Whether maintaining the rigid body controlled in world after the action is complete
   */
   private boolean hold_pose_in_world_;

   public ChestOrientationActionDefinitionMessage()
   {
      definition_ = new behavior_msgs.msg.dds.ActionNodeDefinitionMessage();
      parent_frame_name_ = new StringBuilder();
      chest_transform_to_parent_ = new controller_msgs.msg.dds.RigidBodyTransformMessage();
      hold_pose_in_world_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * parent_frame_name_.length()) + 1; // parent_frame_name_
      currentAlignment += chest_transform_to_parent_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // trajectory_duration_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // hold_pose_in_world_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      definition_.serialize(buffer);
      buffer.writeString(parent_frame_name_);
      chest_transform_to_parent_.serialize(buffer);
      buffer.writeDouble(trajectory_duration_);
      buffer.writeBoolean(hold_pose_in_world_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      definition_.deserialize(buffer);
      buffer.readString(parent_frame_name_);
      chest_transform_to_parent_.deserialize(buffer);
      trajectory_duration_ = buffer.readDouble();
      hold_pose_in_world_ = buffer.readBoolean();

   }

   @Override
   public void set(ChestOrientationActionDefinitionMessage from)
   {
      definition_.set(from.definition_);
      parent_frame_name_.delete(0, parent_frame_name_.length());
      parent_frame_name_.insert(0, from.parent_frame_name_);
      chest_transform_to_parent_.set(from.chest_transform_to_parent_);
      trajectory_duration_ = from.trajectory_duration_;
      hold_pose_in_world_ = from.hold_pose_in_world_;

   }

   public behavior_msgs.msg.dds.ActionNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public StringBuilder getParentFrameName()
   {
      return parent_frame_name_;
   }

   public controller_msgs.msg.dds.RigidBodyTransformMessage getChestTransformToParent()
   {
      return chest_transform_to_parent_;
   }

   public double getTrajectoryDuration()
   {
      return trajectory_duration_;
   }

   public void setTrajectoryDuration(double trajectory_duration_)
   {
      this.trajectory_duration_ = trajectory_duration_;
   }

   public boolean getHoldPoseInWorld()
   {
      return hold_pose_in_world_;
   }

   public void setHoldPoseInWorld(boolean hold_pose_in_world_)
   {
      this.hold_pose_in_world_ = hold_pose_in_world_;
   }


}