/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/ConditionNodeDefinitionMessage):
<pre>{@code
# Parent definition fields
behavior_msgs/LeafNodeDefinitionMessage definition

byte COUNTER_TYPE = 0
byte LLM_TYPE = 1
byte PROXIMITY_TYPE = 2

# The type of condition as defined above
byte type

# COUNTER TYPE

# The number of times to fail before passing
uint32 count_to

# LLM TYPE

# Whether to reset the context on each run
bool reset_context_each_run

# Whether to generate behavior state information and add it to the prompt
bool inject_behavior_state

# Whether to generate environment state information and add it to the prompt
bool inject_environment_state

# If a response match indicates success, else a match indicates failure
bool match_is_success

# The prompt given once at the very beginning
string<=10000 system

# The prompt defining how to make the boolean decision
string<=10000 prompt

# A regular expression, where if it matches, the execution failed
string<=10000 response_matcher

# PROXIMITY TYPE

byte PROXIMITY_XYZ = 0
byte PROXIMITY_XY = 1
byte PROXIMITY_Z = 2

# The type of distance condition as defined above
byte proximity_distance_type

# Name of the object frame
string proximity_object_frame_name

# Name of the frame the distance is expressed in
string proximity_reference_frame_name

# The maximum distance between the object and the reference frame
float64 proximity_distance_to_object

# The maximum time that is spent in evaluating the condition
float64 proximity_evaluation_time

# Whether the failure of missing frame is handled internally by the condition node or not
bool manage_missing_frame_internally}</pre>
*/
public class ConditionNodeDefinitionMessage implements ROS2Message<ConditionNodeDefinitionMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::ConditionNodeDefinitionMessage_";

   /**
      Parent definition fields
   */
   private final behavior_msgs.msg.dds.LeafNodeDefinitionMessage definition_;
   public static final byte COUNTER_TYPE = 0;
   public static final byte LLM_TYPE = 1;
   public static final byte PROXIMITY_TYPE = 2;
   /**
      The type of condition as defined above
   */
   private byte type_;
   /**
      The number of times to fail before passing
   */
   private int count_to_;
   /**
      Whether to reset the context on each run
   */
   private boolean reset_context_each_run_;
   /**
      Whether to generate behavior state information and add it to the prompt
   */
   private boolean inject_behavior_state_;
   /**
      Whether to generate environment state information and add it to the prompt
   */
   private boolean inject_environment_state_;
   /**
      If a response match indicates success, else a match indicates failure
   */
   private boolean match_is_success_;
   /**
      The prompt given once at the very beginning
   */
   // Note: The length of this string should not exceed 10000 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder system_;
   /**
      The prompt defining how to make the boolean decision
   */
   // Note: The length of this string should not exceed 10000 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder prompt_;
   /**
      A regular expression, where if it matches, the execution failed
   */
   // Note: The length of this string should not exceed 10000 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder response_matcher_;
   public static final byte PROXIMITY_XYZ = 0;
   public static final byte PROXIMITY_XY = 1;
   public static final byte PROXIMITY_Z = 2;
   /**
      The type of distance condition as defined above
   */
   private byte proximity_distance_type_;
   /**
      Name of the object frame
   */
   private final StringBuilder proximity_object_frame_name_;
   /**
      Name of the frame the distance is expressed in
   */
   private final StringBuilder proximity_reference_frame_name_;
   /**
      The maximum distance between the object and the reference frame
   */
   private double proximity_distance_to_object_;
   /**
      The maximum time that is spent in evaluating the condition
   */
   private double proximity_evaluation_time_;
   /**
      Whether the failure of missing frame is handled internally by the condition node or not
   */
   private boolean manage_missing_frame_internally_;

   public ConditionNodeDefinitionMessage()
   {
      definition_ = new behavior_msgs.msg.dds.LeafNodeDefinitionMessage();
      reset_context_each_run_ = (boolean) false;
      inject_behavior_state_ = (boolean) false;
      inject_environment_state_ = (boolean) false;
      match_is_success_ = (boolean) false;
      system_ = new StringBuilder(10000);
      prompt_ = new StringBuilder(10000);
      response_matcher_ = new StringBuilder(10000);
      proximity_object_frame_name_ = new StringBuilder();
      proximity_reference_frame_name_ = new StringBuilder();
      manage_missing_frame_internally_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // count_to_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // reset_context_each_run_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // inject_behavior_state_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // inject_environment_state_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // match_is_success_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * system_.length()) + 1; // system_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * prompt_.length()) + 1; // prompt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * response_matcher_.length()) + 1; // response_matcher_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // proximity_distance_type_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * proximity_object_frame_name_.length()) + 1; // proximity_object_frame_name_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * proximity_reference_frame_name_.length()) + 1; // proximity_reference_frame_name_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // proximity_distance_to_object_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // proximity_evaluation_time_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // manage_missing_frame_internally_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      definition_.serialize(buffer);
      buffer.writeByte(type_);
      buffer.writeInt(count_to_);
      buffer.writeBoolean(reset_context_each_run_);
      buffer.writeBoolean(inject_behavior_state_);
      buffer.writeBoolean(inject_environment_state_);
      buffer.writeBoolean(match_is_success_);
      buffer.writeString(system_);
      buffer.writeString(prompt_);
      buffer.writeString(response_matcher_);
      buffer.writeByte(proximity_distance_type_);
      buffer.writeString(proximity_object_frame_name_);
      buffer.writeString(proximity_reference_frame_name_);
      buffer.writeDouble(proximity_distance_to_object_);
      buffer.writeDouble(proximity_evaluation_time_);
      buffer.writeBoolean(manage_missing_frame_internally_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      definition_.deserialize(buffer);
      type_ = buffer.readByte();
      count_to_ = buffer.readInt();
      reset_context_each_run_ = buffer.readBoolean();
      inject_behavior_state_ = buffer.readBoolean();
      inject_environment_state_ = buffer.readBoolean();
      match_is_success_ = buffer.readBoolean();
      buffer.readString(system_);
      buffer.readString(prompt_);
      buffer.readString(response_matcher_);
      proximity_distance_type_ = buffer.readByte();
      buffer.readString(proximity_object_frame_name_);
      buffer.readString(proximity_reference_frame_name_);
      proximity_distance_to_object_ = buffer.readDouble();
      proximity_evaluation_time_ = buffer.readDouble();
      manage_missing_frame_internally_ = buffer.readBoolean();

   }

   @Override
   public void set(ConditionNodeDefinitionMessage from)
   {
      definition_.set(from.definition_);
      type_ = from.type_;
      count_to_ = from.count_to_;
      reset_context_each_run_ = from.reset_context_each_run_;
      inject_behavior_state_ = from.inject_behavior_state_;
      inject_environment_state_ = from.inject_environment_state_;
      match_is_success_ = from.match_is_success_;
      system_.delete(0, system_.length());
      system_.insert(0, from.system_);
      prompt_.delete(0, prompt_.length());
      prompt_.insert(0, from.prompt_);
      response_matcher_.delete(0, response_matcher_.length());
      response_matcher_.insert(0, from.response_matcher_);
      proximity_distance_type_ = from.proximity_distance_type_;
      proximity_object_frame_name_.delete(0, proximity_object_frame_name_.length());
      proximity_object_frame_name_.insert(0, from.proximity_object_frame_name_);
      proximity_reference_frame_name_.delete(0, proximity_reference_frame_name_.length());
      proximity_reference_frame_name_.insert(0, from.proximity_reference_frame_name_);
      proximity_distance_to_object_ = from.proximity_distance_to_object_;
      proximity_evaluation_time_ = from.proximity_evaluation_time_;
      manage_missing_frame_internally_ = from.manage_missing_frame_internally_;

   }

   public behavior_msgs.msg.dds.LeafNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }

   public int getCountTo()
   {
      return count_to_;
   }

   public void setCountTo(int count_to_)
   {
      this.count_to_ = count_to_;
   }

   public boolean getResetContextEachRun()
   {
      return reset_context_each_run_;
   }

   public void setResetContextEachRun(boolean reset_context_each_run_)
   {
      this.reset_context_each_run_ = reset_context_each_run_;
   }

   public boolean getInjectBehaviorState()
   {
      return inject_behavior_state_;
   }

   public void setInjectBehaviorState(boolean inject_behavior_state_)
   {
      this.inject_behavior_state_ = inject_behavior_state_;
   }

   public boolean getInjectEnvironmentState()
   {
      return inject_environment_state_;
   }

   public void setInjectEnvironmentState(boolean inject_environment_state_)
   {
      this.inject_environment_state_ = inject_environment_state_;
   }

   public boolean getMatchIsSuccess()
   {
      return match_is_success_;
   }

   public void setMatchIsSuccess(boolean match_is_success_)
   {
      this.match_is_success_ = match_is_success_;
   }

   public StringBuilder getSystem()
   {
      return system_;
   }

   public StringBuilder getPrompt()
   {
      return prompt_;
   }

   public StringBuilder getResponseMatcher()
   {
      return response_matcher_;
   }

   public byte getProximityDistanceType()
   {
      return proximity_distance_type_;
   }

   public void setProximityDistanceType(byte proximity_distance_type_)
   {
      this.proximity_distance_type_ = proximity_distance_type_;
   }

   public StringBuilder getProximityObjectFrameName()
   {
      return proximity_object_frame_name_;
   }

   public StringBuilder getProximityReferenceFrameName()
   {
      return proximity_reference_frame_name_;
   }

   public double getProximityDistanceToObject()
   {
      return proximity_distance_to_object_;
   }

   public void setProximityDistanceToObject(double proximity_distance_to_object_)
   {
      this.proximity_distance_to_object_ = proximity_distance_to_object_;
   }

   public double getProximityEvaluationTime()
   {
      return proximity_evaluation_time_;
   }

   public void setProximityEvaluationTime(double proximity_evaluation_time_)
   {
      this.proximity_evaluation_time_ = proximity_evaluation_time_;
   }

   public boolean getManageMissingFrameInternally()
   {
      return manage_missing_frame_internally_;
   }

   public void setManageMissingFrameInternally(boolean manage_missing_frame_internally_)
   {
      this.manage_missing_frame_internally_ = manage_missing_frame_internally_;
   }


}