/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/ConditionNodeStateMessage):
<pre>{@code
# Parent state fields
behavior_msgs/LeafNodeStateMessage state

# Definition
behavior_msgs/ConditionNodeDefinitionMessage definition

# COUNTER TYPE

# The current count of the counter
uint32 count

# LLM TYPE

# A request to reset the LLM's context now
bool request_reset_context

# PROXIMITY TYPE

# The current distance of the object from the reference frame
float64 current_distance

# Whether frame to evaluate the proximity is missing
bool missing_frame
}</pre>
*/
public class ConditionNodeStateMessage implements ROS2Message<ConditionNodeStateMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::ConditionNodeStateMessage_";

   /**
      Parent state fields
   */
   private final behavior_msgs.msg.dds.LeafNodeStateMessage state_;
   /**
      Definition
   */
   private final behavior_msgs.msg.dds.ConditionNodeDefinitionMessage definition_;
   /**
      The current count of the counter
   */
   private int count_;
   /**
      A request to reset the LLM's context now
   */
   private boolean request_reset_context_;
   /**
      The current distance of the object from the reference frame
   */
   private double current_distance_;
   /**
      Whether frame to evaluate the proximity is missing
   */
   private boolean missing_frame_;

   public ConditionNodeStateMessage()
   {
      state_ = new behavior_msgs.msg.dds.LeafNodeStateMessage();
      definition_ = new behavior_msgs.msg.dds.ConditionNodeDefinitionMessage();
      request_reset_context_ = (boolean) false;
      missing_frame_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += state_.calculateSizeBytes(currentAlignment);
      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // count_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_reset_context_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // current_distance_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // missing_frame_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      state_.serialize(buffer);
      definition_.serialize(buffer);
      buffer.writeInt(count_);
      buffer.writeBoolean(request_reset_context_);
      buffer.writeDouble(current_distance_);
      buffer.writeBoolean(missing_frame_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      state_.deserialize(buffer);
      definition_.deserialize(buffer);
      count_ = buffer.readInt();
      request_reset_context_ = buffer.readBoolean();
      current_distance_ = buffer.readDouble();
      missing_frame_ = buffer.readBoolean();

   }

   @Override
   public void set(ConditionNodeStateMessage from)
   {
      state_.set(from.state_);
      definition_.set(from.definition_);
      count_ = from.count_;
      request_reset_context_ = from.request_reset_context_;
      current_distance_ = from.current_distance_;
      missing_frame_ = from.missing_frame_;

   }

   public behavior_msgs.msg.dds.LeafNodeStateMessage getState()
   {
      return state_;
   }

   public behavior_msgs.msg.dds.ConditionNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public int getCount()
   {
      return count_;
   }

   public void setCount(int count_)
   {
      this.count_ = count_;
   }

   public boolean getRequestResetContext()
   {
      return request_reset_context_;
   }

   public void setRequestResetContext(boolean request_reset_context_)
   {
      this.request_reset_context_ = request_reset_context_;
   }

   public double getCurrentDistance()
   {
      return current_distance_;
   }

   public void setCurrentDistance(double current_distance_)
   {
      this.current_distance_ = current_distance_;
   }

   public boolean getMissingFrame()
   {
      return missing_frame_;
   }

   public void setMissingFrame(boolean missing_frame_)
   {
      this.missing_frame_ = missing_frame_;
   }


}