/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/DoorTraversalDefinitionMessage):
<pre>{@code
# Parent definition fields
behavior_msgs/BehaviorTreeNodeDefinitionMessage definition

# The hand open angle to assume we lost the grasp on the object
float64 lost_grasp_detection_hand_open_angle

float64 opened_door_handle_distance_from_start}</pre>
*/
public class DoorTraversalDefinitionMessage implements ROS2Message<DoorTraversalDefinitionMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::DoorTraversalDefinitionMessage_";

   /**
      Parent definition fields
   */
   private final behavior_msgs.msg.dds.BehaviorTreeNodeDefinitionMessage definition_;
   /**
      The hand open angle to assume we lost the grasp on the object
   */
   private double lost_grasp_detection_hand_open_angle_;
   private double opened_door_handle_distance_from_start_;

   public DoorTraversalDefinitionMessage()
   {
      definition_ = new behavior_msgs.msg.dds.BehaviorTreeNodeDefinitionMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // lost_grasp_detection_hand_open_angle_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // opened_door_handle_distance_from_start_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      definition_.serialize(buffer);
      buffer.writeDouble(lost_grasp_detection_hand_open_angle_);
      buffer.writeDouble(opened_door_handle_distance_from_start_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      definition_.deserialize(buffer);
      lost_grasp_detection_hand_open_angle_ = buffer.readDouble();
      opened_door_handle_distance_from_start_ = buffer.readDouble();

   }

   @Override
   public void set(DoorTraversalDefinitionMessage from)
   {
      definition_.set(from.definition_);
      lost_grasp_detection_hand_open_angle_ = from.lost_grasp_detection_hand_open_angle_;
      opened_door_handle_distance_from_start_ = from.opened_door_handle_distance_from_start_;

   }

   public behavior_msgs.msg.dds.BehaviorTreeNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public double getLostGraspDetectionHandOpenAngle()
   {
      return lost_grasp_detection_hand_open_angle_;
   }

   public void setLostGraspDetectionHandOpenAngle(double lost_grasp_detection_hand_open_angle_)
   {
      this.lost_grasp_detection_hand_open_angle_ = lost_grasp_detection_hand_open_angle_;
   }

   public double getOpenedDoorHandleDistanceFromStart()
   {
      return opened_door_handle_distance_from_start_;
   }

   public void setOpenedDoorHandleDistanceFromStart(double opened_door_handle_distance_from_start_)
   {
      this.opened_door_handle_distance_from_start_ = opened_door_handle_distance_from_start_;
   }


}