/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/DoorTraversalStateMessage):
<pre>{@code
# Parent state fields
behavior_msgs/BehaviorTreeNodeStateMessage state

# Definition
behavior_msgs/DoorTraversalDefinitionMessage definition

float64 door_hinge_joint_angle

float64 door_handle_distance_from_start
}</pre>
*/
public class DoorTraversalStateMessage implements ROS2Message<DoorTraversalStateMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::DoorTraversalStateMessage_";

   /**
      Parent state fields
   */
   private final behavior_msgs.msg.dds.BehaviorTreeNodeStateMessage state_;
   /**
      Definition
   */
   private final behavior_msgs.msg.dds.DoorTraversalDefinitionMessage definition_;
   private double door_hinge_joint_angle_;
   private double door_handle_distance_from_start_;

   public DoorTraversalStateMessage()
   {
      state_ = new behavior_msgs.msg.dds.BehaviorTreeNodeStateMessage();
      definition_ = new behavior_msgs.msg.dds.DoorTraversalDefinitionMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += state_.calculateSizeBytes(currentAlignment);
      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // door_hinge_joint_angle_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // door_handle_distance_from_start_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      state_.serialize(buffer);
      definition_.serialize(buffer);
      buffer.writeDouble(door_hinge_joint_angle_);
      buffer.writeDouble(door_handle_distance_from_start_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      state_.deserialize(buffer);
      definition_.deserialize(buffer);
      door_hinge_joint_angle_ = buffer.readDouble();
      door_handle_distance_from_start_ = buffer.readDouble();

   }

   @Override
   public void set(DoorTraversalStateMessage from)
   {
      state_.set(from.state_);
      definition_.set(from.definition_);
      door_hinge_joint_angle_ = from.door_hinge_joint_angle_;
      door_handle_distance_from_start_ = from.door_handle_distance_from_start_;

   }

   public behavior_msgs.msg.dds.BehaviorTreeNodeStateMessage getState()
   {
      return state_;
   }

   public behavior_msgs.msg.dds.DoorTraversalDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public double getDoorHingeJointAngle()
   {
      return door_hinge_joint_angle_;
   }

   public void setDoorHingeJointAngle(double door_hinge_joint_angle_)
   {
      this.door_hinge_joint_angle_ = door_hinge_joint_angle_;
   }

   public double getDoorHandleDistanceFromStart()
   {
      return door_handle_distance_from_start_;
   }

   public void setDoorHandleDistanceFromStart(double door_handle_distance_from_start_)
   {
      this.door_handle_distance_from_start_ = door_handle_distance_from_start_;
   }


}