/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/FallbackNodeDefinitionMessage):
<pre>{@code
# Parent definition fields
behavior_msgs/BehaviorTreeNodeDefinitionMessage definition

}</pre>
*/
public class FallbackNodeDefinitionMessage implements ROS2Message<FallbackNodeDefinitionMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::FallbackNodeDefinitionMessage_";

   /**
      Parent definition fields
   */
   private final behavior_msgs.msg.dds.BehaviorTreeNodeDefinitionMessage definition_;

   public FallbackNodeDefinitionMessage()
   {
      definition_ = new behavior_msgs.msg.dds.BehaviorTreeNodeDefinitionMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += definition_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      definition_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      definition_.deserialize(buffer);

   }

   @Override
   public void set(FallbackNodeDefinitionMessage from)
   {
      definition_.set(from.definition_);

   }

   public behavior_msgs.msg.dds.BehaviorTreeNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }


}