/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A single footstep
<p>Source (behavior_msgs/FootstepPlanActionFootstepDefinitionMessage):
<pre>{@code
# A single footstep

# Side, left or right foot
byte robot_side 255

# The footstep's sole pose
geometry_msgs/Pose sole_pose}</pre>
*/
public class FootstepPlanActionFootstepDefinitionMessage implements ROS2Message<FootstepPlanActionFootstepDefinitionMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::FootstepPlanActionFootstepDefinitionMessage_";

   /**
      Side, left or right foot
   */
   private byte robot_side_;
   /**
      The footstep's sole pose
   */
   private final geometry_msgs.msg.dds.Pose sole_pose_;

   public FootstepPlanActionFootstepDefinitionMessage()
   {
      robot_side_ = (byte) 255;
      sole_pose_ = new geometry_msgs.msg.dds.Pose();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_
      currentAlignment += sole_pose_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(robot_side_);
      sole_pose_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      robot_side_ = buffer.readByte();
      sole_pose_.deserialize(buffer);

   }

   @Override
   public void set(FootstepPlanActionFootstepDefinitionMessage from)
   {
      robot_side_ = from.robot_side_;
      sole_pose_.set(from.sole_pose_);

   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }

   public geometry_msgs.msg.dds.Pose getSolePose()
   {
      return sole_pose_;
   }


}