/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/FootstepPlanActionFootstepStateMessage):
<pre>{@code
# Footsteps don't have a state currently
}</pre>
*/
public class FootstepPlanActionFootstepStateMessage implements ROS2Message<FootstepPlanActionFootstepStateMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::FootstepPlanActionFootstepStateMessage_";

   public FootstepPlanActionFootstepStateMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public void set(FootstepPlanActionFootstepStateMessage from)
   {
   }

}