/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/FootstepPlanActionDefinitionMessage):
<pre>{@code
# Parent definition fields
behavior_msgs/ActionNodeDefinitionMessage definition

# Name of the parent frame the footsteps are expressed in
string parent_frame_name

# Swing duration
float64 swing_duration

# Transfer duration
float64 transfer_duration

# OVERRIDE (0) or QUEUE (1)
byte execution_mode

# Is using the footstep planner or manually placing
bool is_manually_placed

# The footsteps, with a maximum of 50
behavior_msgs/FootstepPlanActionFootstepDefinitionMessage[<=50] footsteps

# The position to which the goal stance is aligned
geometry_msgs/Point goal_stance_point

# The point that the robot should be facing in the goal stance
geometry_msgs/Point goal_focal_point

# Left goal foot X to the goal pose
float64 left_goal_foot_x_to_gizmo

# Left goal foot Y to the goal pose
float64 left_goal_foot_y_to_gizmo

# Left goal foot Yaw to the goal pose
float64 left_goal_foot_yaw_to_gizmo

# Right goal foot X to the goal pose
float64 right_goal_foot_x_to_gizmo

# Right goal foot Y to the goal pose
float64 right_goal_foot_y_to_gizmo

# Right goal foot Yaw to the goal pose
float64 right_goal_foot_yaw_to_gizmo

# Initial stance side when planning
byte planner_initial_stance_side

# Whether to perform A* search in the planner
bool planner_perform_a_star_search

# Whether to walk, turning first, matching the goal orientation
bool planner_walk_with_goal_orientation

# The footstep planner parameters
ihmc_common_msgs/PrimitiveDataVectorMessage planner_parameters
}</pre>
*/
public class FootstepPlanActionDefinitionMessage implements ROS2Message<FootstepPlanActionDefinitionMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::FootstepPlanActionDefinitionMessage_";

   /**
      Parent definition fields
   */
   private final behavior_msgs.msg.dds.ActionNodeDefinitionMessage definition_;
   /**
      Name of the parent frame the footsteps are expressed in
   */
   private final StringBuilder parent_frame_name_;
   /**
      Swing duration
   */
   private double swing_duration_;
   /**
      Transfer duration
   */
   private double transfer_duration_;
   /**
      OVERRIDE (0) or QUEUE (1)
   */
   private byte execution_mode_;
   /**
      Is using the footstep planner or manually placing
   */
   private boolean is_manually_placed_;
   /**
      The footsteps, with a maximum of 50
   */
   private final IDLObjectSequence<behavior_msgs.msg.dds.FootstepPlanActionFootstepDefinitionMessage> footsteps_;
   /**
      The position to which the goal stance is aligned
   */
   private final geometry_msgs.msg.dds.Point goal_stance_point_;
   /**
      The point that the robot should be facing in the goal stance
   */
   private final geometry_msgs.msg.dds.Point goal_focal_point_;
   /**
      Left goal foot X to the goal pose
   */
   private double left_goal_foot_x_to_gizmo_;
   /**
      Left goal foot Y to the goal pose
   */
   private double left_goal_foot_y_to_gizmo_;
   /**
      Left goal foot Yaw to the goal pose
   */
   private double left_goal_foot_yaw_to_gizmo_;
   /**
      Right goal foot X to the goal pose
   */
   private double right_goal_foot_x_to_gizmo_;
   /**
      Right goal foot Y to the goal pose
   */
   private double right_goal_foot_y_to_gizmo_;
   /**
      Right goal foot Yaw to the goal pose
   */
   private double right_goal_foot_yaw_to_gizmo_;
   /**
      Initial stance side when planning
   */
   private byte planner_initial_stance_side_;
   /**
      Whether to perform A* search in the planner
   */
   private boolean planner_perform_a_star_search_;
   /**
      Whether to walk, turning first, matching the goal orientation
   */
   private boolean planner_walk_with_goal_orientation_;
   /**
      The footstep planner parameters
   */
   private final ihmc_common_msgs.msg.dds.PrimitiveDataVectorMessage planner_parameters_;

   public FootstepPlanActionDefinitionMessage()
   {
      definition_ = new behavior_msgs.msg.dds.ActionNodeDefinitionMessage();
      parent_frame_name_ = new StringBuilder();
      is_manually_placed_ = (boolean) false;
      footsteps_ = new IDLObjectSequence<behavior_msgs.msg.dds.FootstepPlanActionFootstepDefinitionMessage>(50, behavior_msgs.msg.dds.FootstepPlanActionFootstepDefinitionMessage.class);
      goal_stance_point_ = new geometry_msgs.msg.dds.Point();
      goal_focal_point_ = new geometry_msgs.msg.dds.Point();
      planner_perform_a_star_search_ = (boolean) false;
      planner_walk_with_goal_orientation_ = (boolean) false;
      planner_parameters_ = new ihmc_common_msgs.msg.dds.PrimitiveDataVectorMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * parent_frame_name_.length()) + 1; // parent_frame_name_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // swing_duration_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // transfer_duration_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // execution_mode_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_manually_placed_
      currentAlignment += footsteps_.calculateSizeBytes(currentAlignment);
      currentAlignment += goal_stance_point_.calculateSizeBytes(currentAlignment);
      currentAlignment += goal_focal_point_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // left_goal_foot_x_to_gizmo_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // left_goal_foot_y_to_gizmo_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // left_goal_foot_yaw_to_gizmo_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // right_goal_foot_x_to_gizmo_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // right_goal_foot_y_to_gizmo_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // right_goal_foot_yaw_to_gizmo_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // planner_initial_stance_side_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // planner_perform_a_star_search_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // planner_walk_with_goal_orientation_
      currentAlignment += planner_parameters_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      definition_.serialize(buffer);
      buffer.writeString(parent_frame_name_);
      buffer.writeDouble(swing_duration_);
      buffer.writeDouble(transfer_duration_);
      buffer.writeByte(execution_mode_);
      buffer.writeBoolean(is_manually_placed_);
      footsteps_.serialize(buffer);
      goal_stance_point_.serialize(buffer);
      goal_focal_point_.serialize(buffer);
      buffer.writeDouble(left_goal_foot_x_to_gizmo_);
      buffer.writeDouble(left_goal_foot_y_to_gizmo_);
      buffer.writeDouble(left_goal_foot_yaw_to_gizmo_);
      buffer.writeDouble(right_goal_foot_x_to_gizmo_);
      buffer.writeDouble(right_goal_foot_y_to_gizmo_);
      buffer.writeDouble(right_goal_foot_yaw_to_gizmo_);
      buffer.writeByte(planner_initial_stance_side_);
      buffer.writeBoolean(planner_perform_a_star_search_);
      buffer.writeBoolean(planner_walk_with_goal_orientation_);
      planner_parameters_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      definition_.deserialize(buffer);
      buffer.readString(parent_frame_name_);
      swing_duration_ = buffer.readDouble();
      transfer_duration_ = buffer.readDouble();
      execution_mode_ = buffer.readByte();
      is_manually_placed_ = buffer.readBoolean();
      footsteps_.deserialize(buffer);
      goal_stance_point_.deserialize(buffer);
      goal_focal_point_.deserialize(buffer);
      left_goal_foot_x_to_gizmo_ = buffer.readDouble();
      left_goal_foot_y_to_gizmo_ = buffer.readDouble();
      left_goal_foot_yaw_to_gizmo_ = buffer.readDouble();
      right_goal_foot_x_to_gizmo_ = buffer.readDouble();
      right_goal_foot_y_to_gizmo_ = buffer.readDouble();
      right_goal_foot_yaw_to_gizmo_ = buffer.readDouble();
      planner_initial_stance_side_ = buffer.readByte();
      planner_perform_a_star_search_ = buffer.readBoolean();
      planner_walk_with_goal_orientation_ = buffer.readBoolean();
      planner_parameters_.deserialize(buffer);

   }

   @Override
   public void set(FootstepPlanActionDefinitionMessage from)
   {
      definition_.set(from.definition_);
      parent_frame_name_.delete(0, parent_frame_name_.length());
      parent_frame_name_.insert(0, from.parent_frame_name_);
      swing_duration_ = from.swing_duration_;
      transfer_duration_ = from.transfer_duration_;
      execution_mode_ = from.execution_mode_;
      is_manually_placed_ = from.is_manually_placed_;
      footsteps_.set(from.footsteps_);
      goal_stance_point_.set(from.goal_stance_point_);
      goal_focal_point_.set(from.goal_focal_point_);
      left_goal_foot_x_to_gizmo_ = from.left_goal_foot_x_to_gizmo_;
      left_goal_foot_y_to_gizmo_ = from.left_goal_foot_y_to_gizmo_;
      left_goal_foot_yaw_to_gizmo_ = from.left_goal_foot_yaw_to_gizmo_;
      right_goal_foot_x_to_gizmo_ = from.right_goal_foot_x_to_gizmo_;
      right_goal_foot_y_to_gizmo_ = from.right_goal_foot_y_to_gizmo_;
      right_goal_foot_yaw_to_gizmo_ = from.right_goal_foot_yaw_to_gizmo_;
      planner_initial_stance_side_ = from.planner_initial_stance_side_;
      planner_perform_a_star_search_ = from.planner_perform_a_star_search_;
      planner_walk_with_goal_orientation_ = from.planner_walk_with_goal_orientation_;
      planner_parameters_.set(from.planner_parameters_);

   }

   public behavior_msgs.msg.dds.ActionNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public StringBuilder getParentFrameName()
   {
      return parent_frame_name_;
   }

   public double getSwingDuration()
   {
      return swing_duration_;
   }

   public void setSwingDuration(double swing_duration_)
   {
      this.swing_duration_ = swing_duration_;
   }

   public double getTransferDuration()
   {
      return transfer_duration_;
   }

   public void setTransferDuration(double transfer_duration_)
   {
      this.transfer_duration_ = transfer_duration_;
   }

   public byte getExecutionMode()
   {
      return execution_mode_;
   }

   public void setExecutionMode(byte execution_mode_)
   {
      this.execution_mode_ = execution_mode_;
   }

   public boolean getIsManuallyPlaced()
   {
      return is_manually_placed_;
   }

   public void setIsManuallyPlaced(boolean is_manually_placed_)
   {
      this.is_manually_placed_ = is_manually_placed_;
   }

   public IDLObjectSequence<behavior_msgs.msg.dds.FootstepPlanActionFootstepDefinitionMessage> getFootsteps()
   {
      return footsteps_;
   }

   public geometry_msgs.msg.dds.Point getGoalStancePoint()
   {
      return goal_stance_point_;
   }

   public geometry_msgs.msg.dds.Point getGoalFocalPoint()
   {
      return goal_focal_point_;
   }

   public double getLeftGoalFootXToGizmo()
   {
      return left_goal_foot_x_to_gizmo_;
   }

   public void setLeftGoalFootXToGizmo(double left_goal_foot_x_to_gizmo_)
   {
      this.left_goal_foot_x_to_gizmo_ = left_goal_foot_x_to_gizmo_;
   }

   public double getLeftGoalFootYToGizmo()
   {
      return left_goal_foot_y_to_gizmo_;
   }

   public void setLeftGoalFootYToGizmo(double left_goal_foot_y_to_gizmo_)
   {
      this.left_goal_foot_y_to_gizmo_ = left_goal_foot_y_to_gizmo_;
   }

   public double getLeftGoalFootYawToGizmo()
   {
      return left_goal_foot_yaw_to_gizmo_;
   }

   public void setLeftGoalFootYawToGizmo(double left_goal_foot_yaw_to_gizmo_)
   {
      this.left_goal_foot_yaw_to_gizmo_ = left_goal_foot_yaw_to_gizmo_;
   }

   public double getRightGoalFootXToGizmo()
   {
      return right_goal_foot_x_to_gizmo_;
   }

   public void setRightGoalFootXToGizmo(double right_goal_foot_x_to_gizmo_)
   {
      this.right_goal_foot_x_to_gizmo_ = right_goal_foot_x_to_gizmo_;
   }

   public double getRightGoalFootYToGizmo()
   {
      return right_goal_foot_y_to_gizmo_;
   }

   public void setRightGoalFootYToGizmo(double right_goal_foot_y_to_gizmo_)
   {
      this.right_goal_foot_y_to_gizmo_ = right_goal_foot_y_to_gizmo_;
   }

   public double getRightGoalFootYawToGizmo()
   {
      return right_goal_foot_yaw_to_gizmo_;
   }

   public void setRightGoalFootYawToGizmo(double right_goal_foot_yaw_to_gizmo_)
   {
      this.right_goal_foot_yaw_to_gizmo_ = right_goal_foot_yaw_to_gizmo_;
   }

   public byte getPlannerInitialStanceSide()
   {
      return planner_initial_stance_side_;
   }

   public void setPlannerInitialStanceSide(byte planner_initial_stance_side_)
   {
      this.planner_initial_stance_side_ = planner_initial_stance_side_;
   }

   public boolean getPlannerPerformAStarSearch()
   {
      return planner_perform_a_star_search_;
   }

   public void setPlannerPerformAStarSearch(boolean planner_perform_a_star_search_)
   {
      this.planner_perform_a_star_search_ = planner_perform_a_star_search_;
   }

   public boolean getPlannerWalkWithGoalOrientation()
   {
      return planner_walk_with_goal_orientation_;
   }

   public void setPlannerWalkWithGoalOrientation(boolean planner_walk_with_goal_orientation_)
   {
      this.planner_walk_with_goal_orientation_ = planner_walk_with_goal_orientation_;
   }

   public ihmc_common_msgs.msg.dds.PrimitiveDataVectorMessage getPlannerParameters()
   {
      return planner_parameters_;
   }


}