/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/MinimalFootstepMessage):
<pre>{@code
# Specifies which foot will swing to reach the footstep.
# Field default value 255
int8 robot_side

# Specifies the position of the footstep (sole frame) in world frame.
geometry_msgs/Point position

# Specifies the orientation of the footstep (sole frame) in world frame.
geometry_msgs/Quaternion orientation

# Support polygon
ihmc_common_msgs/Point2DMessage[<=16] support_polygon

# Description of the footstep
string description}</pre>
*/
public class MinimalFootstepMessage implements ROS2Message<MinimalFootstepMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::MinimalFootstepMessage_";

   /**
      Specifies which foot will swing to reach the footstep.
      Field default value 255
   */
   private byte robot_side_;
   /**
      Specifies the position of the footstep (sole frame) in world frame.
   */
   private final geometry_msgs.msg.dds.Point position_;
   /**
      Specifies the orientation of the footstep (sole frame) in world frame.
   */
   private final geometry_msgs.msg.dds.Quaternion orientation_;
   /**
      Support polygon
   */
   private final IDLObjectSequence<ihmc_common_msgs.msg.dds.Point2DMessage> support_polygon_;
   /**
      Description of the footstep
   */
   private final StringBuilder description_;

   public MinimalFootstepMessage()
   {
      position_ = new geometry_msgs.msg.dds.Point();
      orientation_ = new geometry_msgs.msg.dds.Quaternion();
      support_polygon_ = new IDLObjectSequence<ihmc_common_msgs.msg.dds.Point2DMessage>(16, ihmc_common_msgs.msg.dds.Point2DMessage.class);
      description_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_
      currentAlignment += position_.calculateSizeBytes(currentAlignment);
      currentAlignment += orientation_.calculateSizeBytes(currentAlignment);
      currentAlignment += support_polygon_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * description_.length()) + 1; // description_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(robot_side_);
      position_.serialize(buffer);
      orientation_.serialize(buffer);
      support_polygon_.serialize(buffer);
      buffer.writeString(description_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      robot_side_ = buffer.readByte();
      position_.deserialize(buffer);
      orientation_.deserialize(buffer);
      support_polygon_.deserialize(buffer);
      buffer.readString(description_);

   }

   @Override
   public void set(MinimalFootstepMessage from)
   {
      robot_side_ = from.robot_side_;
      position_.set(from.position_);
      orientation_.set(from.orientation_);
      support_polygon_.set(from.support_polygon_);
      description_.delete(0, description_.length());
      description_.insert(0, from.description_);

   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }

   public geometry_msgs.msg.dds.Point getPosition()
   {
      return position_;
   }

   public geometry_msgs.msg.dds.Quaternion getOrientation()
   {
      return orientation_;
   }

   public IDLObjectSequence<ihmc_common_msgs.msg.dds.Point2DMessage> getSupportPolygon()
   {
      return support_polygon_;
   }

   public StringBuilder getDescription()
   {
      return description_;
   }


}