/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/SceneActionNodeStateMessage):
<pre>{@code
# Parent state fields
behavior_msgs/ActionNodeStateMessage state

# Definition
behavior_msgs/SceneActionNodeDefinitionMessage definition
}</pre>
*/
public class SceneActionNodeStateMessage implements ROS2Message<SceneActionNodeStateMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::SceneActionNodeStateMessage_";

   /**
      Parent state fields
   */
   private final behavior_msgs.msg.dds.ActionNodeStateMessage state_;
   /**
      Definition
   */
   private final behavior_msgs.msg.dds.SceneActionNodeDefinitionMessage definition_;

   public SceneActionNodeStateMessage()
   {
      state_ = new behavior_msgs.msg.dds.ActionNodeStateMessage();
      definition_ = new behavior_msgs.msg.dds.SceneActionNodeDefinitionMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += state_.calculateSizeBytes(currentAlignment);
      currentAlignment += definition_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      state_.serialize(buffer);
      definition_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      state_.deserialize(buffer);
      definition_.deserialize(buffer);

   }

   @Override
   public void set(SceneActionNodeStateMessage from)
   {
      state_.set(from.state_);
      definition_.set(from.definition_);

   }

   public behavior_msgs.msg.dds.ActionNodeStateMessage getState()
   {
      return state_;
   }

   public behavior_msgs.msg.dds.SceneActionNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }


}