/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/SceneActionNodeDefinitionMessage):
<pre>{@code
# Parent definition fields
behavior_msgs/ActionNodeDefinitionMessage definition

# Object type (enum ordinal)
byte object_type
}</pre>
*/
public class SceneActionNodeDefinitionMessage implements ROS2Message<SceneActionNodeDefinitionMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::SceneActionNodeDefinitionMessage_";

   /**
      Parent definition fields
   */
   private final behavior_msgs.msg.dds.ActionNodeDefinitionMessage definition_;
   /**
      Object type (enum ordinal)
   */
   private byte object_type_;

   public SceneActionNodeDefinitionMessage()
   {
      definition_ = new behavior_msgs.msg.dds.ActionNodeDefinitionMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // object_type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      definition_.serialize(buffer);
      buffer.writeByte(object_type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      definition_.deserialize(buffer);
      object_type_ = buffer.readByte();

   }

   @Override
   public void set(SceneActionNodeDefinitionMessage from)
   {
      definition_.set(from.definition_);
      object_type_ = from.object_type_;

   }

   public behavior_msgs.msg.dds.ActionNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public byte getObjectType()
   {
      return object_type_;
   }

   public void setObjectType(byte object_type_)
   {
      this.object_type_ = object_type_;
   }


}