/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (controller_msgs/BoundingBoxesPacket):
<pre>{@code

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

int32[] bounding_boxes_x_coordinates
int32[] bounding_boxes_y_coordinates
int32[] bounding_boxes_widths
int32[] bounding_boxes_heights
string[] labels}</pre>
*/
public class BoundingBoxesPacket implements ROS2Message<BoundingBoxesPacket>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::BoundingBoxesPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final IDLIntSequence bounding_boxes_x_coordinates_;
   private final IDLIntSequence bounding_boxes_y_coordinates_;
   private final IDLIntSequence bounding_boxes_widths_;
   private final IDLIntSequence bounding_boxes_heights_;
   private final IDLStringSequence labels_;

   public BoundingBoxesPacket()
   {
      bounding_boxes_x_coordinates_ = new IDLIntSequence();
      bounding_boxes_y_coordinates_ = new IDLIntSequence();
      bounding_boxes_widths_ = new IDLIntSequence();
      bounding_boxes_heights_ = new IDLIntSequence();
      labels_ = new IDLStringSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += bounding_boxes_x_coordinates_.calculateSizeBytes(currentAlignment);
      currentAlignment += bounding_boxes_y_coordinates_.calculateSizeBytes(currentAlignment);
      currentAlignment += bounding_boxes_widths_.calculateSizeBytes(currentAlignment);
      currentAlignment += bounding_boxes_heights_.calculateSizeBytes(currentAlignment);
      currentAlignment += labels_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      bounding_boxes_x_coordinates_.serialize(buffer);
      bounding_boxes_y_coordinates_.serialize(buffer);
      bounding_boxes_widths_.serialize(buffer);
      bounding_boxes_heights_.serialize(buffer);
      labels_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      bounding_boxes_x_coordinates_.deserialize(buffer);
      bounding_boxes_y_coordinates_.deserialize(buffer);
      bounding_boxes_widths_.deserialize(buffer);
      bounding_boxes_heights_.deserialize(buffer);
      labels_.deserialize(buffer);

   }

   @Override
   public void set(BoundingBoxesPacket from)
   {
      sequence_id_ = from.sequence_id_;
      bounding_boxes_x_coordinates_.set(from.bounding_boxes_x_coordinates_);
      bounding_boxes_y_coordinates_.set(from.bounding_boxes_y_coordinates_);
      bounding_boxes_widths_.set(from.bounding_boxes_widths_);
      bounding_boxes_heights_.set(from.bounding_boxes_heights_);
      labels_.set(from.labels_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLIntSequence getBoundingBoxesXCoordinates()
   {
      return bounding_boxes_x_coordinates_;
   }

   public IDLIntSequence getBoundingBoxesYCoordinates()
   {
      return bounding_boxes_y_coordinates_;
   }

   public IDLIntSequence getBoundingBoxesWidths()
   {
      return bounding_boxes_widths_;
   }

   public IDLIntSequence getBoundingBoxesHeights()
   {
      return bounding_boxes_heights_;
   }

   public IDLStringSequence getLabels()
   {
      return labels_;
   }


}