/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC quadruped controller API.
<p>Source (controller_msgs/ComPositionPacket):
<pre>{@code
# This message is part of the IHMC quadruped controller API.

geometry_msgs/Point position}</pre>
*/
public class ComPositionPacket implements ROS2Message<ComPositionPacket>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::ComPositionPacket_";

   private final geometry_msgs.msg.dds.Point position_;

   public ComPositionPacket()
   {
      position_ = new geometry_msgs.msg.dds.Point();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += position_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      position_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      position_.deserialize(buffer);

   }

   @Override
   public void set(ComPositionPacket from)
   {
      position_.set(from.position_);

   }

   public geometry_msgs.msg.dds.Point getPosition()
   {
      return position_;
   }


}