/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
REA parameters used to create concave hull of region
<p>Source (controller_msgs/ConcaveHullFactoryParametersMessage):
<pre>{@code
# REA parameters used to create concave hull of region

float64 edge_length_threshold 0.1
bool remove_all_triangles_with_two_border_edges true
bool allow_splitting_concave_hull true
int32 max_number_of_iterations 5000
float64 triangulation_tolerance 0.0}</pre>
*/
public class ConcaveHullFactoryParametersMessage implements ROS2Message<ConcaveHullFactoryParametersMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::ConcaveHullFactoryParametersMessage_";

   private double edge_length_threshold_;
   private boolean remove_all_triangles_with_two_border_edges_;
   private boolean allow_splitting_concave_hull_;
   private int max_number_of_iterations_;
   private double triangulation_tolerance_;

   public ConcaveHullFactoryParametersMessage()
   {
      edge_length_threshold_ = (double) 0.1;
      remove_all_triangles_with_two_border_edges_ = (boolean) true;
      allow_splitting_concave_hull_ = (boolean) true;
      max_number_of_iterations_ = (int) 5000;
      triangulation_tolerance_ = (double) 0.0;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // edge_length_threshold_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // remove_all_triangles_with_two_border_edges_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // allow_splitting_concave_hull_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // max_number_of_iterations_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // triangulation_tolerance_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(edge_length_threshold_);
      buffer.writeBoolean(remove_all_triangles_with_two_border_edges_);
      buffer.writeBoolean(allow_splitting_concave_hull_);
      buffer.writeInt(max_number_of_iterations_);
      buffer.writeDouble(triangulation_tolerance_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      edge_length_threshold_ = buffer.readDouble();
      remove_all_triangles_with_two_border_edges_ = buffer.readBoolean();
      allow_splitting_concave_hull_ = buffer.readBoolean();
      max_number_of_iterations_ = buffer.readInt();
      triangulation_tolerance_ = buffer.readDouble();

   }

   @Override
   public void set(ConcaveHullFactoryParametersMessage from)
   {
      edge_length_threshold_ = from.edge_length_threshold_;
      remove_all_triangles_with_two_border_edges_ = from.remove_all_triangles_with_two_border_edges_;
      allow_splitting_concave_hull_ = from.allow_splitting_concave_hull_;
      max_number_of_iterations_ = from.max_number_of_iterations_;
      triangulation_tolerance_ = from.triangulation_tolerance_;

   }

   public double getEdgeLengthThreshold()
   {
      return edge_length_threshold_;
   }

   public void setEdgeLengthThreshold(double edge_length_threshold_)
   {
      this.edge_length_threshold_ = edge_length_threshold_;
   }

   public boolean getRemoveAllTrianglesWithTwoBorderEdges()
   {
      return remove_all_triangles_with_two_border_edges_;
   }

   public void setRemoveAllTrianglesWithTwoBorderEdges(boolean remove_all_triangles_with_two_border_edges_)
   {
      this.remove_all_triangles_with_two_border_edges_ = remove_all_triangles_with_two_border_edges_;
   }

   public boolean getAllowSplittingConcaveHull()
   {
      return allow_splitting_concave_hull_;
   }

   public void setAllowSplittingConcaveHull(boolean allow_splitting_concave_hull_)
   {
      this.allow_splitting_concave_hull_ = allow_splitting_concave_hull_;
   }

   public int getMaxNumberOfIterations()
   {
      return max_number_of_iterations_;
   }

   public void setMaxNumberOfIterations(int max_number_of_iterations_)
   {
      this.max_number_of_iterations_ = max_number_of_iterations_;
   }

   public double getTriangulationTolerance()
   {
      return triangulation_tolerance_;
   }

   public void setTriangulationTolerance(double triangulation_tolerance_)
   {
      this.triangulation_tolerance_ = triangulation_tolerance_;
   }


}