/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Input message for the ContinuousStepGenerator.
<p>Source (controller_msgs/ContinuousStepGeneratorInputMessage):
<pre>{@code
# Input message for the ContinuousStepGenerator.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

bool walk
float64 forward_velocity
float64 lateral_velocity
float64 turn_velocity
bool unit_velocities}</pre>
*/
public class ContinuousStepGeneratorInputMessage implements ROS2Message<ContinuousStepGeneratorInputMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::ContinuousStepGeneratorInputMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private boolean walk_;
   private double forward_velocity_;
   private double lateral_velocity_;
   private double turn_velocity_;
   private boolean unit_velocities_;

   public ContinuousStepGeneratorInputMessage()
   {
      walk_ = (boolean) false;
      unit_velocities_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // walk_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // forward_velocity_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // lateral_velocity_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // turn_velocity_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // unit_velocities_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(walk_);
      buffer.writeDouble(forward_velocity_);
      buffer.writeDouble(lateral_velocity_);
      buffer.writeDouble(turn_velocity_);
      buffer.writeBoolean(unit_velocities_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      walk_ = buffer.readBoolean();
      forward_velocity_ = buffer.readDouble();
      lateral_velocity_ = buffer.readDouble();
      turn_velocity_ = buffer.readDouble();
      unit_velocities_ = buffer.readBoolean();

   }

   @Override
   public void set(ContinuousStepGeneratorInputMessage from)
   {
      sequence_id_ = from.sequence_id_;
      walk_ = from.walk_;
      forward_velocity_ = from.forward_velocity_;
      lateral_velocity_ = from.lateral_velocity_;
      turn_velocity_ = from.turn_velocity_;
      unit_velocities_ = from.unit_velocities_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getWalk()
   {
      return walk_;
   }

   public void setWalk(boolean walk_)
   {
      this.walk_ = walk_;
   }

   public double getForwardVelocity()
   {
      return forward_velocity_;
   }

   public void setForwardVelocity(double forward_velocity_)
   {
      this.forward_velocity_ = forward_velocity_;
   }

   public double getLateralVelocity()
   {
      return lateral_velocity_;
   }

   public void setLateralVelocity(double lateral_velocity_)
   {
      this.lateral_velocity_ = lateral_velocity_;
   }

   public double getTurnVelocity()
   {
      return turn_velocity_;
   }

   public void setTurnVelocity(double turn_velocity_)
   {
      this.turn_velocity_ = turn_velocity_;
   }

   public boolean getUnitVelocities()
   {
      return unit_velocities_;
   }

   public void setUnitVelocities(boolean unit_velocities_)
   {
      this.unit_velocities_ = unit_velocities_;
   }


}