/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This is a message that holds data to describe the state.

The state is defined by:
* the state at the beginning of the interval, and
* the state's rate of change during the interval,
in which the state contains the robot's posture and velocity.

The initial state and its rate of change allow us to compute the
state in a desired time.

The order of the state is designed to be consistent with the URDF.
Quaternions can be accommodated due to the different dimensions of
the state and its rate of change.
<p>Source (controller_msgs/CrocoddylStateMessage):
<pre>{@code
# This is a message that holds data to describe the state.
#
# The state is defined by:
#  * the state at the beginning of the interval, and
#  * the state's rate of change during the interval,
# in which the state contains the robot's posture and velocity.
#
# The initial state and its rate of change allow us to compute the
# state in a desired time.
#
# The order of the state is designed to be consistent with the URDF.
# Quaternions can be accommodated due to the different dimensions of
# the state and its rate of change.

# This represents the state at the beginning of the interval.
# This is broken into (position, rate).
# The first three of position are base position.
# The next four are the quaternion rotation of the base.
# The rate is (linear, angular)
float64[] x

# This represents the state's rate of change during the interval
float64[] dx}</pre>
*/
public class CrocoddylStateMessage implements ROS2Message<CrocoddylStateMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::CrocoddylStateMessage_";

   /**
      This represents the state at the beginning of the interval.
      This is broken into (position, rate).
      The first three of position are base position.
      The next four are the quaternion rotation of the base.
      The rate is (linear, angular)
   */
   private final IDLDoubleSequence x_;
   /**
      This represents the state's rate of change during the interval
   */
   private final IDLDoubleSequence dx_;

   public CrocoddylStateMessage()
   {
      x_ = new IDLDoubleSequence();
      dx_ = new IDLDoubleSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += x_.calculateSizeBytes(currentAlignment);
      currentAlignment += dx_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      x_.serialize(buffer);
      dx_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      x_.deserialize(buffer);
      dx_.deserialize(buffer);

   }

   @Override
   public void set(CrocoddylStateMessage from)
   {
      x_.set(from.x_);
      dx_.set(from.dx_);

   }

   public IDLDoubleSequence getX()
   {
      return x_;
   }

   public IDLDoubleSequence getDx()
   {
      return dx_;
   }


}