/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This is a message that holds data to describe the state and control trajectories.

The trajectory is defined by:
* the time interval,
* the state, and
* the control for each node.

The dimension of the intervals, state and control trajectories must be equal.
The header specifies the time at which the message is published.
<p>Source (controller_msgs/CrocoddylSolverTrajectoryMessage):
<pre>{@code
# This is a message that holds data to describe the state and control trajectories.
#
# The trajectory is defined by:
#  * the time interval,
#  * the state, and
#  * the control for each node.
#
# The dimension of the intervals, state and control trajectories must be equal.
# The header specifies the time at which the message is published.

# This represents the time and frame at which the message is published
std_msgs/Header header

# This represents the time and duration of each interval
CrocoddylTimeIntervalMessage[] intervals

# This represents the state for each interval
CrocoddylStateMessage[] state_trajectory

# This represents the control for each interval
CrocoddylControlMessage[] control_trajectory}</pre>
*/
public class CrocoddylSolverTrajectoryMessage implements ROS2Message<CrocoddylSolverTrajectoryMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::CrocoddylSolverTrajectoryMessage_";

   /**
      This represents the time and frame at which the message is published
   */
   private final std_msgs.msg.dds.Header header_;
   /**
      This represents the time and duration of each interval
   */
   private final IDLObjectSequence<controller_msgs.msg.dds.CrocoddylTimeIntervalMessage> intervals_;
   /**
      This represents the state for each interval
   */
   private final IDLObjectSequence<controller_msgs.msg.dds.CrocoddylStateMessage> state_trajectory_;
   /**
      This represents the control for each interval
   */
   private final IDLObjectSequence<controller_msgs.msg.dds.CrocoddylControlMessage> control_trajectory_;

   public CrocoddylSolverTrajectoryMessage()
   {
      header_ = new std_msgs.msg.dds.Header();
      intervals_ = new IDLObjectSequence<controller_msgs.msg.dds.CrocoddylTimeIntervalMessage>(controller_msgs.msg.dds.CrocoddylTimeIntervalMessage.class);
      state_trajectory_ = new IDLObjectSequence<controller_msgs.msg.dds.CrocoddylStateMessage>(controller_msgs.msg.dds.CrocoddylStateMessage.class);
      control_trajectory_ = new IDLObjectSequence<controller_msgs.msg.dds.CrocoddylControlMessage>(controller_msgs.msg.dds.CrocoddylControlMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += intervals_.calculateSizeBytes(currentAlignment);
      currentAlignment += state_trajectory_.calculateSizeBytes(currentAlignment);
      currentAlignment += control_trajectory_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      intervals_.serialize(buffer);
      state_trajectory_.serialize(buffer);
      control_trajectory_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      intervals_.deserialize(buffer);
      state_trajectory_.deserialize(buffer);
      control_trajectory_.deserialize(buffer);

   }

   @Override
   public void set(CrocoddylSolverTrajectoryMessage from)
   {
      header_.set(from.header_);
      intervals_.set(from.intervals_);
      state_trajectory_.set(from.state_trajectory_);
      control_trajectory_.set(from.control_trajectory_);

   }

   public std_msgs.msg.dds.Header getHeader()
   {
      return header_;
   }

   public IDLObjectSequence<controller_msgs.msg.dds.CrocoddylTimeIntervalMessage> getIntervals()
   {
      return intervals_;
   }

   public IDLObjectSequence<controller_msgs.msg.dds.CrocoddylStateMessage> getStateTrajectory()
   {
      return state_trajectory_;
   }

   public IDLObjectSequence<controller_msgs.msg.dds.CrocoddylControlMessage> getControlTrajectory()
   {
      return control_trajectory_;
   }


}