/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This is a message that holds time interval details.

The time interval is defined by:
* the time at the beginning of the interval, and
* the duration of the interval.

The time interval information allow us to compute the beginning of
the reference state and control.
<p>Source (controller_msgs/CrocoddylTimeIntervalMessage):
<pre>{@code
# This is a message that holds time interval details.
#
# The time interval is defined by:
#  * the time at the beginning of the interval, and
#  * the duration of the interval.
#
# The time interval information allow us to compute the beginning of
# the reference state and control.

# This represents the time at the beginning of the interval
float64 time

# This represents the duration of the interval
float64 duration}</pre>
*/
public class CrocoddylTimeIntervalMessage implements ROS2Message<CrocoddylTimeIntervalMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::CrocoddylTimeIntervalMessage_";

   /**
      This represents the time at the beginning of the interval
   */
   private double time_;
   /**
      This represents the duration of the interval
   */
   private double duration_;

   public CrocoddylTimeIntervalMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // time_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // duration_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(time_);
      buffer.writeDouble(duration_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      time_ = buffer.readDouble();
      duration_ = buffer.readDouble();

   }

   @Override
   public void set(CrocoddylTimeIntervalMessage from)
   {
      time_ = from.time_;
      duration_ = from.duration_;

   }

   public double getTime()
   {
      return time_;
   }

   public void setTime(double time_)
   {
      this.time_ = time_;
   }

   public double getDuration()
   {
      return duration_;
   }

   public void setDuration(double duration_)
   {
      this.duration_ = duration_;
   }


}