/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC whole-body controller API.
This message is old will be refreshed in a future release.
Message for commanding the hands to perform various predefined grasps.
<p>Source (controller_msgs/HandDesiredConfigurationMessage):
<pre>{@code
# This message is part of the IHMC whole-body controller API.
# This message is old will be refreshed in a future release.
# Message for commanding the hands to perform various predefined grasps.

byte ROBOT_SIDE_LEFT = 0
byte ROBOT_SIDE_RIGHT = 1

byte HAND_CONFIGURATION_STOP = 0
byte HAND_CONFIGURATION_OPEN = 1
byte HAND_CONFIGURATION_CLOSE = 2
byte HAND_CONFIGURATION_CRUSH = 3
byte HAND_CONFIGURATION_HOOK = 4
byte HAND_CONFIGURATION_BASIC_GRIP = 5
byte HAND_CONFIGURATION_PINCH_GRIP = 6
byte HAND_CONFIGURATION_WIDE_GRIP = 7
byte HAND_CONFIGURATION_SCISSOR_GRIP = 8
byte HAND_CONFIGURATION_RESET = 9
byte HAND_CONFIGURATION_OPEN_FINGERS = 10
byte HAND_CONFIGURATION_OPEN_THUMB = 11
byte HAND_CONFIGURATION_CLOSE_FINGERS = 12
byte HAND_CONFIGURATION_CLOSE_THUMB = 13
byte HAND_CONFIGURATION_OPEN_INDEX = 14
byte HAND_CONFIGURATION_OPEN_MIDDLE = 15
byte HAND_CONFIGURATION_HALF_CLOSE = 16
byte HAND_CONFIGURATION_CONNECT = 17
byte HAND_CONFIGURATION_CRUSH_INDEX = 18
byte HAND_CONFIGURATION_CRUSH_MIDDLE = 19
byte HAND_CONFIGURATION_CRUSH_THUMB = 20
byte HAND_CONFIGURATION_INVERT_POWER = 21
byte HAND_CONFIGURATION_T_SPREAD = 22
byte HAND_CONFIGURATION_BEND_BACKWARD = 23
byte HAND_CONFIGURATION_CALIBRATE = 24
byte HAND_CONFIGURATION_FINGER_MANIPULATION = 25
byte HAND_CONFIGURATION_PRE_CREEPY_GRASP = 26
byte HAND_CONFIGURATION_PARTIAL_CREEPY_GRASP = 27
byte HAND_CONFIGURATION_CREEPY_GRASPING = 28
byte HAND_CONFIGURATION_CREEPY_GRASPING_HARD = 29
byte HAND_CONFIGURATION_SLOW_CLOSE = 30

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Specifies the side of the robot that will execute the trajectory
byte robot_side 255
# Specifies the grasp to perform
byte desired_hand_configuration 255}</pre>
*/
public class HandDesiredConfigurationMessage implements ROS2Message<HandDesiredConfigurationMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::HandDesiredConfigurationMessage_";

   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   public static final byte HAND_CONFIGURATION_STOP = 0;
   public static final byte HAND_CONFIGURATION_OPEN = 1;
   public static final byte HAND_CONFIGURATION_CLOSE = 2;
   public static final byte HAND_CONFIGURATION_CRUSH = 3;
   public static final byte HAND_CONFIGURATION_HOOK = 4;
   public static final byte HAND_CONFIGURATION_BASIC_GRIP = 5;
   public static final byte HAND_CONFIGURATION_PINCH_GRIP = 6;
   public static final byte HAND_CONFIGURATION_WIDE_GRIP = 7;
   public static final byte HAND_CONFIGURATION_SCISSOR_GRIP = 8;
   public static final byte HAND_CONFIGURATION_RESET = 9;
   public static final byte HAND_CONFIGURATION_OPEN_FINGERS = 10;
   public static final byte HAND_CONFIGURATION_OPEN_THUMB = 11;
   public static final byte HAND_CONFIGURATION_CLOSE_FINGERS = 12;
   public static final byte HAND_CONFIGURATION_CLOSE_THUMB = 13;
   public static final byte HAND_CONFIGURATION_OPEN_INDEX = 14;
   public static final byte HAND_CONFIGURATION_OPEN_MIDDLE = 15;
   public static final byte HAND_CONFIGURATION_HALF_CLOSE = 16;
   public static final byte HAND_CONFIGURATION_CONNECT = 17;
   public static final byte HAND_CONFIGURATION_CRUSH_INDEX = 18;
   public static final byte HAND_CONFIGURATION_CRUSH_MIDDLE = 19;
   public static final byte HAND_CONFIGURATION_CRUSH_THUMB = 20;
   public static final byte HAND_CONFIGURATION_INVERT_POWER = 21;
   public static final byte HAND_CONFIGURATION_T_SPREAD = 22;
   public static final byte HAND_CONFIGURATION_BEND_BACKWARD = 23;
   public static final byte HAND_CONFIGURATION_CALIBRATE = 24;
   public static final byte HAND_CONFIGURATION_FINGER_MANIPULATION = 25;
   public static final byte HAND_CONFIGURATION_PRE_CREEPY_GRASP = 26;
   public static final byte HAND_CONFIGURATION_PARTIAL_CREEPY_GRASP = 27;
   public static final byte HAND_CONFIGURATION_CREEPY_GRASPING = 28;
   public static final byte HAND_CONFIGURATION_CREEPY_GRASPING_HARD = 29;
   public static final byte HAND_CONFIGURATION_SLOW_CLOSE = 30;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Specifies the side of the robot that will execute the trajectory
   */
   private byte robot_side_;
   /**
      Specifies the grasp to perform
   */
   private byte desired_hand_configuration_;

   public HandDesiredConfigurationMessage()
   {
      robot_side_ = (byte) 255;
      desired_hand_configuration_ = (byte) 255;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // desired_hand_configuration_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(robot_side_);
      buffer.writeByte(desired_hand_configuration_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      robot_side_ = buffer.readByte();
      desired_hand_configuration_ = buffer.readByte();

   }

   @Override
   public void set(HandDesiredConfigurationMessage from)
   {
      sequence_id_ = from.sequence_id_;
      robot_side_ = from.robot_side_;
      desired_hand_configuration_ = from.desired_hand_configuration_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }

   public byte getDesiredHandConfiguration()
   {
      return desired_hand_configuration_;
   }

   public void setDesiredHandConfiguration(byte desired_hand_configuration_)
   {
      this.desired_hand_configuration_ = desired_hand_configuration_;
   }


}