/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Atlas specific message.
This packet controls the stiffness of LegJoints. i.e., the maximum force a joint puts out when it
is (pushed) away from a desired position. This is useful to prevent robot from falling when leg
hit things unexpectedly. However, low stiffness (high compliance) can lead to poor joint tracking
in the presence of natural joint stiction. Finding a good balance is application specific. In our
hybrid velocity+force controller, most force comes from velocity control, therefore, only
parameter related to velocity control is exposed.
<p>Source (controller_msgs/LegCompliancePacket):
<pre>{@code
# Atlas specific message.
# This packet controls the stiffness of LegJoints. i.e., the maximum force a joint puts out when it
# is (pushed) away from a desired position. This is useful to prevent robot from falling when leg
# hit things unexpectedly. However, low stiffness (high compliance) can lead to poor joint tracking
# in the presence of natural joint stiction. Finding a good balance is application specific. In our
# hybrid velocity+force controller, most force comes from velocity control, therefore, only
# parameter related to velocity control is exposed.

byte ROBOT_SIDE_LEFT = 0
byte ROBOT_SIDE_RIGHT = 1

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# maximum allowed force (ratio) from velocity control in the range of [0.0, 1.0]. 1.0 is the
# maximum stiffness (default) value tuned for fast walking, 0.0 refers to zero velocity control
# making the joint very compliant (only force control) but often bad tracking. On Atlas, 0.1-0.3
# gives decent tracking for slow motion and yet still compliant. The numbers in the array
# correspond to joints HPZ, HPX, HPY, KNY, AKY, AKX, respectively.
float32[] max_velocity_deltas

byte robot_side 255}</pre>
*/
public class LegCompliancePacket implements ROS2Message<LegCompliancePacket>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::LegCompliancePacket_";

   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      maximum allowed force (ratio) from velocity control in the range of [0.0, 1.0]. 1.0 is the
      maximum stiffness (default) value tuned for fast walking, 0.0 refers to zero velocity control
      making the joint very compliant (only force control) but often bad tracking. On Atlas, 0.1-0.3
      gives decent tracking for slow motion and yet still compliant. The numbers in the array
      correspond to joints HPZ, HPX, HPY, KNY, AKY, AKX, respectively.
   */
   private final IDLFloatSequence max_velocity_deltas_;
   private byte robot_side_;

   public LegCompliancePacket()
   {
      max_velocity_deltas_ = new IDLFloatSequence();
      robot_side_ = (byte) 255;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += max_velocity_deltas_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      max_velocity_deltas_.serialize(buffer);
      buffer.writeByte(robot_side_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      max_velocity_deltas_.deserialize(buffer);
      robot_side_ = buffer.readByte();

   }

   @Override
   public void set(LegCompliancePacket from)
   {
      sequence_id_ = from.sequence_id_;
      max_velocity_deltas_.set(from.max_velocity_deltas_);
      robot_side_ = from.robot_side_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLFloatSequence getMaxVelocityDeltas()
   {
      return max_velocity_deltas_;
   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }


}