/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Message part of the localization module
<p>Source (controller_msgs/LocalizationStatusPacket):
<pre>{@code
# Message part of the localization module

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

float64 overlap
string status}</pre>
*/
public class LocalizationStatusPacket implements ROS2Message<LocalizationStatusPacket>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::LocalizationStatusPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private double overlap_;
   private final StringBuilder status_;

   public LocalizationStatusPacket()
   {
      status_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // overlap_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * status_.length()) + 1; // status_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeDouble(overlap_);
      buffer.writeString(status_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      overlap_ = buffer.readDouble();
      buffer.readString(status_);

   }

   @Override
   public void set(LocalizationStatusPacket from)
   {
      sequence_id_ = from.sequence_id_;
      overlap_ = from.overlap_;
      status_.delete(0, status_.length());
      status_.insert(0, from.status_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public double getOverlap()
   {
      return overlap_;
   }

   public void setOverlap(double overlap_)
   {
      this.overlap_ = overlap_;
   }

   public StringBuilder getStatus()
   {
      return status_;
   }


}