/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC whole-body controller API.
This message can be used to send a predefined angular momentum trajectory to the controller.
This trajectory will be used for ICP planning.
<p>Source (controller_msgs/MomentumTrajectoryMessage):
<pre>{@code
# This message is part of the IHMC whole-body controller API.
# This message can be used to send a predefined angular momentum trajectory to the controller.
# This trajectory will be used for ICP planning.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# List of angular momentum trajectory waypoints.
# Each waypoint contains the angular momentum and the angular momentum rate at a given time.
# NOTE: As the angular momentum can't be encoded using the SO3TrajectoryMessage, the EuclideanTrajectoryMessage is used. 
ihmc_common_msgs/EuclideanTrajectoryMessage angular_momentum_trajectory
}</pre>
*/
public class MomentumTrajectoryMessage implements ROS2Message<MomentumTrajectoryMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::MomentumTrajectoryMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      List of angular momentum trajectory waypoints.
      Each waypoint contains the angular momentum and the angular momentum rate at a given time.
      NOTE: As the angular momentum can't be encoded using the SO3TrajectoryMessage, the EuclideanTrajectoryMessage is used.
   */
   private final ihmc_common_msgs.msg.dds.EuclideanTrajectoryMessage angular_momentum_trajectory_;

   public MomentumTrajectoryMessage()
   {
      angular_momentum_trajectory_ = new ihmc_common_msgs.msg.dds.EuclideanTrajectoryMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += angular_momentum_trajectory_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      angular_momentum_trajectory_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      angular_momentum_trajectory_.deserialize(buffer);

   }

   @Override
   public void set(MomentumTrajectoryMessage from)
   {
      sequence_id_ = from.sequence_id_;
      angular_momentum_trajectory_.set(from.angular_momentum_trajectory_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public ihmc_common_msgs.msg.dds.EuclideanTrajectoryMessage getAngularMomentumTrajectory()
   {
      return angular_momentum_trajectory_;
   }


}