/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC multi-contact controller API.
Message for commanding whole-body jointspace trajectory as well as precomputed load status
<p>Source (controller_msgs/MultiContactTimedContactSequenceMessage):
<pre>{@code
# This message is part of the IHMC multi-contact controller API.
# Message for commanding whole-body jointspace trajectory as well as precomputed load status

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Timed intervals that left arm is in contact
ihmc_common_msgs/TimeIntervalMessage[<=25] left_arm_contact_intervals
# Timed intervals that right arm is in contact
ihmc_common_msgs/TimeIntervalMessage[<=25] right_arm_contact_intervals
# Timed intervals that left leg is in contact
ihmc_common_msgs/TimeIntervalMessage[<=25] left_leg_contact_intervals
# Timed intervals that right leg is in contact
ihmc_common_msgs/TimeIntervalMessage[<=25] right_leg_contact_intervals
}</pre>
*/
public class MultiContactTimedContactSequenceMessage implements ROS2Message<MultiContactTimedContactSequenceMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::MultiContactTimedContactSequenceMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Timed intervals that left arm is in contact
   */
   private final IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage> left_arm_contact_intervals_;
   /**
      Timed intervals that right arm is in contact
   */
   private final IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage> right_arm_contact_intervals_;
   /**
      Timed intervals that left leg is in contact
   */
   private final IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage> left_leg_contact_intervals_;
   /**
      Timed intervals that right leg is in contact
   */
   private final IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage> right_leg_contact_intervals_;

   public MultiContactTimedContactSequenceMessage()
   {
      left_arm_contact_intervals_ = new IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage>(25, ihmc_common_msgs.msg.dds.TimeIntervalMessage.class);
      right_arm_contact_intervals_ = new IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage>(25, ihmc_common_msgs.msg.dds.TimeIntervalMessage.class);
      left_leg_contact_intervals_ = new IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage>(25, ihmc_common_msgs.msg.dds.TimeIntervalMessage.class);
      right_leg_contact_intervals_ = new IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage>(25, ihmc_common_msgs.msg.dds.TimeIntervalMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += left_arm_contact_intervals_.calculateSizeBytes(currentAlignment);
      currentAlignment += right_arm_contact_intervals_.calculateSizeBytes(currentAlignment);
      currentAlignment += left_leg_contact_intervals_.calculateSizeBytes(currentAlignment);
      currentAlignment += right_leg_contact_intervals_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      left_arm_contact_intervals_.serialize(buffer);
      right_arm_contact_intervals_.serialize(buffer);
      left_leg_contact_intervals_.serialize(buffer);
      right_leg_contact_intervals_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      left_arm_contact_intervals_.deserialize(buffer);
      right_arm_contact_intervals_.deserialize(buffer);
      left_leg_contact_intervals_.deserialize(buffer);
      right_leg_contact_intervals_.deserialize(buffer);

   }

   @Override
   public void set(MultiContactTimedContactSequenceMessage from)
   {
      sequence_id_ = from.sequence_id_;
      left_arm_contact_intervals_.set(from.left_arm_contact_intervals_);
      right_arm_contact_intervals_.set(from.right_arm_contact_intervals_);
      left_leg_contact_intervals_.set(from.left_leg_contact_intervals_);
      right_leg_contact_intervals_.set(from.right_leg_contact_intervals_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage> getLeftArmContactIntervals()
   {
      return left_arm_contact_intervals_;
   }

   public IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage> getRightArmContactIntervals()
   {
      return right_arm_contact_intervals_;
   }

   public IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage> getLeftLegContactIntervals()
   {
      return left_leg_contact_intervals_;
   }

   public IDLObjectSequence<ihmc_common_msgs.msg.dds.TimeIntervalMessage> getRightLegContactIntervals()
   {
      return right_leg_contact_intervals_;
   }


}