/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC multi-contact controller API.
<p>Source (controller_msgs/MultiContactTrajectorySequenceMessage):
<pre>{@code
# This message is part of the IHMC multi-contact controller API.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Sequence of trajectories to be executed in succession
MultiContactTrajectoryMessage[<=50] trajectory_sequence}</pre>
*/
public class MultiContactTrajectorySequenceMessage implements ROS2Message<MultiContactTrajectorySequenceMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::MultiContactTrajectorySequenceMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Sequence of trajectories to be executed in succession
   */
   private final IDLObjectSequence<controller_msgs.msg.dds.MultiContactTrajectoryMessage> trajectory_sequence_;

   public MultiContactTrajectorySequenceMessage()
   {
      trajectory_sequence_ = new IDLObjectSequence<controller_msgs.msg.dds.MultiContactTrajectoryMessage>(50, controller_msgs.msg.dds.MultiContactTrajectoryMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += trajectory_sequence_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      trajectory_sequence_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      trajectory_sequence_.deserialize(buffer);

   }

   @Override
   public void set(MultiContactTrajectorySequenceMessage from)
   {
      sequence_id_ = from.sequence_id_;
      trajectory_sequence_.set(from.trajectory_sequence_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLObjectSequence<controller_msgs.msg.dds.MultiContactTrajectoryMessage> getTrajectorySequence()
   {
      return trajectory_sequence_;
   }


}