/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part the IHMC humanoid behavior module.
<p>Source (controller_msgs/ObjectWeightPacket):
<pre>{@code
# This message is part the IHMC humanoid behavior module.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte ROBOT_SIDE_LEFT = 0
byte ROBOT_SIDE_RIGHT = 1

byte robot_side 255
float64 weight}</pre>
*/
public class ObjectWeightPacket implements ROS2Message<ObjectWeightPacket>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::ObjectWeightPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   private byte robot_side_;
   private double weight_;

   public ObjectWeightPacket()
   {
      robot_side_ = (byte) 255;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // weight_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(robot_side_);
      buffer.writeDouble(weight_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      robot_side_ = buffer.readByte();
      weight_ = buffer.readDouble();

   }

   @Override
   public void set(ObjectWeightPacket from)
   {
      sequence_id_ = from.sequence_id_;
      robot_side_ = from.robot_side_;
      weight_ = from.weight_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }

   public double getWeight()
   {
      return weight_;
   }

   public void setWeight(double weight_)
   {
      this.weight_ = weight_;
   }


}