/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of IHMC Simulation Construction Set.
Notifies the user when the simulation has stopped.
<p>Source (controller_msgs/SCSListenerPacket):
<pre>{@code
# This message is part of IHMC Simulation Construction Set.
# Notifies the user when the simulation has stopped.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

bool is_stopped true}</pre>
*/
public class SCSListenerPacket implements ROS2Message<SCSListenerPacket>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::SCSListenerPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private boolean is_stopped_;

   public SCSListenerPacket()
   {
      is_stopped_ = (boolean) true;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_stopped_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(is_stopped_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      is_stopped_ = buffer.readBoolean();

   }

   @Override
   public void set(SCSListenerPacket from)
   {
      sequence_id_ = from.sequence_id_;
      is_stopped_ = from.is_stopped_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getIsStopped()
   {
      return is_stopped_;
   }

   public void setIsStopped(boolean is_stopped_)
   {
      this.is_stopped_ = is_stopped_;
   }


}