/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Old message, needs to be tested and cleaned up.
<p>Source (controller_msgs/SnapFootstepPacket):
<pre>{@code
# Old message, needs to be tested and cleaned up.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

FootstepDataMessage[] footstep_data
int32[] footstep_order
byte[] flag

}</pre>
*/
public class SnapFootstepPacket implements ROS2Message<SnapFootstepPacket>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::SnapFootstepPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final IDLObjectSequence<controller_msgs.msg.dds.FootstepDataMessage> footstep_data_;
   private final IDLIntSequence footstep_order_;
   private final IDLByteSequence flag_;

   public SnapFootstepPacket()
   {
      footstep_data_ = new IDLObjectSequence<controller_msgs.msg.dds.FootstepDataMessage>(controller_msgs.msg.dds.FootstepDataMessage.class);
      footstep_order_ = new IDLIntSequence();
      flag_ = new IDLByteSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += footstep_data_.calculateSizeBytes(currentAlignment);
      currentAlignment += footstep_order_.calculateSizeBytes(currentAlignment);
      currentAlignment += flag_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      footstep_data_.serialize(buffer);
      footstep_order_.serialize(buffer);
      flag_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      footstep_data_.deserialize(buffer);
      footstep_order_.deserialize(buffer);
      flag_.deserialize(buffer);

   }

   @Override
   public void set(SnapFootstepPacket from)
   {
      sequence_id_ = from.sequence_id_;
      footstep_data_.set(from.footstep_data_);
      footstep_order_.set(from.footstep_order_);
      flag_.set(from.flag_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLObjectSequence<controller_msgs.msg.dds.FootstepDataMessage> getFootstepData()
   {
      return footstep_data_;
   }

   public IDLIntSequence getFootstepOrder()
   {
      return footstep_order_;
   }

   public IDLByteSequence getFlag()
   {
      return flag_;
   }


}