/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
TODO: This message is not really used, the feature it provides needs to be fixed or this message needs to be deleted.
<p>Source (controller_msgs/UIConnectedPacket):
<pre>{@code
# TODO: This message is not really used, the feature it provides needs to be fixed or this message needs to be deleted.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id}</pre>
*/
public class UIConnectedPacket implements ROS2Message<UIConnectedPacket>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::UIConnectedPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;

   public UIConnectedPacket()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();

   }

   @Override
   public void set(UIConnectedPacket from)
   {
      sequence_id_ = from.sequence_id_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }


}