/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (controller_msgs/UIPositionCheckerPacket):
<pre>{@code

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

geometry_msgs/Point position
geometry_msgs/Quaternion orientation}</pre>
*/
public class UIPositionCheckerPacket implements ROS2Message<UIPositionCheckerPacket>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::UIPositionCheckerPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final geometry_msgs.msg.dds.Point position_;
   private final geometry_msgs.msg.dds.Quaternion orientation_;

   public UIPositionCheckerPacket()
   {
      position_ = new geometry_msgs.msg.dds.Point();
      orientation_ = new geometry_msgs.msg.dds.Quaternion();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += position_.calculateSizeBytes(currentAlignment);
      currentAlignment += orientation_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      position_.serialize(buffer);
      orientation_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      position_.deserialize(buffer);
      orientation_.deserialize(buffer);

   }

   @Override
   public void set(UIPositionCheckerPacket from)
   {
      sequence_id_ = from.sequence_id_;
      position_.set(from.position_);
      orientation_.set(from.orientation_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public geometry_msgs.msg.dds.Point getPosition()
   {
      return position_;
   }

   public geometry_msgs.msg.dds.Quaternion getOrientation()
   {
      return orientation_;
   }


}