/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package atlas_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Atlas specific message.
<p>Source (atlas_msgs/AtlasElectricMotorAutoEnableFlagPacket):
<pre>{@code
# Atlas specific message.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

bool should_auto_enable}</pre>
*/
public class AtlasElectricMotorAutoEnableFlagPacket implements ROS2Message<AtlasElectricMotorAutoEnableFlagPacket>
{
   public static final java.lang.String name = "atlas_msgs::msg::dds_::AtlasElectricMotorAutoEnableFlagPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private boolean should_auto_enable_;

   public AtlasElectricMotorAutoEnableFlagPacket()
   {
      should_auto_enable_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // should_auto_enable_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(should_auto_enable_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      should_auto_enable_ = buffer.readBoolean();

   }

   @Override
   public void set(AtlasElectricMotorAutoEnableFlagPacket from)
   {
      sequence_id_ = from.sequence_id_;
      should_auto_enable_ = from.should_auto_enable_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getShouldAutoEnable()
   {
      return should_auto_enable_;
   }

   public void setShouldAutoEnable(boolean should_auto_enable_)
   {
      this.should_auto_enable_ = should_auto_enable_;
   }


}