/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package atlas_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Atlas specific message.
<p>Source (atlas_msgs/AtlasLowLevelControlModeMessage):
<pre>{@code
# Atlas specific message.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte ATLAS_LOW_LEVEL_CONTROL_MODE_STAND_PREP = 0
byte ATLAS_LOW_LEVEL_CONTROL_MODE_FREEZE = 1

byte requested_atlas_low_level_control_mode 255}</pre>
*/
public class AtlasLowLevelControlModeMessage implements ROS2Message<AtlasLowLevelControlModeMessage>
{
   public static final java.lang.String name = "atlas_msgs::msg::dds_::AtlasLowLevelControlModeMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   public static final byte ATLAS_LOW_LEVEL_CONTROL_MODE_STAND_PREP = 0;
   public static final byte ATLAS_LOW_LEVEL_CONTROL_MODE_FREEZE = 1;
   private byte requested_atlas_low_level_control_mode_;

   public AtlasLowLevelControlModeMessage()
   {
      requested_atlas_low_level_control_mode_ = (byte) 255;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // requested_atlas_low_level_control_mode_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(requested_atlas_low_level_control_mode_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      requested_atlas_low_level_control_mode_ = buffer.readByte();

   }

   @Override
   public void set(AtlasLowLevelControlModeMessage from)
   {
      sequence_id_ = from.sequence_id_;
      requested_atlas_low_level_control_mode_ = from.requested_atlas_low_level_control_mode_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getRequestedAtlasLowLevelControlMode()
   {
      return requested_atlas_low_level_control_mode_;
   }

   public void setRequestedAtlasLowLevelControlMode(byte requested_atlas_low_level_control_mode_)
   {
      this.requested_atlas_low_level_control_mode_ = requested_atlas_low_level_control_mode_;
   }


}