/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package atlas_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Atlas specific message.
<p>Source (atlas_msgs/BDIBehaviorStatusPacket):
<pre>{@code
# Atlas specific message.

byte NONE = 0
byte FREEZE = 1
byte STAND_PREP = 2
byte STAND = 3
byte WALK = 4
byte STEP = 5
byte MANIPULATE = 6
byte USER = 7
byte CALIBRATE = 8
byte SOFT_STOP = 9

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte current_bdi_robot_behavior 255}</pre>
*/
public class BDIBehaviorStatusPacket implements ROS2Message<BDIBehaviorStatusPacket>
{
   public static final java.lang.String name = "atlas_msgs::msg::dds_::BDIBehaviorStatusPacket_";

   public static final byte NONE = 0;
   public static final byte FREEZE = 1;
   public static final byte STAND_PREP = 2;
   public static final byte STAND = 3;
   public static final byte WALK = 4;
   public static final byte STEP = 5;
   public static final byte MANIPULATE = 6;
   public static final byte USER = 7;
   public static final byte CALIBRATE = 8;
   public static final byte SOFT_STOP = 9;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private byte current_bdi_robot_behavior_;

   public BDIBehaviorStatusPacket()
   {
      current_bdi_robot_behavior_ = (byte) 255;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // current_bdi_robot_behavior_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(current_bdi_robot_behavior_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      current_bdi_robot_behavior_ = buffer.readByte();

   }

   @Override
   public void set(BDIBehaviorStatusPacket from)
   {
      sequence_id_ = from.sequence_id_;
      current_bdi_robot_behavior_ = from.current_bdi_robot_behavior_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getCurrentBdiRobotBehavior()
   {
      return current_bdi_robot_behavior_;
   }

   public void setCurrentBdiRobotBehavior(byte current_bdi_robot_behavior_)
   {
      this.current_bdi_robot_behavior_ = current_bdi_robot_behavior_;
   }


}