/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package atlas_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Atlas specific message.
<p>Source (atlas_msgs/BDIBehaviorCommandPacket):
<pre>{@code
# Atlas specific message.

byte NONE = 0
byte FREEZE = 1
byte STAND_PREP = 2
byte STAND = 3
byte WALK = 4
byte STEP = 5
byte MANIPULATE = 6
byte USER = 7
byte CALIBRATE = 8
byte SOFT_STOP = 9

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte atlas_bdi_robot_behavior 255
bool stop false}</pre>
*/
public class BDIBehaviorCommandPacket implements ROS2Message<BDIBehaviorCommandPacket>
{
   public static final java.lang.String name = "atlas_msgs::msg::dds_::BDIBehaviorCommandPacket_";

   public static final byte NONE = 0;
   public static final byte FREEZE = 1;
   public static final byte STAND_PREP = 2;
   public static final byte STAND = 3;
   public static final byte WALK = 4;
   public static final byte STEP = 5;
   public static final byte MANIPULATE = 6;
   public static final byte USER = 7;
   public static final byte CALIBRATE = 8;
   public static final byte SOFT_STOP = 9;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private byte atlas_bdi_robot_behavior_;
   private boolean stop_;

   public BDIBehaviorCommandPacket()
   {
      atlas_bdi_robot_behavior_ = (byte) 255;
      stop_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // atlas_bdi_robot_behavior_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // stop_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(atlas_bdi_robot_behavior_);
      buffer.writeBoolean(stop_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      atlas_bdi_robot_behavior_ = buffer.readByte();
      stop_ = buffer.readBoolean();

   }

   @Override
   public void set(BDIBehaviorCommandPacket from)
   {
      sequence_id_ = from.sequence_id_;
      atlas_bdi_robot_behavior_ = from.atlas_bdi_robot_behavior_;
      stop_ = from.stop_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getAtlasBdiRobotBehavior()
   {
      return atlas_bdi_robot_behavior_;
   }

   public void setAtlasBdiRobotBehavior(byte atlas_bdi_robot_behavior_)
   {
      this.atlas_bdi_robot_behavior_ = atlas_bdi_robot_behavior_;
   }

   public boolean getStop()
   {
      return stop_;
   }

   public void setStop(boolean stop_)
   {
      this.stop_ = stop_;
   }


}