/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
An perception scene node for an ArUco marker
The topic name identifies the node.
<p>Source (perception_msgs/ArUcoMarkerNodeMessage):
<pre>{@code
# An perception scene node for an ArUco marker
# The topic name identifies the node.

# The detectable scene node information
perception_msgs/DetectableSceneNodeMessage detectable_scene_node

# ArUco marker ID
uint16 marker_id

# ArUco marker size
float32 marker_size

# Break frequency filter value for nodes that are alpha filtered
float32 break_frequency}</pre>
*/
public class ArUcoMarkerNodeMessage implements ROS2Message<ArUcoMarkerNodeMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::ArUcoMarkerNodeMessage_";

   /**
      The detectable scene node information
   */
   private final perception_msgs.msg.dds.DetectableSceneNodeMessage detectable_scene_node_;
   /**
      ArUco marker ID
   */
   private short marker_id_;
   /**
      ArUco marker size
   */
   private float marker_size_;
   /**
      Break frequency filter value for nodes that are alpha filtered
   */
   private float break_frequency_;

   public ArUcoMarkerNodeMessage()
   {
      detectable_scene_node_ = new perception_msgs.msg.dds.DetectableSceneNodeMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += detectable_scene_node_.calculateSizeBytes(currentAlignment);
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // marker_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // marker_size_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // break_frequency_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      detectable_scene_node_.serialize(buffer);
      buffer.writeShort(marker_id_);
      buffer.writeFloat(marker_size_);
      buffer.writeFloat(break_frequency_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      detectable_scene_node_.deserialize(buffer);
      marker_id_ = buffer.readShort();
      marker_size_ = buffer.readFloat();
      break_frequency_ = buffer.readFloat();

   }

   @Override
   public void set(ArUcoMarkerNodeMessage from)
   {
      detectable_scene_node_.set(from.detectable_scene_node_);
      marker_id_ = from.marker_id_;
      marker_size_ = from.marker_size_;
      break_frequency_ = from.break_frequency_;

   }

   public perception_msgs.msg.dds.DetectableSceneNodeMessage getDetectableSceneNode()
   {
      return detectable_scene_node_;
   }

   public short getMarkerId()
   {
      return marker_id_;
   }

   public void setMarkerId(short marker_id_)
   {
      this.marker_id_ = marker_id_;
   }

   public float getMarkerSize()
   {
      return marker_size_;
   }

   public void setMarkerSize(float marker_size_)
   {
      this.marker_size_ = marker_size_;
   }

   public float getBreakFrequency()
   {
      return break_frequency_;
   }

   public void setBreakFrequency(float break_frequency_)
   {
      this.break_frequency_ = break_frequency_;
   }


}