/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/BallDetectionParametersMessage):
<pre>{@code
# Diameter of ball being detected, in meters
float64 ball_diameter

# Position alpha filter value
float64 alpha

# HSV lower bounds
float64 h_low
float64 s_low
float64 v_low

# HSV upper bounds
float64 h_high
float64 s_high
float64 v_high
}</pre>
*/
public class BallDetectionParametersMessage implements ROS2Message<BallDetectionParametersMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::BallDetectionParametersMessage_";

   /**
      Diameter of ball being detected, in meters
   */
   private double ball_diameter_;
   /**
      Position alpha filter value
   */
   private double alpha_;
   /**
      HSV lower bounds
   */
   private double h_low_;
   private double s_low_;
   private double v_low_;
   /**
      HSV upper bounds
   */
   private double h_high_;
   private double s_high_;
   private double v_high_;

   public BallDetectionParametersMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // ball_diameter_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // alpha_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // h_low_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // s_low_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // v_low_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // h_high_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // s_high_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // v_high_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(ball_diameter_);
      buffer.writeDouble(alpha_);
      buffer.writeDouble(h_low_);
      buffer.writeDouble(s_low_);
      buffer.writeDouble(v_low_);
      buffer.writeDouble(h_high_);
      buffer.writeDouble(s_high_);
      buffer.writeDouble(v_high_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      ball_diameter_ = buffer.readDouble();
      alpha_ = buffer.readDouble();
      h_low_ = buffer.readDouble();
      s_low_ = buffer.readDouble();
      v_low_ = buffer.readDouble();
      h_high_ = buffer.readDouble();
      s_high_ = buffer.readDouble();
      v_high_ = buffer.readDouble();

   }

   @Override
   public void set(BallDetectionParametersMessage from)
   {
      ball_diameter_ = from.ball_diameter_;
      alpha_ = from.alpha_;
      h_low_ = from.h_low_;
      s_low_ = from.s_low_;
      v_low_ = from.v_low_;
      h_high_ = from.h_high_;
      s_high_ = from.s_high_;
      v_high_ = from.v_high_;

   }

   public double getBallDiameter()
   {
      return ball_diameter_;
   }

   public void setBallDiameter(double ball_diameter_)
   {
      this.ball_diameter_ = ball_diameter_;
   }

   public double getAlpha()
   {
      return alpha_;
   }

   public void setAlpha(double alpha_)
   {
      this.alpha_ = alpha_;
   }

   public double getHLow()
   {
      return h_low_;
   }

   public void setHLow(double h_low_)
   {
      this.h_low_ = h_low_;
   }

   public double getSLow()
   {
      return s_low_;
   }

   public void setSLow(double s_low_)
   {
      this.s_low_ = s_low_;
   }

   public double getVLow()
   {
      return v_low_;
   }

   public void setVLow(double v_low_)
   {
      this.v_low_ = v_low_;
   }

   public double getHHigh()
   {
      return h_high_;
   }

   public void setHHigh(double h_high_)
   {
      this.h_high_ = h_high_;
   }

   public double getSHigh()
   {
      return s_high_;
   }

   public void setSHigh(double s_high_)
   {
      this.s_high_ = s_high_;
   }

   public double getVHigh()
   {
      return v_high_;
   }

   public void setVHigh(double v_high_)
   {
      this.v_high_ = v_high_;
   }


}