/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Atlas specific message
<p>Source (perception_msgs/BlackFlyParameterPacket):
<pre>{@code
# Atlas specific message

byte ROBOT_SIDE_LEFT = 0
byte ROBOT_SIDE_RIGHT = 1

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

bool auto_exposure
bool auto_gain
bool auto_shutter
float64 exposure
float64 frame_rate
bool from_ui
float64 gain
float64 shutter
byte robot_side 255}</pre>
*/
public class BlackFlyParameterPacket implements ROS2Message<BlackFlyParameterPacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::BlackFlyParameterPacket_";

   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private boolean auto_exposure_;
   private boolean auto_gain_;
   private boolean auto_shutter_;
   private double exposure_;
   private double frame_rate_;
   private boolean from_ui_;
   private double gain_;
   private double shutter_;
   private byte robot_side_;

   public BlackFlyParameterPacket()
   {
      auto_exposure_ = (boolean) false;
      auto_gain_ = (boolean) false;
      auto_shutter_ = (boolean) false;
      from_ui_ = (boolean) false;
      robot_side_ = (byte) 255;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // auto_exposure_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // auto_gain_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // auto_shutter_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // exposure_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // frame_rate_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // from_ui_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // gain_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // shutter_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(auto_exposure_);
      buffer.writeBoolean(auto_gain_);
      buffer.writeBoolean(auto_shutter_);
      buffer.writeDouble(exposure_);
      buffer.writeDouble(frame_rate_);
      buffer.writeBoolean(from_ui_);
      buffer.writeDouble(gain_);
      buffer.writeDouble(shutter_);
      buffer.writeByte(robot_side_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      auto_exposure_ = buffer.readBoolean();
      auto_gain_ = buffer.readBoolean();
      auto_shutter_ = buffer.readBoolean();
      exposure_ = buffer.readDouble();
      frame_rate_ = buffer.readDouble();
      from_ui_ = buffer.readBoolean();
      gain_ = buffer.readDouble();
      shutter_ = buffer.readDouble();
      robot_side_ = buffer.readByte();

   }

   @Override
   public void set(BlackFlyParameterPacket from)
   {
      sequence_id_ = from.sequence_id_;
      auto_exposure_ = from.auto_exposure_;
      auto_gain_ = from.auto_gain_;
      auto_shutter_ = from.auto_shutter_;
      exposure_ = from.exposure_;
      frame_rate_ = from.frame_rate_;
      from_ui_ = from.from_ui_;
      gain_ = from.gain_;
      shutter_ = from.shutter_;
      robot_side_ = from.robot_side_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getAutoExposure()
   {
      return auto_exposure_;
   }

   public void setAutoExposure(boolean auto_exposure_)
   {
      this.auto_exposure_ = auto_exposure_;
   }

   public boolean getAutoGain()
   {
      return auto_gain_;
   }

   public void setAutoGain(boolean auto_gain_)
   {
      this.auto_gain_ = auto_gain_;
   }

   public boolean getAutoShutter()
   {
      return auto_shutter_;
   }

   public void setAutoShutter(boolean auto_shutter_)
   {
      this.auto_shutter_ = auto_shutter_;
   }

   public double getExposure()
   {
      return exposure_;
   }

   public void setExposure(double exposure_)
   {
      this.exposure_ = exposure_;
   }

   public double getFrameRate()
   {
      return frame_rate_;
   }

   public void setFrameRate(double frame_rate_)
   {
      this.frame_rate_ = frame_rate_;
   }

   public boolean getFromUi()
   {
      return from_ui_;
   }

   public void setFromUi(boolean from_ui_)
   {
      this.from_ui_ = from_ui_;
   }

   public double getGain()
   {
      return gain_;
   }

   public void setGain(double gain_)
   {
      this.gain_ = gain_;
   }

   public double getShutter()
   {
      return shutter_;
   }

   public void setShutter(double shutter_)
   {
      this.shutter_ = shutter_;
   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }


}