/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/ChunkMessage):
<pre>{@code
# We have a hash to keep each chunk unique
int32 hash_code_of_chunk

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# X coordinate of the center of the height map
float64 origin_x 0.0

# Y coordinate of the center of the height map
float64 origin_y 0.0

# Width of the height map in meters
float64 width_in_meters

# Cell size in meters of an individual cell
float64 cell_size_in_meters

# Cells per axis
int32 cells_per_axis

# List of heights, which correspond to the list of keys
float32[<=5000] heights
}</pre>
*/
public class ChunkMessage implements ROS2Message<ChunkMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::ChunkMessage_";

   /**
      We have a hash to keep each chunk unique
   */
   private int hash_code_of_chunk_;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      X coordinate of the center of the height map
   */
   private double origin_x_;
   /**
      Y coordinate of the center of the height map
   */
   private double origin_y_;
   /**
      Width of the height map in meters
   */
   private double width_in_meters_;
   /**
      Cell size in meters of an individual cell
   */
   private double cell_size_in_meters_;
   /**
      Cells per axis
   */
   private int cells_per_axis_;
   /**
      List of heights, which correspond to the list of keys
   */
   private final IDLFloatSequence heights_;

   public ChunkMessage()
   {
      origin_x_ = (double) 0.0;
      origin_y_ = (double) 0.0;
      heights_ = new IDLFloatSequence(5000);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // hash_code_of_chunk_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // origin_x_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // origin_y_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // width_in_meters_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // cell_size_in_meters_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // cells_per_axis_
      currentAlignment += heights_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(hash_code_of_chunk_);
      buffer.writeLong(sequence_id_);
      buffer.writeDouble(origin_x_);
      buffer.writeDouble(origin_y_);
      buffer.writeDouble(width_in_meters_);
      buffer.writeDouble(cell_size_in_meters_);
      buffer.writeInt(cells_per_axis_);
      heights_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      hash_code_of_chunk_ = buffer.readInt();
      sequence_id_ = buffer.readLong();
      origin_x_ = buffer.readDouble();
      origin_y_ = buffer.readDouble();
      width_in_meters_ = buffer.readDouble();
      cell_size_in_meters_ = buffer.readDouble();
      cells_per_axis_ = buffer.readInt();
      heights_.deserialize(buffer);

   }

   @Override
   public void set(ChunkMessage from)
   {
      hash_code_of_chunk_ = from.hash_code_of_chunk_;
      sequence_id_ = from.sequence_id_;
      origin_x_ = from.origin_x_;
      origin_y_ = from.origin_y_;
      width_in_meters_ = from.width_in_meters_;
      cell_size_in_meters_ = from.cell_size_in_meters_;
      cells_per_axis_ = from.cells_per_axis_;
      heights_.set(from.heights_);

   }

   public int getHashCodeOfChunk()
   {
      return hash_code_of_chunk_;
   }

   public void setHashCodeOfChunk(int hash_code_of_chunk_)
   {
      this.hash_code_of_chunk_ = hash_code_of_chunk_;
   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public double getOriginX()
   {
      return origin_x_;
   }

   public void setOriginX(double origin_x_)
   {
      this.origin_x_ = origin_x_;
   }

   public double getOriginY()
   {
      return origin_y_;
   }

   public void setOriginY(double origin_y_)
   {
      this.origin_y_ = origin_y_;
   }

   public double getWidthInMeters()
   {
      return width_in_meters_;
   }

   public void setWidthInMeters(double width_in_meters_)
   {
      this.width_in_meters_ = width_in_meters_;
   }

   public double getCellSizeInMeters()
   {
      return cell_size_in_meters_;
   }

   public void setCellSizeInMeters(double cell_size_in_meters_)
   {
      this.cell_size_in_meters_ = cell_size_in_meters_;
   }

   public int getCellsPerAxis()
   {
      return cells_per_axis_;
   }

   public void setCellsPerAxis(int cells_per_axis_)
   {
      this.cells_per_axis_ = cells_per_axis_;
   }

   public IDLFloatSequence getHeights()
   {
      return heights_;
   }


}