/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Message representing a DetectedDoor
<p>Source (perception_msgs/DetectedDoorMessage):
<pre>{@code
# Message representing a DetectedDoor

# UUID of this detection
ihmc_common_msgs/UUIDMessage detection_uuid

# The opening mechanism
perception_msgs/DetectedDoorOpeningMechanismMessage opening_mechanism

# Panel pose
# May contain NaN in the position and/or orientation values if unknown.
controller_msgs/RigidBodyTransformMessage panel_transform_to_world

# Planar region of the panel
perception_msgs/PlanarRegionMessage panel_planar_region

# Last detection instant
ihmc_common_msgs/InstantMessage last_detection_time

# Internal statistics
ihmc_common_msgs/InstantMessage opening_mechanism_first_detection_time
int32 opening_mechanism_detection_count
ihmc_common_msgs/InstantMessage panel_first_detection_time
int32 panel_detection_count}</pre>
*/
public class DetectedDoorMessage implements ROS2Message<DetectedDoorMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::DetectedDoorMessage_";

   /**
      UUID of this detection
   */
   private final ihmc_common_msgs.msg.dds.UUIDMessage detection_uuid_;
   /**
      The opening mechanism
   */
   private final perception_msgs.msg.dds.DetectedDoorOpeningMechanismMessage opening_mechanism_;
   /**
      Panel pose
      May contain NaN in the position and/or orientation values if unknown.
   */
   private final controller_msgs.msg.dds.RigidBodyTransformMessage panel_transform_to_world_;
   /**
      Planar region of the panel
   */
   private final perception_msgs.msg.dds.PlanarRegionMessage panel_planar_region_;
   /**
      Last detection instant
   */
   private final ihmc_common_msgs.msg.dds.InstantMessage last_detection_time_;
   /**
      Internal statistics
   */
   private final ihmc_common_msgs.msg.dds.InstantMessage opening_mechanism_first_detection_time_;
   private int opening_mechanism_detection_count_;
   private final ihmc_common_msgs.msg.dds.InstantMessage panel_first_detection_time_;
   private int panel_detection_count_;

   public DetectedDoorMessage()
   {
      detection_uuid_ = new ihmc_common_msgs.msg.dds.UUIDMessage();
      opening_mechanism_ = new perception_msgs.msg.dds.DetectedDoorOpeningMechanismMessage();
      panel_transform_to_world_ = new controller_msgs.msg.dds.RigidBodyTransformMessage();
      panel_planar_region_ = new perception_msgs.msg.dds.PlanarRegionMessage();
      last_detection_time_ = new ihmc_common_msgs.msg.dds.InstantMessage();
      opening_mechanism_first_detection_time_ = new ihmc_common_msgs.msg.dds.InstantMessage();
      panel_first_detection_time_ = new ihmc_common_msgs.msg.dds.InstantMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += detection_uuid_.calculateSizeBytes(currentAlignment);
      currentAlignment += opening_mechanism_.calculateSizeBytes(currentAlignment);
      currentAlignment += panel_transform_to_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += panel_planar_region_.calculateSizeBytes(currentAlignment);
      currentAlignment += last_detection_time_.calculateSizeBytes(currentAlignment);
      currentAlignment += opening_mechanism_first_detection_time_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // opening_mechanism_detection_count_
      currentAlignment += panel_first_detection_time_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // panel_detection_count_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      detection_uuid_.serialize(buffer);
      opening_mechanism_.serialize(buffer);
      panel_transform_to_world_.serialize(buffer);
      panel_planar_region_.serialize(buffer);
      last_detection_time_.serialize(buffer);
      opening_mechanism_first_detection_time_.serialize(buffer);
      buffer.writeInt(opening_mechanism_detection_count_);
      panel_first_detection_time_.serialize(buffer);
      buffer.writeInt(panel_detection_count_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      detection_uuid_.deserialize(buffer);
      opening_mechanism_.deserialize(buffer);
      panel_transform_to_world_.deserialize(buffer);
      panel_planar_region_.deserialize(buffer);
      last_detection_time_.deserialize(buffer);
      opening_mechanism_first_detection_time_.deserialize(buffer);
      opening_mechanism_detection_count_ = buffer.readInt();
      panel_first_detection_time_.deserialize(buffer);
      panel_detection_count_ = buffer.readInt();

   }

   @Override
   public void set(DetectedDoorMessage from)
   {
      detection_uuid_.set(from.detection_uuid_);
      opening_mechanism_.set(from.opening_mechanism_);
      panel_transform_to_world_.set(from.panel_transform_to_world_);
      panel_planar_region_.set(from.panel_planar_region_);
      last_detection_time_.set(from.last_detection_time_);
      opening_mechanism_first_detection_time_.set(from.opening_mechanism_first_detection_time_);
      opening_mechanism_detection_count_ = from.opening_mechanism_detection_count_;
      panel_first_detection_time_.set(from.panel_first_detection_time_);
      panel_detection_count_ = from.panel_detection_count_;

   }

   public ihmc_common_msgs.msg.dds.UUIDMessage getDetectionUuid()
   {
      return detection_uuid_;
   }

   public perception_msgs.msg.dds.DetectedDoorOpeningMechanismMessage getOpeningMechanism()
   {
      return opening_mechanism_;
   }

   public controller_msgs.msg.dds.RigidBodyTransformMessage getPanelTransformToWorld()
   {
      return panel_transform_to_world_;
   }

   public perception_msgs.msg.dds.PlanarRegionMessage getPanelPlanarRegion()
   {
      return panel_planar_region_;
   }

   public ihmc_common_msgs.msg.dds.InstantMessage getLastDetectionTime()
   {
      return last_detection_time_;
   }

   public ihmc_common_msgs.msg.dds.InstantMessage getOpeningMechanismFirstDetectionTime()
   {
      return opening_mechanism_first_detection_time_;
   }

   public int getOpeningMechanismDetectionCount()
   {
      return opening_mechanism_detection_count_;
   }

   public void setOpeningMechanismDetectionCount(int opening_mechanism_detection_count_)
   {
      this.opening_mechanism_detection_count_ = opening_mechanism_detection_count_;
   }

   public ihmc_common_msgs.msg.dds.InstantMessage getPanelFirstDetectionTime()
   {
      return panel_first_detection_time_;
   }

   public int getPanelDetectionCount()
   {
      return panel_detection_count_;
   }

   public void setPanelDetectionCount(int panel_detection_count_)
   {
      this.panel_detection_count_ = panel_detection_count_;
   }


}