/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Message representing the DoorOpeningMechanism
<p>Source (perception_msgs/DetectedDoorOpeningMechanismMessage):
<pre>{@code
# Message representing the DoorOpeningMechanism

string name

# Ordinal of DoorSide
byte side

# Pose of the opening mechanism.
# May contain NaN in the position and/or orientation values if unknown.
controller_msgs/RigidBodyTransformMessage transform_to_world
}</pre>
*/
public class DetectedDoorOpeningMechanismMessage implements ROS2Message<DetectedDoorOpeningMechanismMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::DetectedDoorOpeningMechanismMessage_";

   private final StringBuilder name_;
   /**
      Ordinal of DoorSide
   */
   private byte side_;
   /**
      Pose of the opening mechanism.
      May contain NaN in the position and/or orientation values if unknown.
   */
   private final controller_msgs.msg.dds.RigidBodyTransformMessage transform_to_world_;

   public DetectedDoorOpeningMechanismMessage()
   {
      name_ = new StringBuilder();
      transform_to_world_ = new controller_msgs.msg.dds.RigidBodyTransformMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // side_
      currentAlignment += transform_to_world_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(name_);
      buffer.writeByte(side_);
      transform_to_world_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(name_);
      side_ = buffer.readByte();
      transform_to_world_.deserialize(buffer);

   }

   @Override
   public void set(DetectedDoorOpeningMechanismMessage from)
   {
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      side_ = from.side_;
      transform_to_world_.set(from.transform_to_world_);

   }

   public StringBuilder getName()
   {
      return name_;
   }

   public byte getSide()
   {
      return side_;
   }

   public void setSide(byte side_)
   {
      this.side_ = side_;
   }

   public controller_msgs.msg.dds.RigidBodyTransformMessage getTransformToWorld()
   {
      return transform_to_world_;
   }


}