/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/DoorNodeMessage):
<pre>{@code
# The base scene node information
perception_msgs/DetectableSceneNodeMessage detectable_scene_node

# The transform of the frame of the door corner (X points in the direction the door opens)
geometry_msgs/Transform door_corner_transform_to_world
# Whether the pose of the door frame is locked
bool pose_locked

# The door panel
perception_msgs/DoorPanelMessage door_panel

# The door opening mechanisms
perception_msgs/DoorOpeningMechanismMessage[] opening_mechanisms}</pre>
*/
public class DoorNodeMessage implements ROS2Message<DoorNodeMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::DoorNodeMessage_";

   /**
      The base scene node information
   */
   private final perception_msgs.msg.dds.DetectableSceneNodeMessage detectable_scene_node_;
   /**
      The transform of the frame of the door corner (X points in the direction the door opens)
   */
   private final geometry_msgs.msg.dds.Transform door_corner_transform_to_world_;
   /**
      Whether the pose of the door frame is locked
   */
   private boolean pose_locked_;
   /**
      The door panel
   */
   private final perception_msgs.msg.dds.DoorPanelMessage door_panel_;
   /**
      The door opening mechanisms
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.DoorOpeningMechanismMessage> opening_mechanisms_;

   public DoorNodeMessage()
   {
      detectable_scene_node_ = new perception_msgs.msg.dds.DetectableSceneNodeMessage();
      door_corner_transform_to_world_ = new geometry_msgs.msg.dds.Transform();
      pose_locked_ = (boolean) false;
      door_panel_ = new perception_msgs.msg.dds.DoorPanelMessage();
      opening_mechanisms_ = new IDLObjectSequence<perception_msgs.msg.dds.DoorOpeningMechanismMessage>(perception_msgs.msg.dds.DoorOpeningMechanismMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += detectable_scene_node_.calculateSizeBytes(currentAlignment);
      currentAlignment += door_corner_transform_to_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // pose_locked_
      currentAlignment += door_panel_.calculateSizeBytes(currentAlignment);
      currentAlignment += opening_mechanisms_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      detectable_scene_node_.serialize(buffer);
      door_corner_transform_to_world_.serialize(buffer);
      buffer.writeBoolean(pose_locked_);
      door_panel_.serialize(buffer);
      opening_mechanisms_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      detectable_scene_node_.deserialize(buffer);
      door_corner_transform_to_world_.deserialize(buffer);
      pose_locked_ = buffer.readBoolean();
      door_panel_.deserialize(buffer);
      opening_mechanisms_.deserialize(buffer);

   }

   @Override
   public void set(DoorNodeMessage from)
   {
      detectable_scene_node_.set(from.detectable_scene_node_);
      door_corner_transform_to_world_.set(from.door_corner_transform_to_world_);
      pose_locked_ = from.pose_locked_;
      door_panel_.set(from.door_panel_);
      opening_mechanisms_.set(from.opening_mechanisms_);

   }

   public perception_msgs.msg.dds.DetectableSceneNodeMessage getDetectableSceneNode()
   {
      return detectable_scene_node_;
   }

   public geometry_msgs.msg.dds.Transform getDoorCornerTransformToWorld()
   {
      return door_corner_transform_to_world_;
   }

   public boolean getPoseLocked()
   {
      return pose_locked_;
   }

   public void setPoseLocked(boolean pose_locked_)
   {
      this.pose_locked_ = pose_locked_;
   }

   public perception_msgs.msg.dds.DoorPanelMessage getDoorPanel()
   {
      return door_panel_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.DoorOpeningMechanismMessage> getOpeningMechanisms()
   {
      return opening_mechanisms_;
   }


}