/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC humanoid behavior module.
<p>Source (perception_msgs/DoorParameterPacket):
<pre>{@code
# This message is part of the IHMC humanoid behavior module.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

geometry_msgs/Point hinged_point_on_ground
geometry_msgs/Point end_point_on_ground

float64 door_height

geometry_msgs/Pose door_handle_transform_to_world

# Some behaviors will average the door location to remove noise, 
# trustedPosition allows someone to tell the behavior that this is an accurate location and and can does not need to be averaged, 
# this is useful for sending door locations manually from the ui
bool trusted_position false}</pre>
*/
public class DoorParameterPacket implements ROS2Message<DoorParameterPacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::DoorParameterPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final geometry_msgs.msg.dds.Point hinged_point_on_ground_;
   private final geometry_msgs.msg.dds.Point end_point_on_ground_;
   private double door_height_;
   private final geometry_msgs.msg.dds.Pose door_handle_transform_to_world_;
   /**
      Some behaviors will average the door location to remove noise,
      trustedPosition allows someone to tell the behavior that this is an accurate location and and can does not need to be averaged,
      this is useful for sending door locations manually from the ui
   */
   private boolean trusted_position_;

   public DoorParameterPacket()
   {
      hinged_point_on_ground_ = new geometry_msgs.msg.dds.Point();
      end_point_on_ground_ = new geometry_msgs.msg.dds.Point();
      door_handle_transform_to_world_ = new geometry_msgs.msg.dds.Pose();
      trusted_position_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += hinged_point_on_ground_.calculateSizeBytes(currentAlignment);
      currentAlignment += end_point_on_ground_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // door_height_
      currentAlignment += door_handle_transform_to_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // trusted_position_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      hinged_point_on_ground_.serialize(buffer);
      end_point_on_ground_.serialize(buffer);
      buffer.writeDouble(door_height_);
      door_handle_transform_to_world_.serialize(buffer);
      buffer.writeBoolean(trusted_position_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      hinged_point_on_ground_.deserialize(buffer);
      end_point_on_ground_.deserialize(buffer);
      door_height_ = buffer.readDouble();
      door_handle_transform_to_world_.deserialize(buffer);
      trusted_position_ = buffer.readBoolean();

   }

   @Override
   public void set(DoorParameterPacket from)
   {
      sequence_id_ = from.sequence_id_;
      hinged_point_on_ground_.set(from.hinged_point_on_ground_);
      end_point_on_ground_.set(from.end_point_on_ground_);
      door_height_ = from.door_height_;
      door_handle_transform_to_world_.set(from.door_handle_transform_to_world_);
      trusted_position_ = from.trusted_position_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public geometry_msgs.msg.dds.Point getHingedPointOnGround()
   {
      return hinged_point_on_ground_;
   }

   public geometry_msgs.msg.dds.Point getEndPointOnGround()
   {
      return end_point_on_ground_;
   }

   public double getDoorHeight()
   {
      return door_height_;
   }

   public void setDoorHeight(double door_height_)
   {
      this.door_height_ = door_height_;
   }

   public geometry_msgs.msg.dds.Pose getDoorHandleTransformToWorld()
   {
      return door_handle_transform_to_world_;
   }

   public boolean getTrustedPosition()
   {
      return trusted_position_;
   }

   public void setTrustedPosition(boolean trusted_position_)
   {
      this.trusted_position_ = trusted_position_;
   }


}