/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/DrillDetectionPacket):
<pre>{@code

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

bool is_drill_on}</pre>
*/
public class DrillDetectionPacket implements ROS2Message<DrillDetectionPacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::DrillDetectionPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private boolean is_drill_on_;

   public DrillDetectionPacket()
   {
      is_drill_on_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_drill_on_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(is_drill_on_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      is_drill_on_ = buffer.readBoolean();

   }

   @Override
   public void set(DrillDetectionPacket from)
   {
      sequence_id_ = from.sequence_id_;
      is_drill_on_ = from.is_drill_on_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getIsDrillOn()
   {
      return is_drill_on_;
   }

   public void setIsDrillOn(boolean is_drill_on_)
   {
      this.is_drill_on_ = is_drill_on_;
   }


}