/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/FisheyePacket):
<pre>{@code

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

VideoPacket video_packet}</pre>
*/
public class FisheyePacket implements ROS2Message<FisheyePacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::FisheyePacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final perception_msgs.msg.dds.VideoPacket video_packet_;

   public FisheyePacket()
   {
      video_packet_ = new perception_msgs.msg.dds.VideoPacket();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += video_packet_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      video_packet_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      video_packet_.deserialize(buffer);

   }

   @Override
   public void set(FisheyePacket from)
   {
      sequence_id_ = from.sequence_id_;
      video_packet_.set(from.video_packet_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public perception_msgs.msg.dds.VideoPacket getVideoPacket()
   {
      return video_packet_;
   }


}