/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
DetectableSceneNode for FoundationPose tracked objects
<p>Source (perception_msgs/FoundationPoseNodeMessage):
<pre>{@code
# DetectableSceneNode for FoundationPose tracked objects

# DetectableSceneNode information
perception_msgs/DetectableSceneNodeMessage detectable_scene_node

# Object's pose estimated by FoundationPose
geometry_msgs/Pose object_pose}</pre>
*/
public class FoundationPoseNodeMessage implements ROS2Message<FoundationPoseNodeMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::FoundationPoseNodeMessage_";

   /**
      DetectableSceneNode information
   */
   private final perception_msgs.msg.dds.DetectableSceneNodeMessage detectable_scene_node_;
   /**
      Object's pose estimated by FoundationPose
   */
   private final geometry_msgs.msg.dds.Pose object_pose_;

   public FoundationPoseNodeMessage()
   {
      detectable_scene_node_ = new perception_msgs.msg.dds.DetectableSceneNodeMessage();
      object_pose_ = new geometry_msgs.msg.dds.Pose();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += detectable_scene_node_.calculateSizeBytes(currentAlignment);
      currentAlignment += object_pose_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      detectable_scene_node_.serialize(buffer);
      object_pose_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      detectable_scene_node_.deserialize(buffer);
      object_pose_.deserialize(buffer);

   }

   @Override
   public void set(FoundationPoseNodeMessage from)
   {
      detectable_scene_node_.set(from.detectable_scene_node_);
      object_pose_.set(from.object_pose_);

   }

   public perception_msgs.msg.dds.DetectableSceneNodeMessage getDetectableSceneNode()
   {
      return detectable_scene_node_;
   }

   public geometry_msgs.msg.dds.Pose getObjectPose()
   {
      return object_pose_;
   }


}