/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Message for sending large colored point clouds,
discretized and compressed with LZ4,
and publishing partial scans at a higher rate to allow smaller message sizes
<p>Source (perception_msgs/FusedSensorHeadPointCloudMessage):
<pre>{@code
# Message for sending large colored point clouds,
# discretized and compressed with LZ4,
# and publishing partial scans at a higher rate to allow smaller message sizes

# Approximate sensor data aquisition time seconds since epoch
# Nanoseconds since the epoch goes beyond what a long can hold so we use two values.
int64 aquisition_seconds_since_epoch
# Approximate sensor data aquisition time additional nanoseconds
int64 aquisition_additional_nanos

# Total number of segments
uint32 number_of_segments

# Number of points per segment
int32 points_per_segment

# Segment this data represents
uint32 segment_index

# Compressed point cloud data
# Sized specifically for our current primary sensor head streaming
# 22220 * 4 * 4
byte[<=7000000] scan
}</pre>
*/
public class FusedSensorHeadPointCloudMessage implements ROS2Message<FusedSensorHeadPointCloudMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::FusedSensorHeadPointCloudMessage_";

   /**
      Approximate sensor data aquisition time seconds since epoch
      Nanoseconds since the epoch goes beyond what a long can hold so we use two values.
   */
   private long aquisition_seconds_since_epoch_;
   /**
      Approximate sensor data aquisition time additional nanoseconds
   */
   private long aquisition_additional_nanos_;
   /**
      Total number of segments
   */
   private int number_of_segments_;
   /**
      Number of points per segment
   */
   private int points_per_segment_;
   /**
      Segment this data represents
   */
   private int segment_index_;
   /**
      Compressed point cloud data
      Sized specifically for our current primary sensor head streaming
      22220 * 4 * 4
   */
   private final IDLByteSequence scan_;

   public FusedSensorHeadPointCloudMessage()
   {
      scan_ = new IDLByteSequence(7000000);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // aquisition_seconds_since_epoch_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // aquisition_additional_nanos_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // number_of_segments_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // points_per_segment_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // segment_index_
      currentAlignment += scan_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(aquisition_seconds_since_epoch_);
      buffer.writeLong(aquisition_additional_nanos_);
      buffer.writeInt(number_of_segments_);
      buffer.writeInt(points_per_segment_);
      buffer.writeInt(segment_index_);
      scan_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      aquisition_seconds_since_epoch_ = buffer.readLong();
      aquisition_additional_nanos_ = buffer.readLong();
      number_of_segments_ = buffer.readInt();
      points_per_segment_ = buffer.readInt();
      segment_index_ = buffer.readInt();
      scan_.deserialize(buffer);

   }

   @Override
   public void set(FusedSensorHeadPointCloudMessage from)
   {
      aquisition_seconds_since_epoch_ = from.aquisition_seconds_since_epoch_;
      aquisition_additional_nanos_ = from.aquisition_additional_nanos_;
      number_of_segments_ = from.number_of_segments_;
      points_per_segment_ = from.points_per_segment_;
      segment_index_ = from.segment_index_;
      scan_.set(from.scan_);

   }

   public long getAquisitionSecondsSinceEpoch()
   {
      return aquisition_seconds_since_epoch_;
   }

   public void setAquisitionSecondsSinceEpoch(long aquisition_seconds_since_epoch_)
   {
      this.aquisition_seconds_since_epoch_ = aquisition_seconds_since_epoch_;
   }

   public long getAquisitionAdditionalNanos()
   {
      return aquisition_additional_nanos_;
   }

   public void setAquisitionAdditionalNanos(long aquisition_additional_nanos_)
   {
      this.aquisition_additional_nanos_ = aquisition_additional_nanos_;
   }

   public int getNumberOfSegments()
   {
      return number_of_segments_;
   }

   public void setNumberOfSegments(int number_of_segments_)
   {
      this.number_of_segments_ = number_of_segments_;
   }

   public int getPointsPerSegment()
   {
      return points_per_segment_;
   }

   public void setPointsPerSegment(int points_per_segment_)
   {
      this.points_per_segment_ = points_per_segment_;
   }

   public int getSegmentIndex()
   {
      return segment_index_;
   }

   public void setSegmentIndex(int segment_index_)
   {
      this.segment_index_ = segment_index_;
   }

   public IDLByteSequence getScan()
   {
      return scan_;
   }


}