/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/HeatMapPacket):
<pre>{@code

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

float32[] data
int32 width
int32 height
string name}</pre>
*/
public class HeatMapPacket implements ROS2Message<HeatMapPacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::HeatMapPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final IDLFloatSequence data_;
   private int width_;
   private int height_;
   private final StringBuilder name_;

   public HeatMapPacket()
   {
      data_ = new IDLFloatSequence();
      name_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += data_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // width_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // height_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      data_.serialize(buffer);
      buffer.writeInt(width_);
      buffer.writeInt(height_);
      buffer.writeString(name_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      data_.deserialize(buffer);
      width_ = buffer.readInt();
      height_ = buffer.readInt();
      buffer.readString(name_);

   }

   @Override
   public void set(HeatMapPacket from)
   {
      sequence_id_ = from.sequence_id_;
      data_.set(from.data_);
      width_ = from.width_;
      height_ = from.height_;
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLFloatSequence getData()
   {
      return data_;
   }

   public int getWidth()
   {
      return width_;
   }

   public void setWidth(int width_)
   {
      this.width_ = width_;
   }

   public int getHeight()
   {
      return height_;
   }

   public void setHeight(int height_)
   {
      this.height_ = height_;
   }

   public StringBuilder getName()
   {
      return name_;
   }


}