/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC height quad tree module
<p>Source (perception_msgs/HeightQuadTreeLeafMessage):
<pre>{@code
# This message is part of the IHMC height quad tree module

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

float32 center_x
float32 center_y
float32 height}</pre>
*/
public class HeightQuadTreeLeafMessage implements ROS2Message<HeightQuadTreeLeafMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::HeightQuadTreeLeafMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private float center_x_;
   private float center_y_;
   private float height_;

   public HeightQuadTreeLeafMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // center_x_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // center_y_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // height_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeFloat(center_x_);
      buffer.writeFloat(center_y_);
      buffer.writeFloat(height_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      center_x_ = buffer.readFloat();
      center_y_ = buffer.readFloat();
      height_ = buffer.readFloat();

   }

   @Override
   public void set(HeightQuadTreeLeafMessage from)
   {
      sequence_id_ = from.sequence_id_;
      center_x_ = from.center_x_;
      center_y_ = from.center_y_;
      height_ = from.height_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public float getCenterX()
   {
      return center_x_;
   }

   public void setCenterX(float center_x_)
   {
      this.center_x_ = center_x_;
   }

   public float getCenterY()
   {
      return center_y_;
   }

   public void setCenterY(float center_y_)
   {
      this.center_y_ = center_y_;
   }

   public float getHeight()
   {
      return height_;
   }

   public void setHeight(float height_)
   {
      this.height_ = height_;
   }


}