/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC height quad tree module
<p>Source (perception_msgs/HeightQuadTreeMessage):
<pre>{@code
# This message is part of the IHMC height quad tree module

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

float32 default_height
float32 resolution
float32 size_x
float32 size_y
HeightQuadTreeLeafMessage[<=5000] leaves}</pre>
*/
public class HeightQuadTreeMessage implements ROS2Message<HeightQuadTreeMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::HeightQuadTreeMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private float default_height_;
   private float resolution_;
   private float size_x_;
   private float size_y_;
   private final IDLObjectSequence<perception_msgs.msg.dds.HeightQuadTreeLeafMessage> leaves_;

   public HeightQuadTreeMessage()
   {
      leaves_ = new IDLObjectSequence<perception_msgs.msg.dds.HeightQuadTreeLeafMessage>(5000, perception_msgs.msg.dds.HeightQuadTreeLeafMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // default_height_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // resolution_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // size_x_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // size_y_
      currentAlignment += leaves_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeFloat(default_height_);
      buffer.writeFloat(resolution_);
      buffer.writeFloat(size_x_);
      buffer.writeFloat(size_y_);
      leaves_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      default_height_ = buffer.readFloat();
      resolution_ = buffer.readFloat();
      size_x_ = buffer.readFloat();
      size_y_ = buffer.readFloat();
      leaves_.deserialize(buffer);

   }

   @Override
   public void set(HeightQuadTreeMessage from)
   {
      sequence_id_ = from.sequence_id_;
      default_height_ = from.default_height_;
      resolution_ = from.resolution_;
      size_x_ = from.size_x_;
      size_y_ = from.size_y_;
      leaves_.set(from.leaves_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public float getDefaultHeight()
   {
      return default_height_;
   }

   public void setDefaultHeight(float default_height_)
   {
      this.default_height_ = default_height_;
   }

   public float getResolution()
   {
      return resolution_;
   }

   public void setResolution(float resolution_)
   {
      this.resolution_ = resolution_;
   }

   public float getSizeX()
   {
      return size_x_;
   }

   public void setSizeX(float size_x_)
   {
      this.size_x_ = size_x_;
   }

   public float getSizeY()
   {
      return size_y_;
   }

   public void setSizeY(float size_y_)
   {
      this.size_y_ = size_y_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.HeightQuadTreeLeafMessage> getLeaves()
   {
      return leaves_;
   }


}