/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/Image32):
<pre>{@code
# This message can be used as a general image.
# Each component of the data which of length is same with width * height is an integer value describing color with the conventional RGB.
# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

int32 width

int32 height

int32[<=4000000] rgbdata}</pre>
*/
public class Image32 implements ROS2Message<Image32>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::Image32_";

   /**
      This message can be used as a general image.
      Each component of the data which of length is same with width * height is an integer value describing color with the conventional RGB.
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private int width_;
   private int height_;
   private final IDLIntSequence rgbdata_;

   public Image32()
   {
      rgbdata_ = new IDLIntSequence(4000000);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // width_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // height_
      currentAlignment += rgbdata_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeInt(width_);
      buffer.writeInt(height_);
      rgbdata_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      width_ = buffer.readInt();
      height_ = buffer.readInt();
      rgbdata_.deserialize(buffer);

   }

   @Override
   public void set(Image32 from)
   {
      sequence_id_ = from.sequence_id_;
      width_ = from.width_;
      height_ = from.height_;
      rgbdata_.set(from.rgbdata_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public int getWidth()
   {
      return width_;
   }

   public void setWidth(int width_)
   {
      this.width_ = width_;
   }

   public int getHeight()
   {
      return height_;
   }

   public void setHeight(int height_)
   {
      this.height_ = height_;
   }

   public IDLIntSequence getRgbdata()
   {
      return rgbdata_;
   }


}