/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message should disappear to be replaced by ROS equivalent.
<p>Source (perception_msgs/LidarScanMessage):
<pre>{@code
# This message should disappear to be replaced by ROS equivalent.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

int64 robot_timestamp
geometry_msgs/Point lidar_position
geometry_msgs/Quaternion lidar_orientation

# There are two types of confidence value noticing the quality of the data for sensor pose and point cloud.
# The range of confidence is from 0.0 with the worst quality to 1.0 with the best quality.
# The confidence of the sensor pose represents the quality of the pose estimation.
float64 sensor_pose_confidence 1.0
# There are two types of confidence value noticing the quality of the data for sensor pose and point cloud.
# The range of confidence is from 0.0 with the worst quality to 1.0 with the best quality.
# The confidence of the point cloud represents the quality of the collected point cloud data.
float64 point_cloud_confidence 1.0
# Number of points in the pointcloud
int32 number_of_points
# Compressed pointcloud data. See us.ihmc.communication.packets.LidarPointCloudCompression for method to compress and decompress
byte[<=2000000] scan}</pre>
*/
public class LidarScanMessage implements ROS2Message<LidarScanMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::LidarScanMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private long robot_timestamp_;
   private final geometry_msgs.msg.dds.Point lidar_position_;
   private final geometry_msgs.msg.dds.Quaternion lidar_orientation_;
   /**
      There are two types of confidence value noticing the quality of the data for sensor pose and point cloud.
      The range of confidence is from 0.0 with the worst quality to 1.0 with the best quality.
      The confidence of the sensor pose represents the quality of the pose estimation.
   */
   private double sensor_pose_confidence_;
   /**
      There are two types of confidence value noticing the quality of the data for sensor pose and point cloud.
      The range of confidence is from 0.0 with the worst quality to 1.0 with the best quality.
      The confidence of the point cloud represents the quality of the collected point cloud data.
   */
   private double point_cloud_confidence_;
   /**
      Number of points in the pointcloud
   */
   private int number_of_points_;
   /**
      Compressed pointcloud data. See us.ihmc.communication.packets.LidarPointCloudCompression for method to compress and decompress
   */
   private final IDLByteSequence scan_;

   public LidarScanMessage()
   {
      lidar_position_ = new geometry_msgs.msg.dds.Point();
      lidar_orientation_ = new geometry_msgs.msg.dds.Quaternion();
      sensor_pose_confidence_ = (double) 1.0;
      point_cloud_confidence_ = (double) 1.0;
      scan_ = new IDLByteSequence(2000000);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // robot_timestamp_
      currentAlignment += lidar_position_.calculateSizeBytes(currentAlignment);
      currentAlignment += lidar_orientation_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sensor_pose_confidence_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // point_cloud_confidence_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // number_of_points_
      currentAlignment += scan_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeLong(robot_timestamp_);
      lidar_position_.serialize(buffer);
      lidar_orientation_.serialize(buffer);
      buffer.writeDouble(sensor_pose_confidence_);
      buffer.writeDouble(point_cloud_confidence_);
      buffer.writeInt(number_of_points_);
      scan_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      robot_timestamp_ = buffer.readLong();
      lidar_position_.deserialize(buffer);
      lidar_orientation_.deserialize(buffer);
      sensor_pose_confidence_ = buffer.readDouble();
      point_cloud_confidence_ = buffer.readDouble();
      number_of_points_ = buffer.readInt();
      scan_.deserialize(buffer);

   }

   @Override
   public void set(LidarScanMessage from)
   {
      sequence_id_ = from.sequence_id_;
      robot_timestamp_ = from.robot_timestamp_;
      lidar_position_.set(from.lidar_position_);
      lidar_orientation_.set(from.lidar_orientation_);
      sensor_pose_confidence_ = from.sensor_pose_confidence_;
      point_cloud_confidence_ = from.point_cloud_confidence_;
      number_of_points_ = from.number_of_points_;
      scan_.set(from.scan_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public long getRobotTimestamp()
   {
      return robot_timestamp_;
   }

   public void setRobotTimestamp(long robot_timestamp_)
   {
      this.robot_timestamp_ = robot_timestamp_;
   }

   public geometry_msgs.msg.dds.Point getLidarPosition()
   {
      return lidar_position_;
   }

   public geometry_msgs.msg.dds.Quaternion getLidarOrientation()
   {
      return lidar_orientation_;
   }

   public double getSensorPoseConfidence()
   {
      return sensor_pose_confidence_;
   }

   public void setSensorPoseConfidence(double sensor_pose_confidence_)
   {
      this.sensor_pose_confidence_ = sensor_pose_confidence_;
   }

   public double getPointCloudConfidence()
   {
      return point_cloud_confidence_;
   }

   public void setPointCloudConfidence(double point_cloud_confidence_)
   {
      this.point_cloud_confidence_ = point_cloud_confidence_;
   }

   public int getNumberOfPoints()
   {
      return number_of_points_;
   }

   public void setNumberOfPoints(int number_of_points_)
   {
      this.number_of_points_ = number_of_points_;
   }

   public IDLByteSequence getScan()
   {
      return scan_;
   }


}