/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Message used for simulated LIDAR
<p>Source (perception_msgs/LidarScanParametersMessage):
<pre>{@code
# Message used for simulated LIDAR

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

int64 timestamp

float32 sweep_yaw_max
float32 sweep_yaw_min
float32 height_pitch_max
float32 height_pitch_min
float32 time_increment
float32 scan_time
float32 min_range
float32 max_range

int32 points_per_sweep
int32 scan_height}</pre>
*/
public class LidarScanParametersMessage implements ROS2Message<LidarScanParametersMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::LidarScanParametersMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private long timestamp_;
   private float sweep_yaw_max_;
   private float sweep_yaw_min_;
   private float height_pitch_max_;
   private float height_pitch_min_;
   private float time_increment_;
   private float scan_time_;
   private float min_range_;
   private float max_range_;
   private int points_per_sweep_;
   private int scan_height_;

   public LidarScanParametersMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // timestamp_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // sweep_yaw_max_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // sweep_yaw_min_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // height_pitch_max_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // height_pitch_min_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // time_increment_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // scan_time_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // min_range_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // max_range_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // points_per_sweep_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // scan_height_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeLong(timestamp_);
      buffer.writeFloat(sweep_yaw_max_);
      buffer.writeFloat(sweep_yaw_min_);
      buffer.writeFloat(height_pitch_max_);
      buffer.writeFloat(height_pitch_min_);
      buffer.writeFloat(time_increment_);
      buffer.writeFloat(scan_time_);
      buffer.writeFloat(min_range_);
      buffer.writeFloat(max_range_);
      buffer.writeInt(points_per_sweep_);
      buffer.writeInt(scan_height_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      timestamp_ = buffer.readLong();
      sweep_yaw_max_ = buffer.readFloat();
      sweep_yaw_min_ = buffer.readFloat();
      height_pitch_max_ = buffer.readFloat();
      height_pitch_min_ = buffer.readFloat();
      time_increment_ = buffer.readFloat();
      scan_time_ = buffer.readFloat();
      min_range_ = buffer.readFloat();
      max_range_ = buffer.readFloat();
      points_per_sweep_ = buffer.readInt();
      scan_height_ = buffer.readInt();

   }

   @Override
   public void set(LidarScanParametersMessage from)
   {
      sequence_id_ = from.sequence_id_;
      timestamp_ = from.timestamp_;
      sweep_yaw_max_ = from.sweep_yaw_max_;
      sweep_yaw_min_ = from.sweep_yaw_min_;
      height_pitch_max_ = from.height_pitch_max_;
      height_pitch_min_ = from.height_pitch_min_;
      time_increment_ = from.time_increment_;
      scan_time_ = from.scan_time_;
      min_range_ = from.min_range_;
      max_range_ = from.max_range_;
      points_per_sweep_ = from.points_per_sweep_;
      scan_height_ = from.scan_height_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public long getTimestamp()
   {
      return timestamp_;
   }

   public void setTimestamp(long timestamp_)
   {
      this.timestamp_ = timestamp_;
   }

   public float getSweepYawMax()
   {
      return sweep_yaw_max_;
   }

   public void setSweepYawMax(float sweep_yaw_max_)
   {
      this.sweep_yaw_max_ = sweep_yaw_max_;
   }

   public float getSweepYawMin()
   {
      return sweep_yaw_min_;
   }

   public void setSweepYawMin(float sweep_yaw_min_)
   {
      this.sweep_yaw_min_ = sweep_yaw_min_;
   }

   public float getHeightPitchMax()
   {
      return height_pitch_max_;
   }

   public void setHeightPitchMax(float height_pitch_max_)
   {
      this.height_pitch_max_ = height_pitch_max_;
   }

   public float getHeightPitchMin()
   {
      return height_pitch_min_;
   }

   public void setHeightPitchMin(float height_pitch_min_)
   {
      this.height_pitch_min_ = height_pitch_min_;
   }

   public float getTimeIncrement()
   {
      return time_increment_;
   }

   public void setTimeIncrement(float time_increment_)
   {
      this.time_increment_ = time_increment_;
   }

   public float getScanTime()
   {
      return scan_time_;
   }

   public void setScanTime(float scan_time_)
   {
      this.scan_time_ = scan_time_;
   }

   public float getMinRange()
   {
      return min_range_;
   }

   public void setMinRange(float min_range_)
   {
      this.min_range_ = min_range_;
   }

   public float getMaxRange()
   {
      return max_range_;
   }

   public void setMaxRange(float max_range_)
   {
      this.max_range_ = max_range_;
   }

   public int getPointsPerSweep()
   {
      return points_per_sweep_;
   }

   public void setPointsPerSweep(int points_per_sweep_)
   {
      this.points_per_sweep_ = points_per_sweep_;
   }

   public int getScanHeight()
   {
      return scan_height_;
   }

   public void setScanHeight(int scan_height_)
   {
      this.scan_height_ = scan_height_;
   }


}