/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/MultisenseParameterPacket):
<pre>{@code

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

bool initialize
float64 gain
float64 motor_speed
bool led_enable
bool flash_enable
float64 duty_cycle
bool auto_exposure
bool auto_white_balance
}</pre>
*/
public class MultisenseParameterPacket implements ROS2Message<MultisenseParameterPacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::MultisenseParameterPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private boolean initialize_;
   private double gain_;
   private double motor_speed_;
   private boolean led_enable_;
   private boolean flash_enable_;
   private double duty_cycle_;
   private boolean auto_exposure_;
   private boolean auto_white_balance_;

   public MultisenseParameterPacket()
   {
      initialize_ = (boolean) false;
      led_enable_ = (boolean) false;
      flash_enable_ = (boolean) false;
      auto_exposure_ = (boolean) false;
      auto_white_balance_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // initialize_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // gain_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // motor_speed_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // led_enable_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // flash_enable_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // duty_cycle_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // auto_exposure_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // auto_white_balance_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(initialize_);
      buffer.writeDouble(gain_);
      buffer.writeDouble(motor_speed_);
      buffer.writeBoolean(led_enable_);
      buffer.writeBoolean(flash_enable_);
      buffer.writeDouble(duty_cycle_);
      buffer.writeBoolean(auto_exposure_);
      buffer.writeBoolean(auto_white_balance_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      initialize_ = buffer.readBoolean();
      gain_ = buffer.readDouble();
      motor_speed_ = buffer.readDouble();
      led_enable_ = buffer.readBoolean();
      flash_enable_ = buffer.readBoolean();
      duty_cycle_ = buffer.readDouble();
      auto_exposure_ = buffer.readBoolean();
      auto_white_balance_ = buffer.readBoolean();

   }

   @Override
   public void set(MultisenseParameterPacket from)
   {
      sequence_id_ = from.sequence_id_;
      initialize_ = from.initialize_;
      gain_ = from.gain_;
      motor_speed_ = from.motor_speed_;
      led_enable_ = from.led_enable_;
      flash_enable_ = from.flash_enable_;
      duty_cycle_ = from.duty_cycle_;
      auto_exposure_ = from.auto_exposure_;
      auto_white_balance_ = from.auto_white_balance_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getInitialize()
   {
      return initialize_;
   }

   public void setInitialize(boolean initialize_)
   {
      this.initialize_ = initialize_;
   }

   public double getGain()
   {
      return gain_;
   }

   public void setGain(double gain_)
   {
      this.gain_ = gain_;
   }

   public double getMotorSpeed()
   {
      return motor_speed_;
   }

   public void setMotorSpeed(double motor_speed_)
   {
      this.motor_speed_ = motor_speed_;
   }

   public boolean getLedEnable()
   {
      return led_enable_;
   }

   public void setLedEnable(boolean led_enable_)
   {
      this.led_enable_ = led_enable_;
   }

   public boolean getFlashEnable()
   {
      return flash_enable_;
   }

   public void setFlashEnable(boolean flash_enable_)
   {
      this.flash_enable_ = flash_enable_;
   }

   public double getDutyCycle()
   {
      return duty_cycle_;
   }

   public void setDutyCycle(double duty_cycle_)
   {
      this.duty_cycle_ = duty_cycle_;
   }

   public boolean getAutoExposure()
   {
      return auto_exposure_;
   }

   public void setAutoExposure(boolean auto_exposure_)
   {
      this.auto_exposure_ = auto_exposure_;
   }

   public boolean getAutoWhiteBalance()
   {
      return auto_white_balance_;
   }

   public void setAutoWhiteBalance(boolean auto_white_balance_)
   {
      this.auto_white_balance_ = auto_white_balance_;
   }


}