/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC robot environment awareness module.
This message contains a list of occupied cells in the octree
All keys are given at maximum depth
<p>Source (perception_msgs/OcTreeKeyListMessage):
<pre>{@code
# This message is part of the IHMC robot environment awareness module.
# This message contains a list of occupied cells in the octree
# All keys are given at maximum depth

int32 tree_depth
float64 tree_resolution
int32 number_of_keys

# See us.ihmc.robotEnvironmentAwareness.communication.converters.OcTreeMessageConvterter for info on the compression protocol
byte[<=200000] keys
}</pre>
*/
public class OcTreeKeyListMessage implements ROS2Message<OcTreeKeyListMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::OcTreeKeyListMessage_";

   private int tree_depth_;
   private double tree_resolution_;
   private int number_of_keys_;
   /**
      See us.ihmc.robotEnvironmentAwareness.communication.converters.OcTreeMessageConvterter for info on the compression protocol
   */
   private final IDLByteSequence keys_;

   public OcTreeKeyListMessage()
   {
      keys_ = new IDLByteSequence(200000);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // tree_depth_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // tree_resolution_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // number_of_keys_
      currentAlignment += keys_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(tree_depth_);
      buffer.writeDouble(tree_resolution_);
      buffer.writeInt(number_of_keys_);
      keys_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      tree_depth_ = buffer.readInt();
      tree_resolution_ = buffer.readDouble();
      number_of_keys_ = buffer.readInt();
      keys_.deserialize(buffer);

   }

   @Override
   public void set(OcTreeKeyListMessage from)
   {
      tree_depth_ = from.tree_depth_;
      tree_resolution_ = from.tree_resolution_;
      number_of_keys_ = from.number_of_keys_;
      keys_.set(from.keys_);

   }

   public int getTreeDepth()
   {
      return tree_depth_;
   }

   public void setTreeDepth(int tree_depth_)
   {
      this.tree_depth_ = tree_depth_;
   }

   public double getTreeResolution()
   {
      return tree_resolution_;
   }

   public void setTreeResolution(double tree_resolution_)
   {
      this.tree_resolution_ = tree_resolution_;
   }

   public int getNumberOfKeys()
   {
      return number_of_keys_;
   }

   public void setNumberOfKeys(int number_of_keys_)
   {
      this.number_of_keys_ = number_of_keys_;
   }

   public IDLByteSequence getKeys()
   {
      return keys_;
   }


}