/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC Robot Environment Awareness (REA) module.
<p>Source (perception_msgs/PolygonizerParametersMessage):
<pre>{@code
# This message is part of the IHMC Robot Environment Awareness (REA) module.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Threshold used when creating a new concave hull.
# Uses the Duckham and al. (2008) algorithm defined in the paper "Efficient generation of
# simple polygons for characterizing the shape of a set of points in the plane".
float64 concave_hull_threshold 0.15

# The minimum number of nodes required for a region to be polygonized.
int32 min_number_of_nodes 10

# Filter parameter on the concave hull of a region. Used to removed vertices describing shallow angle.
float64 shallow_angle_threshold 0.01745

# Filter parameter on the concave hull of a region. Used to removed vertices that create peaks.
float64 peak_angle_threshold 2.967

# Filter parameter on the concave hull of a region. Used to removed short edges.
float64 length_threshold 0.05

# Threshold used for decomposing the concave hull into convex polygons. Describes the maximum depth
# of a concavity before the concave hull gets split in 2.
float64 depth_threshold 0.10

# Filter for splitting concave hulls at any narrow passage which width is less than (2 * length_threshold).
bool cut_narrow_passage true}</pre>
*/
public class PolygonizerParametersMessage implements ROS2Message<PolygonizerParametersMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::PolygonizerParametersMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Threshold used when creating a new concave hull.
      Uses the Duckham and al. (2008) algorithm defined in the paper "Efficient generation of
      simple polygons for characterizing the shape of a set of points in the plane".
   */
   private double concave_hull_threshold_;
   /**
      The minimum number of nodes required for a region to be polygonized.
   */
   private int min_number_of_nodes_;
   /**
      Filter parameter on the concave hull of a region. Used to removed vertices describing shallow angle.
   */
   private double shallow_angle_threshold_;
   /**
      Filter parameter on the concave hull of a region. Used to removed vertices that create peaks.
   */
   private double peak_angle_threshold_;
   /**
      Filter parameter on the concave hull of a region. Used to removed short edges.
   */
   private double length_threshold_;
   /**
      Threshold used for decomposing the concave hull into convex polygons. Describes the maximum depth
      of a concavity before the concave hull gets split in 2.
   */
   private double depth_threshold_;
   /**
      Filter for splitting concave hulls at any narrow passage which width is less than (2 * length_threshold).
   */
   private boolean cut_narrow_passage_;

   public PolygonizerParametersMessage()
   {
      concave_hull_threshold_ = (double) 0.15;
      min_number_of_nodes_ = (int) 10;
      shallow_angle_threshold_ = (double) 0.01745;
      peak_angle_threshold_ = (double) 2.967;
      length_threshold_ = (double) 0.05;
      depth_threshold_ = (double) 0.10;
      cut_narrow_passage_ = (boolean) true;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // concave_hull_threshold_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // min_number_of_nodes_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // shallow_angle_threshold_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // peak_angle_threshold_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // length_threshold_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // depth_threshold_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // cut_narrow_passage_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeDouble(concave_hull_threshold_);
      buffer.writeInt(min_number_of_nodes_);
      buffer.writeDouble(shallow_angle_threshold_);
      buffer.writeDouble(peak_angle_threshold_);
      buffer.writeDouble(length_threshold_);
      buffer.writeDouble(depth_threshold_);
      buffer.writeBoolean(cut_narrow_passage_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      concave_hull_threshold_ = buffer.readDouble();
      min_number_of_nodes_ = buffer.readInt();
      shallow_angle_threshold_ = buffer.readDouble();
      peak_angle_threshold_ = buffer.readDouble();
      length_threshold_ = buffer.readDouble();
      depth_threshold_ = buffer.readDouble();
      cut_narrow_passage_ = buffer.readBoolean();

   }

   @Override
   public void set(PolygonizerParametersMessage from)
   {
      sequence_id_ = from.sequence_id_;
      concave_hull_threshold_ = from.concave_hull_threshold_;
      min_number_of_nodes_ = from.min_number_of_nodes_;
      shallow_angle_threshold_ = from.shallow_angle_threshold_;
      peak_angle_threshold_ = from.peak_angle_threshold_;
      length_threshold_ = from.length_threshold_;
      depth_threshold_ = from.depth_threshold_;
      cut_narrow_passage_ = from.cut_narrow_passage_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public double getConcaveHullThreshold()
   {
      return concave_hull_threshold_;
   }

   public void setConcaveHullThreshold(double concave_hull_threshold_)
   {
      this.concave_hull_threshold_ = concave_hull_threshold_;
   }

   public int getMinNumberOfNodes()
   {
      return min_number_of_nodes_;
   }

   public void setMinNumberOfNodes(int min_number_of_nodes_)
   {
      this.min_number_of_nodes_ = min_number_of_nodes_;
   }

   public double getShallowAngleThreshold()
   {
      return shallow_angle_threshold_;
   }

   public void setShallowAngleThreshold(double shallow_angle_threshold_)
   {
      this.shallow_angle_threshold_ = shallow_angle_threshold_;
   }

   public double getPeakAngleThreshold()
   {
      return peak_angle_threshold_;
   }

   public void setPeakAngleThreshold(double peak_angle_threshold_)
   {
      this.peak_angle_threshold_ = peak_angle_threshold_;
   }

   public double getLengthThreshold()
   {
      return length_threshold_;
   }

   public void setLengthThreshold(double length_threshold_)
   {
      this.length_threshold_ = length_threshold_;
   }

   public double getDepthThreshold()
   {
      return depth_threshold_;
   }

   public void setDepthThreshold(double depth_threshold_)
   {
      this.depth_threshold_ = depth_threshold_;
   }

   public boolean getCutNarrowPassage()
   {
      return cut_narrow_passage_;
   }

   public void setCutNarrowPassage(boolean cut_narrow_passage_)
   {
      this.cut_narrow_passage_ = cut_narrow_passage_;
   }


}