/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC robot environment awareness module (REA).
It is destined to gather complementary information related to the current state REA is in.
<p>Source (perception_msgs/REAStatusMessage):
<pre>{@code
# This message is part of the IHMC robot environment awareness module (REA).
# It is destined to gather complementary information related to the current state REA is in.

# Informs if REA is currently collecting sensor data and estimating planar regions.
# Note that if both, is_using_lidar and is_using_stereo_vision are false, REA is running but not collecting data.
bool is_running false
# Informs whether REA is collecting LIDAR data or not.
bool is_using_lidar false
# Informs whether REA is collecting pointcloud data from a stereo-camera.
bool is_using_stereo_vision false
# Informs whether REA's internal data has just been cleared.
bool has_cleared false

# Provides the current set of filter parameters used in REA.
REASensorDataFilterParametersMessage current_sensor_filter_parameters}</pre>
*/
public class REAStatusMessage implements ROS2Message<REAStatusMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::REAStatusMessage_";

   /**
      Informs if REA is currently collecting sensor data and estimating planar regions.
      Note that if both, is_using_lidar and is_using_stereo_vision are false, REA is running but not collecting data.
   */
   private boolean is_running_;
   /**
      Informs whether REA is collecting LIDAR data or not.
   */
   private boolean is_using_lidar_;
   /**
      Informs whether REA is collecting pointcloud data from a stereo-camera.
   */
   private boolean is_using_stereo_vision_;
   /**
      Informs whether REA's internal data has just been cleared.
   */
   private boolean has_cleared_;
   /**
      Provides the current set of filter parameters used in REA.
   */
   private final perception_msgs.msg.dds.REASensorDataFilterParametersMessage current_sensor_filter_parameters_;

   public REAStatusMessage()
   {
      is_running_ = (boolean) false;
      is_using_lidar_ = (boolean) false;
      is_using_stereo_vision_ = (boolean) false;
      has_cleared_ = (boolean) false;
      current_sensor_filter_parameters_ = new perception_msgs.msg.dds.REASensorDataFilterParametersMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_running_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_using_lidar_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_using_stereo_vision_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // has_cleared_
      currentAlignment += current_sensor_filter_parameters_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(is_running_);
      buffer.writeBoolean(is_using_lidar_);
      buffer.writeBoolean(is_using_stereo_vision_);
      buffer.writeBoolean(has_cleared_);
      current_sensor_filter_parameters_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      is_running_ = buffer.readBoolean();
      is_using_lidar_ = buffer.readBoolean();
      is_using_stereo_vision_ = buffer.readBoolean();
      has_cleared_ = buffer.readBoolean();
      current_sensor_filter_parameters_.deserialize(buffer);

   }

   @Override
   public void set(REAStatusMessage from)
   {
      is_running_ = from.is_running_;
      is_using_lidar_ = from.is_using_lidar_;
      is_using_stereo_vision_ = from.is_using_stereo_vision_;
      has_cleared_ = from.has_cleared_;
      current_sensor_filter_parameters_.set(from.current_sensor_filter_parameters_);

   }

   public boolean getIsRunning()
   {
      return is_running_;
   }

   public void setIsRunning(boolean is_running_)
   {
      this.is_running_ = is_running_;
   }

   public boolean getIsUsingLidar()
   {
      return is_using_lidar_;
   }

   public void setIsUsingLidar(boolean is_using_lidar_)
   {
      this.is_using_lidar_ = is_using_lidar_;
   }

   public boolean getIsUsingStereoVision()
   {
      return is_using_stereo_vision_;
   }

   public void setIsUsingStereoVision(boolean is_using_stereo_vision_)
   {
      this.is_using_stereo_vision_ = is_using_stereo_vision_;
   }

   public boolean getHasCleared()
   {
      return has_cleared_;
   }

   public void setHasCleared(boolean has_cleared_)
   {
      this.has_cleared_ = has_cleared_;
   }

   public perception_msgs.msg.dds.REASensorDataFilterParametersMessage getCurrentSensorFilterParameters()
   {
      return current_sensor_filter_parameters_;
   }


}