/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC robot environment awareness module (REA).
This provides access to a few filters used in REA.
<p>Source (perception_msgs/REASensorDataFilterParametersMessage):
<pre>{@code
# This message is part of the IHMC robot environment awareness module (REA).
# This provides access to a few filters used in REA.

# Lower-bound of the bounding box inside which sensor data will be processed into planar regions.
# Note that the coordinates are relative to the sensor position and yaw:
# - x-coordinate: represents the distance in front (positive) or in the back (negative) of the sensor.
# - y-coordinate: represents the distance to the left (positive) or to the right (negative) of the sensor.
# - z-coordinate: represents the distance above (positive) or below (negative) of the sensor.
# Sensor data collected outside this bounding box is still used to help estimating empty space inside it.
# If any of the lower-bound coordinates is NaN, the bounding box parameters will be ignored.
geometry_msgs/Point bounding_box_min
# Upper-bound of the bounding box inside which sensor data will be processed into planar regions.
# Note that the coordinates are relative to the sensor position and yaw:
# - x-coordinate: represents the distance in front (positive) or in the back (negative) of the sensor.
# - y-coordinate: represents the distance to the left (positive) or to the right (negative) of the sensor.
# - z-coordinate: represents the distance above (positive) or below (negative) of the sensor.
# Sensor data collected outside this bounding box is still used to help estimating empty space inside it.
# If any of the upper-bound coordinates is NaN, the bounding box parameters will be ignored.
geometry_msgs/Point bounding_box_max
# Defines a bounding sphere centered at the sensor within which sensor data will be processed into planar regions.
# Sensor data collected outside this bounding sphere is still used to help estimating empty space inside it.
# A negative value will be ignored.
float64 sensor_max_range
# Defines a bounding sphere centered at the sensor within which sensor data is to be ignored.
# A negative value will be ignored.
float64 sensor_min_range}</pre>
*/
public class REASensorDataFilterParametersMessage implements ROS2Message<REASensorDataFilterParametersMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::REASensorDataFilterParametersMessage_";

   /**
      Lower-bound of the bounding box inside which sensor data will be processed into planar regions.
      Note that the coordinates are relative to the sensor position and yaw:
      - x-coordinate: represents the distance in front (positive) or in the back (negative) of the sensor.
      - y-coordinate: represents the distance to the left (positive) or to the right (negative) of the sensor.
      - z-coordinate: represents the distance above (positive) or below (negative) of the sensor.
      Sensor data collected outside this bounding box is still used to help estimating empty space inside it.
      If any of the lower-bound coordinates is NaN, the bounding box parameters will be ignored.
   */
   private final geometry_msgs.msg.dds.Point bounding_box_min_;
   /**
      Upper-bound of the bounding box inside which sensor data will be processed into planar regions.
      Note that the coordinates are relative to the sensor position and yaw:
      - x-coordinate: represents the distance in front (positive) or in the back (negative) of the sensor.
      - y-coordinate: represents the distance to the left (positive) or to the right (negative) of the sensor.
      - z-coordinate: represents the distance above (positive) or below (negative) of the sensor.
      Sensor data collected outside this bounding box is still used to help estimating empty space inside it.
      If any of the upper-bound coordinates is NaN, the bounding box parameters will be ignored.
   */
   private final geometry_msgs.msg.dds.Point bounding_box_max_;
   /**
      Defines a bounding sphere centered at the sensor within which sensor data will be processed into planar regions.
      Sensor data collected outside this bounding sphere is still used to help estimating empty space inside it.
      A negative value will be ignored.
   */
   private double sensor_max_range_;
   /**
      Defines a bounding sphere centered at the sensor within which sensor data is to be ignored.
      A negative value will be ignored.
   */
   private double sensor_min_range_;

   public REASensorDataFilterParametersMessage()
   {
      bounding_box_min_ = new geometry_msgs.msg.dds.Point();
      bounding_box_max_ = new geometry_msgs.msg.dds.Point();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += bounding_box_min_.calculateSizeBytes(currentAlignment);
      currentAlignment += bounding_box_max_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sensor_max_range_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sensor_min_range_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      bounding_box_min_.serialize(buffer);
      bounding_box_max_.serialize(buffer);
      buffer.writeDouble(sensor_max_range_);
      buffer.writeDouble(sensor_min_range_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      bounding_box_min_.deserialize(buffer);
      bounding_box_max_.deserialize(buffer);
      sensor_max_range_ = buffer.readDouble();
      sensor_min_range_ = buffer.readDouble();

   }

   @Override
   public void set(REASensorDataFilterParametersMessage from)
   {
      bounding_box_min_.set(from.bounding_box_min_);
      bounding_box_max_.set(from.bounding_box_max_);
      sensor_max_range_ = from.sensor_max_range_;
      sensor_min_range_ = from.sensor_min_range_;

   }

   public geometry_msgs.msg.dds.Point getBoundingBoxMin()
   {
      return bounding_box_min_;
   }

   public geometry_msgs.msg.dds.Point getBoundingBoxMax()
   {
      return bounding_box_max_;
   }

   public double getSensorMaxRange()
   {
      return sensor_max_range_;
   }

   public void setSensorMaxRange(double sensor_max_range_)
   {
      this.sensor_max_range_ = sensor_max_range_;
   }

   public double getSensorMinRange()
   {
      return sensor_min_range_;
   }

   public void setSensorMinRange(double sensor_min_range_)
   {
      this.sensor_min_range_ = sensor_min_range_;
   }


}