/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC robot environment awareness module (REA).
It is destined to host user requests for changing the internal state of REA.
<p>Source (perception_msgs/REAStateRequestMessage):
<pre>{@code
# This message is part of the IHMC robot environment awareness module (REA).
# It is destined to host user requests for changing the internal state of REA.

# When true, REA will temporarily stop collecting pointcloud data until another message requesting it to resume is sent.
# In the case REA was already paused, nothing changes.
# In the case both pause and resume are requested, the pause request is ignored.
bool request_pause false
# When true, REA will resume collecting pointcloud data.
# In the case REA was already collecting data, nothing changes.
# In the case both pause and resume are requested, the pause request is ignored.
bool request_resume false
# When true, REA will clear its internal data collected until now.
# After a clear, REA will start building planar regions from scratch.
# This is useful in the case of noisy data, of if the sensor pose estimation has drifted for instance.
bool request_clear false}</pre>
*/
public class REAStateRequestMessage implements ROS2Message<REAStateRequestMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::REAStateRequestMessage_";

   /**
      When true, REA will temporarily stop collecting pointcloud data until another message requesting it to resume is sent.
      In the case REA was already paused, nothing changes.
      In the case both pause and resume are requested, the pause request is ignored.
   */
   private boolean request_pause_;
   /**
      When true, REA will resume collecting pointcloud data.
      In the case REA was already collecting data, nothing changes.
      In the case both pause and resume are requested, the pause request is ignored.
   */
   private boolean request_resume_;
   /**
      When true, REA will clear its internal data collected until now.
      After a clear, REA will start building planar regions from scratch.
      This is useful in the case of noisy data, of if the sensor pose estimation has drifted for instance.
   */
   private boolean request_clear_;

   public REAStateRequestMessage()
   {
      request_pause_ = (boolean) false;
      request_resume_ = (boolean) false;
      request_clear_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_pause_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_resume_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_clear_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(request_pause_);
      buffer.writeBoolean(request_resume_);
      buffer.writeBoolean(request_clear_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      request_pause_ = buffer.readBoolean();
      request_resume_ = buffer.readBoolean();
      request_clear_ = buffer.readBoolean();

   }

   @Override
   public void set(REAStateRequestMessage from)
   {
      request_pause_ = from.request_pause_;
      request_resume_ = from.request_resume_;
      request_clear_ = from.request_clear_;

   }

   public boolean getRequestPause()
   {
      return request_pause_;
   }

   public void setRequestPause(boolean request_pause_)
   {
      this.request_pause_ = request_pause_;
   }

   public boolean getRequestResume()
   {
      return request_resume_;
   }

   public void setRequestResume(boolean request_resume_)
   {
      this.request_resume_ = request_resume_;
   }

   public boolean getRequestClear()
   {
      return request_clear_;
   }

   public void setRequestClear(boolean request_clear_)
   {
      this.request_clear_ = request_clear_;
   }


}