/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Use this message to request a new point cloud from the stereo camera.
<p>Source (perception_msgs/RequestStereoPointCloudMessage):
<pre>{@code
# Use this message to request a new point cloud from the stereo camera.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id
}</pre>
*/
public class RequestStereoPointCloudMessage implements ROS2Message<RequestStereoPointCloudMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::RequestStereoPointCloudMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;

   public RequestStereoPointCloudMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();

   }

   @Override
   public void set(RequestStereoPointCloudMessage from)
   {
      sequence_id_ = from.sequence_id_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }


}