/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Gives the current state of the complete collection of detectable scene nodes.
Publishing all scene nodes in one messages can simplify synchronization and
reduce the complexity of logic in figuring out when nodes are currently under
consideration.
<p>Source (perception_msgs/SceneGraphMessage):
<pre>{@code
# Gives the current state of the complete collection of detectable scene nodes.
# Publishing all scene nodes in one messages can simplify synchronization and
# reduce the complexity of logic in figuring out when nodes are currently under
# consideration.

byte SCENE_NODE_TYPE=0
byte DETECTABLE_SCENE_NODE_TYPE=1
byte PREDEFINED_RIGID_BODY_NODE_TYPE=2
byte ARUCO_MARKER_NODE_TYPE=3
byte STATIC_RELATIVE_NODE_TYPE=5
byte PRIMITIVE_RIGID_BODY_NODE_TYPE=6
byte YOLO_NODE_TYPE=7
byte FOUNDATION_POSE_NODE_TYPE=8
byte DOOR_NODE_TYPE=9

# Monotonically increasing message ID that matches the CRDTInfo update number
uint64 sequence_id

# The ID to assign to the next instantiated node
uint32 next_id

# A depth first ordered list of types.
byte[<=1000] scene_tree_types

# A depth first ordered list of node indexes.
# The index is of that node in it's respective list for
# it's type.
uint32[<=1000] scene_tree_indices

# Basic scene nodes
perception_msgs/SceneNodeMessage[<=200] scene_nodes

# Detectable scene nodes
perception_msgs/DetectableSceneNodeMessage[<=200] detectable_scene_nodes

# Predefined rigid body scene nodes
perception_msgs/PredefinedRigidBodySceneNodeMessage[<=200] predefined_rigid_body_scene_nodes

# ArUco marker scene nodes
perception_msgs/ArUcoMarkerNodeMessage[<=200] aruco_marker_scene_nodes

# Static relative scene nodes
perception_msgs/StaticRelativeSceneNodeMessage[<=200] static_relative_scene_nodes

# Reshapable rigid body scene nodes
perception_msgs/PrimitiveRigidBodySceneNodeMessage[<=200] primitive_rigid_body_scene_nodes

# YOLO scene nodes
perception_msgs/YOLOv8NodeMessage[<=200] yolo_scene_nodes

# FoundationPose scene nodes
perception_msgs/FoundationPoseNodeMessage[] foundation_pose_scene_nodes

# Door scene nodes
perception_msgs/DoorNodeMessage[<=200] door_scene_nodes}</pre>
*/
public class SceneGraphMessage implements ROS2Message<SceneGraphMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::SceneGraphMessage_";

   public static final byte SCENE_NODE_TYPE = 0;
   public static final byte DETECTABLE_SCENE_NODE_TYPE = 1;
   public static final byte PREDEFINED_RIGID_BODY_NODE_TYPE = 2;
   public static final byte ARUCO_MARKER_NODE_TYPE = 3;
   public static final byte STATIC_RELATIVE_NODE_TYPE = 5;
   public static final byte PRIMITIVE_RIGID_BODY_NODE_TYPE = 6;
   public static final byte YOLO_NODE_TYPE = 7;
   public static final byte FOUNDATION_POSE_NODE_TYPE = 8;
   public static final byte DOOR_NODE_TYPE = 9;
   /**
      Monotonically increasing message ID that matches the CRDTInfo update number
   */
   private long sequence_id_;
   /**
      The ID to assign to the next instantiated node
   */
   private int next_id_;
   /**
      A depth first ordered list of types.
   */
   private final IDLByteSequence scene_tree_types_;
   /**
      A depth first ordered list of node indexes.
      The index is of that node in it's respective list for
      it's type.
   */
   private final IDLIntSequence scene_tree_indices_;
   /**
      Basic scene nodes
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.SceneNodeMessage> scene_nodes_;
   /**
      Detectable scene nodes
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.DetectableSceneNodeMessage> detectable_scene_nodes_;
   /**
      Predefined rigid body scene nodes
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.PredefinedRigidBodySceneNodeMessage> predefined_rigid_body_scene_nodes_;
   /**
      ArUco marker scene nodes
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.ArUcoMarkerNodeMessage> aruco_marker_scene_nodes_;
   /**
      Static relative scene nodes
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.StaticRelativeSceneNodeMessage> static_relative_scene_nodes_;
   /**
      Reshapable rigid body scene nodes
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.PrimitiveRigidBodySceneNodeMessage> primitive_rigid_body_scene_nodes_;
   /**
      YOLO scene nodes
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.YOLOv8NodeMessage> yolo_scene_nodes_;
   /**
      FoundationPose scene nodes
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.FoundationPoseNodeMessage> foundation_pose_scene_nodes_;
   /**
      Door scene nodes
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.DoorNodeMessage> door_scene_nodes_;

   public SceneGraphMessage()
   {
      scene_tree_types_ = new IDLByteSequence(1000);
      scene_tree_indices_ = new IDLIntSequence(1000);
      scene_nodes_ = new IDLObjectSequence<perception_msgs.msg.dds.SceneNodeMessage>(200, perception_msgs.msg.dds.SceneNodeMessage.class);
      detectable_scene_nodes_ = new IDLObjectSequence<perception_msgs.msg.dds.DetectableSceneNodeMessage>(200, perception_msgs.msg.dds.DetectableSceneNodeMessage.class);
      predefined_rigid_body_scene_nodes_ = new IDLObjectSequence<perception_msgs.msg.dds.PredefinedRigidBodySceneNodeMessage>(200, perception_msgs.msg.dds.PredefinedRigidBodySceneNodeMessage.class);
      aruco_marker_scene_nodes_ = new IDLObjectSequence<perception_msgs.msg.dds.ArUcoMarkerNodeMessage>(200, perception_msgs.msg.dds.ArUcoMarkerNodeMessage.class);
      static_relative_scene_nodes_ = new IDLObjectSequence<perception_msgs.msg.dds.StaticRelativeSceneNodeMessage>(200, perception_msgs.msg.dds.StaticRelativeSceneNodeMessage.class);
      primitive_rigid_body_scene_nodes_ = new IDLObjectSequence<perception_msgs.msg.dds.PrimitiveRigidBodySceneNodeMessage>(200, perception_msgs.msg.dds.PrimitiveRigidBodySceneNodeMessage.class);
      yolo_scene_nodes_ = new IDLObjectSequence<perception_msgs.msg.dds.YOLOv8NodeMessage>(200, perception_msgs.msg.dds.YOLOv8NodeMessage.class);
      foundation_pose_scene_nodes_ = new IDLObjectSequence<perception_msgs.msg.dds.FoundationPoseNodeMessage>(perception_msgs.msg.dds.FoundationPoseNodeMessage.class);
      door_scene_nodes_ = new IDLObjectSequence<perception_msgs.msg.dds.DoorNodeMessage>(200, perception_msgs.msg.dds.DoorNodeMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // next_id_
      currentAlignment += scene_tree_types_.calculateSizeBytes(currentAlignment);
      currentAlignment += scene_tree_indices_.calculateSizeBytes(currentAlignment);
      currentAlignment += scene_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += detectable_scene_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += predefined_rigid_body_scene_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += aruco_marker_scene_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += static_relative_scene_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += primitive_rigid_body_scene_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += yolo_scene_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += foundation_pose_scene_nodes_.calculateSizeBytes(currentAlignment);
      currentAlignment += door_scene_nodes_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeInt(next_id_);
      scene_tree_types_.serialize(buffer);
      scene_tree_indices_.serialize(buffer);
      scene_nodes_.serialize(buffer);
      detectable_scene_nodes_.serialize(buffer);
      predefined_rigid_body_scene_nodes_.serialize(buffer);
      aruco_marker_scene_nodes_.serialize(buffer);
      static_relative_scene_nodes_.serialize(buffer);
      primitive_rigid_body_scene_nodes_.serialize(buffer);
      yolo_scene_nodes_.serialize(buffer);
      foundation_pose_scene_nodes_.serialize(buffer);
      door_scene_nodes_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      next_id_ = buffer.readInt();
      scene_tree_types_.deserialize(buffer);
      scene_tree_indices_.deserialize(buffer);
      scene_nodes_.deserialize(buffer);
      detectable_scene_nodes_.deserialize(buffer);
      predefined_rigid_body_scene_nodes_.deserialize(buffer);
      aruco_marker_scene_nodes_.deserialize(buffer);
      static_relative_scene_nodes_.deserialize(buffer);
      primitive_rigid_body_scene_nodes_.deserialize(buffer);
      yolo_scene_nodes_.deserialize(buffer);
      foundation_pose_scene_nodes_.deserialize(buffer);
      door_scene_nodes_.deserialize(buffer);

   }

   @Override
   public void set(SceneGraphMessage from)
   {
      sequence_id_ = from.sequence_id_;
      next_id_ = from.next_id_;
      scene_tree_types_.set(from.scene_tree_types_);
      scene_tree_indices_.set(from.scene_tree_indices_);
      scene_nodes_.set(from.scene_nodes_);
      detectable_scene_nodes_.set(from.detectable_scene_nodes_);
      predefined_rigid_body_scene_nodes_.set(from.predefined_rigid_body_scene_nodes_);
      aruco_marker_scene_nodes_.set(from.aruco_marker_scene_nodes_);
      static_relative_scene_nodes_.set(from.static_relative_scene_nodes_);
      primitive_rigid_body_scene_nodes_.set(from.primitive_rigid_body_scene_nodes_);
      yolo_scene_nodes_.set(from.yolo_scene_nodes_);
      foundation_pose_scene_nodes_.set(from.foundation_pose_scene_nodes_);
      door_scene_nodes_.set(from.door_scene_nodes_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public int getNextId()
   {
      return next_id_;
   }

   public void setNextId(int next_id_)
   {
      this.next_id_ = next_id_;
   }

   public IDLByteSequence getSceneTreeTypes()
   {
      return scene_tree_types_;
   }

   public IDLIntSequence getSceneTreeIndices()
   {
      return scene_tree_indices_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.SceneNodeMessage> getSceneNodes()
   {
      return scene_nodes_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.DetectableSceneNodeMessage> getDetectableSceneNodes()
   {
      return detectable_scene_nodes_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.PredefinedRigidBodySceneNodeMessage> getPredefinedRigidBodySceneNodes()
   {
      return predefined_rigid_body_scene_nodes_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.ArUcoMarkerNodeMessage> getArucoMarkerSceneNodes()
   {
      return aruco_marker_scene_nodes_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.StaticRelativeSceneNodeMessage> getStaticRelativeSceneNodes()
   {
      return static_relative_scene_nodes_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.PrimitiveRigidBodySceneNodeMessage> getPrimitiveRigidBodySceneNodes()
   {
      return primitive_rigid_body_scene_nodes_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.YOLOv8NodeMessage> getYoloSceneNodes()
   {
      return yolo_scene_nodes_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.FoundationPoseNodeMessage> getFoundationPoseSceneNodes()
   {
      return foundation_pose_scene_nodes_;
   }

   public IDLObjectSequence<perception_msgs.msg.dds.DoorNodeMessage> getDoorSceneNodes()
   {
      return door_scene_nodes_;
   }


}