/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
The base scene node information
The topic name identifies the node.
<p>Source (perception_msgs/SceneNodeMessage):
<pre>{@code
# The base scene node information
# The topic name identifies the node.

# The ID of the node
uint32 id

# The name of the scene node
string name

# A mechanism for confirming and ending a freeze early
ihmc_common_msgs/ConfirmableRequestMessage confirmable_request

# Transform of the node's frame to world frame
controller_msgs/RigidBodyTransformMessage transform_to_world

# Number of child nodes; used for serialization
uint16 number_of_children}</pre>
*/
public class SceneNodeMessage implements ROS2Message<SceneNodeMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::SceneNodeMessage_";

   /**
      The ID of the node
   */
   private int id_;
   /**
      The name of the scene node
   */
   private final StringBuilder name_;
   /**
      A mechanism for confirming and ending a freeze early
   */
   private final ihmc_common_msgs.msg.dds.ConfirmableRequestMessage confirmable_request_;
   /**
      Transform of the node's frame to world frame
   */
   private final controller_msgs.msg.dds.RigidBodyTransformMessage transform_to_world_;
   /**
      Number of child nodes; used for serialization
   */
   private short number_of_children_;

   public SceneNodeMessage()
   {
      name_ = new StringBuilder();
      confirmable_request_ = new ihmc_common_msgs.msg.dds.ConfirmableRequestMessage();
      transform_to_world_ = new controller_msgs.msg.dds.RigidBodyTransformMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += confirmable_request_.calculateSizeBytes(currentAlignment);
      currentAlignment += transform_to_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // number_of_children_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(id_);
      buffer.writeString(name_);
      confirmable_request_.serialize(buffer);
      transform_to_world_.serialize(buffer);
      buffer.writeShort(number_of_children_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      id_ = buffer.readInt();
      buffer.readString(name_);
      confirmable_request_.deserialize(buffer);
      transform_to_world_.deserialize(buffer);
      number_of_children_ = buffer.readShort();

   }

   @Override
   public void set(SceneNodeMessage from)
   {
      id_ = from.id_;
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      confirmable_request_.set(from.confirmable_request_);
      transform_to_world_.set(from.transform_to_world_);
      number_of_children_ = from.number_of_children_;

   }

   public int getId()
   {
      return id_;
   }

   public void setId(int id_)
   {
      this.id_ = id_;
   }

   public StringBuilder getName()
   {
      return name_;
   }

   public ihmc_common_msgs.msg.dds.ConfirmableRequestMessage getConfirmableRequest()
   {
      return confirmable_request_;
   }

   public controller_msgs.msg.dds.RigidBodyTransformMessage getTransformToWorld()
   {
      return transform_to_world_;
   }

   public short getNumberOfChildren()
   {
      return number_of_children_;
   }

   public void setNumberOfChildren(short number_of_children_)
   {
      this.number_of_children_ = number_of_children_;
   }


}