/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/SimulatedLidarScanPacket):
<pre>{@code

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

float32[] ranges
int32 sensor_id
LidarScanParametersMessage lidar_scan_parameters}</pre>
*/
public class SimulatedLidarScanPacket implements ROS2Message<SimulatedLidarScanPacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::SimulatedLidarScanPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final IDLFloatSequence ranges_;
   private int sensor_id_;
   private final perception_msgs.msg.dds.LidarScanParametersMessage lidar_scan_parameters_;

   public SimulatedLidarScanPacket()
   {
      ranges_ = new IDLFloatSequence();
      lidar_scan_parameters_ = new perception_msgs.msg.dds.LidarScanParametersMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += ranges_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // sensor_id_
      currentAlignment += lidar_scan_parameters_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      ranges_.serialize(buffer);
      buffer.writeInt(sensor_id_);
      lidar_scan_parameters_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      ranges_.deserialize(buffer);
      sensor_id_ = buffer.readInt();
      lidar_scan_parameters_.deserialize(buffer);

   }

   @Override
   public void set(SimulatedLidarScanPacket from)
   {
      sequence_id_ = from.sequence_id_;
      ranges_.set(from.ranges_);
      sensor_id_ = from.sensor_id_;
      lidar_scan_parameters_.set(from.lidar_scan_parameters_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLFloatSequence getRanges()
   {
      return ranges_;
   }

   public int getSensorId()
   {
      return sensor_id_;
   }

   public void setSensorId(int sensor_id_)
   {
      this.sensor_id_ = sensor_id_;
   }

   public perception_msgs.msg.dds.LidarScanParametersMessage getLidarScanParameters()
   {
      return lidar_scan_parameters_;
   }


}