/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A static relative heuristic scene node
The topic name identifies the node.
<p>Source (perception_msgs/StaticRelativeSceneNodeMessage):
<pre>{@code
# A static relative heuristic scene node
# The topic name identifies the node.

# The predefined rigid body information that this extends
perception_msgs/PredefinedRigidBodySceneNodeMessage predefined_rigid_body_scene_node

# Distance to robot to disable tracking.
# Used for automatically disabling tracking for static relative objects.
float32 distance_to_disable_tracking

# Current distance to robot.
# Used for automatically disabling tracking for static relative objects.
float32 current_distance_to_robot}</pre>
*/
public class StaticRelativeSceneNodeMessage implements ROS2Message<StaticRelativeSceneNodeMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::StaticRelativeSceneNodeMessage_";

   /**
      The predefined rigid body information that this extends
   */
   private final perception_msgs.msg.dds.PredefinedRigidBodySceneNodeMessage predefined_rigid_body_scene_node_;
   /**
      Distance to robot to disable tracking.
      Used for automatically disabling tracking for static relative objects.
   */
   private float distance_to_disable_tracking_;
   /**
      Current distance to robot.
      Used for automatically disabling tracking for static relative objects.
   */
   private float current_distance_to_robot_;

   public StaticRelativeSceneNodeMessage()
   {
      predefined_rigid_body_scene_node_ = new perception_msgs.msg.dds.PredefinedRigidBodySceneNodeMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += predefined_rigid_body_scene_node_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // distance_to_disable_tracking_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // current_distance_to_robot_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      predefined_rigid_body_scene_node_.serialize(buffer);
      buffer.writeFloat(distance_to_disable_tracking_);
      buffer.writeFloat(current_distance_to_robot_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      predefined_rigid_body_scene_node_.deserialize(buffer);
      distance_to_disable_tracking_ = buffer.readFloat();
      current_distance_to_robot_ = buffer.readFloat();

   }

   @Override
   public void set(StaticRelativeSceneNodeMessage from)
   {
      predefined_rigid_body_scene_node_.set(from.predefined_rigid_body_scene_node_);
      distance_to_disable_tracking_ = from.distance_to_disable_tracking_;
      current_distance_to_robot_ = from.current_distance_to_robot_;

   }

   public perception_msgs.msg.dds.PredefinedRigidBodySceneNodeMessage getPredefinedRigidBodySceneNode()
   {
      return predefined_rigid_body_scene_node_;
   }

   public float getDistanceToDisableTracking()
   {
      return distance_to_disable_tracking_;
   }

   public void setDistanceToDisableTracking(float distance_to_disable_tracking_)
   {
      this.distance_to_disable_tracking_ = distance_to_disable_tracking_;
   }

   public float getCurrentDistanceToRobot()
   {
      return current_distance_to_robot_;
   }

   public void setCurrentDistanceToRobot(float current_distance_to_robot_)
   {
      this.current_distance_to_robot_ = current_distance_to_robot_;
   }


}