/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC humanoid behavior module.
<p>Source (perception_msgs/ValveLocationPacket):
<pre>{@code
# This message is part of the IHMC humanoid behavior module.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

geometry_msgs/Pose valve_pose_in_world
float64 valve_radius}</pre>
*/
public class ValveLocationPacket implements ROS2Message<ValveLocationPacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::ValveLocationPacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final geometry_msgs.msg.dds.Pose valve_pose_in_world_;
   private double valve_radius_;

   public ValveLocationPacket()
   {
      valve_pose_in_world_ = new geometry_msgs.msg.dds.Pose();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += valve_pose_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // valve_radius_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      valve_pose_in_world_.serialize(buffer);
      buffer.writeDouble(valve_radius_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      valve_pose_in_world_.deserialize(buffer);
      valve_radius_ = buffer.readDouble();

   }

   @Override
   public void set(ValveLocationPacket from)
   {
      sequence_id_ = from.sequence_id_;
      valve_pose_in_world_.set(from.valve_pose_in_world_);
      valve_radius_ = from.valve_radius_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public geometry_msgs.msg.dds.Pose getValvePoseInWorld()
   {
      return valve_pose_in_world_;
   }

   public double getValveRadius()
   {
      return valve_radius_;
   }

   public void setValveRadius(double valve_radius_)
   {
      this.valve_radius_ = valve_radius_;
   }


}