/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Old message used for the VRC? Needs to be revised, maybe deleted?
<p>Source (perception_msgs/VehiclePosePacket):
<pre>{@code
# Old message used for the VRC? Needs to be revised, maybe deleted?

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

geometry_msgs/Point position
geometry_msgs/Quaternion orientation
int32 index 0}</pre>
*/
public class VehiclePosePacket implements ROS2Message<VehiclePosePacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::VehiclePosePacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final geometry_msgs.msg.dds.Point position_;
   private final geometry_msgs.msg.dds.Quaternion orientation_;
   private int index_;

   public VehiclePosePacket()
   {
      position_ = new geometry_msgs.msg.dds.Point();
      orientation_ = new geometry_msgs.msg.dds.Quaternion();
      index_ = (int) 0;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += position_.calculateSizeBytes(currentAlignment);
      currentAlignment += orientation_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // index_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      position_.serialize(buffer);
      orientation_.serialize(buffer);
      buffer.writeInt(index_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      position_.deserialize(buffer);
      orientation_.deserialize(buffer);
      index_ = buffer.readInt();

   }

   @Override
   public void set(VehiclePosePacket from)
   {
      sequence_id_ = from.sequence_id_;
      position_.set(from.position_);
      orientation_.set(from.orientation_);
      index_ = from.index_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public geometry_msgs.msg.dds.Point getPosition()
   {
      return position_;
   }

   public geometry_msgs.msg.dds.Quaternion getOrientation()
   {
      return orientation_;
   }

   public int getIndex()
   {
      return index_;
   }

   public void setIndex(int index_)
   {
      this.index_ = index_;
   }


}