/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/VideoPacket):
<pre>{@code

byte VIDEO_SOURCE_MULTISENSE_LEFT_EYE = 0
byte VIDEO_SOURCE_MULTISENSE_RIGHT_EYE = 1
byte VIDEO_SOURCE_FISHEYE_LEFT = 2
byte VIDEO_SOURCE_FISHEYE_RIGHT = 3
byte VIDEO_SOURCE_CV_THRESHOLD = 4
byte VIDEO_SOURCE_IMAGE_PROCESSING_BEHAVIOR = 5
byte VIDEO_SOURCE_AWARE_FACE_TRACKER = 6

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte video_source 255
int64 timestamp
byte[<=2000000] data
uint16 image_width
uint16 image_height
geometry_msgs/Point position
geometry_msgs/Quaternion orientation
IntrinsicParametersMessage intrinsic_parameters}</pre>
*/
public class VideoPacket implements ROS2Message<VideoPacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::VideoPacket_";

   public static final byte VIDEO_SOURCE_MULTISENSE_LEFT_EYE = 0;
   public static final byte VIDEO_SOURCE_MULTISENSE_RIGHT_EYE = 1;
   public static final byte VIDEO_SOURCE_FISHEYE_LEFT = 2;
   public static final byte VIDEO_SOURCE_FISHEYE_RIGHT = 3;
   public static final byte VIDEO_SOURCE_CV_THRESHOLD = 4;
   public static final byte VIDEO_SOURCE_IMAGE_PROCESSING_BEHAVIOR = 5;
   public static final byte VIDEO_SOURCE_AWARE_FACE_TRACKER = 6;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private byte video_source_;
   private long timestamp_;
   private final IDLByteSequence data_;
   private short image_width_;
   private short image_height_;
   private final geometry_msgs.msg.dds.Point position_;
   private final geometry_msgs.msg.dds.Quaternion orientation_;
   private final perception_msgs.msg.dds.IntrinsicParametersMessage intrinsic_parameters_;

   public VideoPacket()
   {
      video_source_ = (byte) 255;
      data_ = new IDLByteSequence(2000000);
      position_ = new geometry_msgs.msg.dds.Point();
      orientation_ = new geometry_msgs.msg.dds.Quaternion();
      intrinsic_parameters_ = new perception_msgs.msg.dds.IntrinsicParametersMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // video_source_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // timestamp_
      currentAlignment += data_.calculateSizeBytes(currentAlignment);
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // image_width_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // image_height_
      currentAlignment += position_.calculateSizeBytes(currentAlignment);
      currentAlignment += orientation_.calculateSizeBytes(currentAlignment);
      currentAlignment += intrinsic_parameters_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(video_source_);
      buffer.writeLong(timestamp_);
      data_.serialize(buffer);
      buffer.writeShort(image_width_);
      buffer.writeShort(image_height_);
      position_.serialize(buffer);
      orientation_.serialize(buffer);
      intrinsic_parameters_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      video_source_ = buffer.readByte();
      timestamp_ = buffer.readLong();
      data_.deserialize(buffer);
      image_width_ = buffer.readShort();
      image_height_ = buffer.readShort();
      position_.deserialize(buffer);
      orientation_.deserialize(buffer);
      intrinsic_parameters_.deserialize(buffer);

   }

   @Override
   public void set(VideoPacket from)
   {
      sequence_id_ = from.sequence_id_;
      video_source_ = from.video_source_;
      timestamp_ = from.timestamp_;
      data_.set(from.data_);
      image_width_ = from.image_width_;
      image_height_ = from.image_height_;
      position_.set(from.position_);
      orientation_.set(from.orientation_);
      intrinsic_parameters_.set(from.intrinsic_parameters_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getVideoSource()
   {
      return video_source_;
   }

   public void setVideoSource(byte video_source_)
   {
      this.video_source_ = video_source_;
   }

   public long getTimestamp()
   {
      return timestamp_;
   }

   public void setTimestamp(long timestamp_)
   {
      this.timestamp_ = timestamp_;
   }

   public IDLByteSequence getData()
   {
      return data_;
   }

   public short getImageWidth()
   {
      return image_width_;
   }

   public void setImageWidth(short image_width_)
   {
      this.image_width_ = image_width_;
   }

   public short getImageHeight()
   {
      return image_height_;
   }

   public void setImageHeight(short image_height_)
   {
      this.image_height_ = image_height_;
   }

   public geometry_msgs.msg.dds.Point getPosition()
   {
      return position_;
   }

   public geometry_msgs.msg.dds.Quaternion getOrientation()
   {
      return orientation_;
   }

   public perception_msgs.msg.dds.IntrinsicParametersMessage getIntrinsicParameters()
   {
      return intrinsic_parameters_;
   }


}