/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC humanoid behavior module.
<p>Source (perception_msgs/WallPosePacket):
<pre>{@code
# This message is part of the IHMC humanoid behavior module.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

float64 cutting_radius 0.20
geometry_msgs/Point center_position
geometry_msgs/Quaternion center_orientation}</pre>
*/
public class WallPosePacket implements ROS2Message<WallPosePacket>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::WallPosePacket_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private double cutting_radius_;
   private final geometry_msgs.msg.dds.Point center_position_;
   private final geometry_msgs.msg.dds.Quaternion center_orientation_;

   public WallPosePacket()
   {
      cutting_radius_ = (double) 0.20;
      center_position_ = new geometry_msgs.msg.dds.Point();
      center_orientation_ = new geometry_msgs.msg.dds.Quaternion();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // cutting_radius_
      currentAlignment += center_position_.calculateSizeBytes(currentAlignment);
      currentAlignment += center_orientation_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeDouble(cutting_radius_);
      center_position_.serialize(buffer);
      center_orientation_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      cutting_radius_ = buffer.readDouble();
      center_position_.deserialize(buffer);
      center_orientation_.deserialize(buffer);

   }

   @Override
   public void set(WallPosePacket from)
   {
      sequence_id_ = from.sequence_id_;
      cutting_radius_ = from.cutting_radius_;
      center_position_.set(from.center_position_);
      center_orientation_.set(from.center_orientation_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public double getCuttingRadius()
   {
      return cutting_radius_;
   }

   public void setCuttingRadius(double cutting_radius_)
   {
      this.cutting_radius_ = cutting_radius_;
   }

   public geometry_msgs.msg.dds.Point getCenterPosition()
   {
      return center_position_;
   }

   public geometry_msgs.msg.dds.Quaternion getCenterOrientation()
   {
      return center_orientation_;
   }


}