/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Parameters for running YOLOv8
<p>Source (perception_msgs/YOLOv8ParametersMessage):
<pre>{@code
# TODO: Having these parameter/settings messages kinda sucks.
# Should try to get a better system.

# Parameters for running YOLOv8

# Confidence required to consider a mask a valid detection
float32 confidence_threshold

float32 non_maximum_suppression_threshold

float32 segmentation_threshold

# How much to shrink the object mask. Higher value = more shrinkage
int32 erosion_kernel_radius

float32 outlier_threshold

# TODO: Add back?
# List of YOLOv8DetectionClass values that YOLO should detect
# byte[<=100] target_detection_classes}</pre>
*/
public class YOLOv8ParametersMessage implements ROS2Message<YOLOv8ParametersMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::YOLOv8ParametersMessage_";

   /**
      Confidence required to consider a mask a valid detection
   */
   private float confidence_threshold_;
   private float non_maximum_suppression_threshold_;
   private float segmentation_threshold_;
   /**
      How much to shrink the object mask. Higher value = more shrinkage
   */
   private int erosion_kernel_radius_;
   private float outlier_threshold_;

   public YOLOv8ParametersMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // confidence_threshold_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // non_maximum_suppression_threshold_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // segmentation_threshold_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // erosion_kernel_radius_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // outlier_threshold_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeFloat(confidence_threshold_);
      buffer.writeFloat(non_maximum_suppression_threshold_);
      buffer.writeFloat(segmentation_threshold_);
      buffer.writeInt(erosion_kernel_radius_);
      buffer.writeFloat(outlier_threshold_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      confidence_threshold_ = buffer.readFloat();
      non_maximum_suppression_threshold_ = buffer.readFloat();
      segmentation_threshold_ = buffer.readFloat();
      erosion_kernel_radius_ = buffer.readInt();
      outlier_threshold_ = buffer.readFloat();

   }

   @Override
   public void set(YOLOv8ParametersMessage from)
   {
      confidence_threshold_ = from.confidence_threshold_;
      non_maximum_suppression_threshold_ = from.non_maximum_suppression_threshold_;
      segmentation_threshold_ = from.segmentation_threshold_;
      erosion_kernel_radius_ = from.erosion_kernel_radius_;
      outlier_threshold_ = from.outlier_threshold_;

   }

   public float getConfidenceThreshold()
   {
      return confidence_threshold_;
   }

   public void setConfidenceThreshold(float confidence_threshold_)
   {
      this.confidence_threshold_ = confidence_threshold_;
   }

   public float getNonMaximumSuppressionThreshold()
   {
      return non_maximum_suppression_threshold_;
   }

   public void setNonMaximumSuppressionThreshold(float non_maximum_suppression_threshold_)
   {
      this.non_maximum_suppression_threshold_ = non_maximum_suppression_threshold_;
   }

   public float getSegmentationThreshold()
   {
      return segmentation_threshold_;
   }

   public void setSegmentationThreshold(float segmentation_threshold_)
   {
      this.segmentation_threshold_ = segmentation_threshold_;
   }

   public int getErosionKernelRadius()
   {
      return erosion_kernel_radius_;
   }

   public void setErosionKernelRadius(int erosion_kernel_radius_)
   {
      this.erosion_kernel_radius_ = erosion_kernel_radius_;
   }

   public float getOutlierThreshold()
   {
      return outlier_threshold_;
   }

   public void setOutlierThreshold(float outlier_threshold_)
   {
      this.outlier_threshold_ = outlier_threshold_;
   }


}