/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package system_monitor_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (system_monitor_msgs/SystemServiceStatusMessage):
<pre>{@code
# The name of the systemd service
string service_name

# The status from systemctl status <service_name>
string status

# If the log_data is complete (a full log)
bool refresh

# log_data contains packed system log strings. It may
# be empty most of the time if there are no new log lines
# generated by the service
byte[<=25000000] log_data
}</pre>
*/
public class SystemServiceStatusMessage implements ROS2Message<SystemServiceStatusMessage>
{
   public static final java.lang.String name = "system_monitor_msgs::msg::dds_::SystemServiceStatusMessage_";

   /**
      The name of the systemd service
   */
   private final StringBuilder service_name_;
   /**
      The status from systemctl status <service_name>
   */
   private final StringBuilder status_;
   /**
      If the log_data is complete (a full log)
   */
   private boolean refresh_;
   /**
      log_data contains packed system log strings. It may
      be empty most of the time if there are no new log lines
      generated by the service
   */
   private final IDLByteSequence log_data_;

   public SystemServiceStatusMessage()
   {
      service_name_ = new StringBuilder();
      status_ = new StringBuilder();
      refresh_ = (boolean) false;
      log_data_ = new IDLByteSequence(25000000);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * service_name_.length()) + 1; // service_name_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * status_.length()) + 1; // status_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // refresh_
      currentAlignment += log_data_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(service_name_);
      buffer.writeString(status_);
      buffer.writeBoolean(refresh_);
      log_data_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(service_name_);
      buffer.readString(status_);
      refresh_ = buffer.readBoolean();
      log_data_.deserialize(buffer);

   }

   @Override
   public void set(SystemServiceStatusMessage from)
   {
      service_name_.delete(0, service_name_.length());
      service_name_.insert(0, from.service_name_);
      status_.delete(0, status_.length());
      status_.insert(0, from.status_);
      refresh_ = from.refresh_;
      log_data_.set(from.log_data_);

   }

   public StringBuilder getServiceName()
   {
      return service_name_;
   }

   public StringBuilder getStatus()
   {
      return status_;
   }

   public boolean getRefresh()
   {
      return refresh_;
   }

   public void setRefresh(boolean refresh_)
   {
      this.refresh_ = refresh_;
   }

   public IDLByteSequence getLogData()
   {
      return log_data_;
   }


}