/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package system_monitor_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (system_monitor_msgs/SystemAvailableMessage):
<pre>{@code
# The hostname of the system
# Equivalent of running `hostname` at the shell
string hostname

# A random ID for the topic name for messages from this machine
# We do not use the hostname because we don't want to assume the hostname is normalized
# to the format of topic names (i.e. hostnames might contain spaces, end with numbers, etc)
string instance_id
}</pre>
*/
public class SystemAvailableMessage implements ROS2Message<SystemAvailableMessage>
{
   public static final java.lang.String name = "system_monitor_msgs::msg::dds_::SystemAvailableMessage_";

   /**
      The hostname of the system
      Equivalent of running `hostname` at the shell
   */
   private final StringBuilder hostname_;
   /**
      A random ID for the topic name for messages from this machine
      We do not use the hostname because we don't want to assume the hostname is normalized
      to the format of topic names (i.e. hostnames might contain spaces, end with numbers, etc)
   */
   private final StringBuilder instance_id_;

   public SystemAvailableMessage()
   {
      hostname_ = new StringBuilder();
      instance_id_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * hostname_.length()) + 1; // hostname_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * instance_id_.length()) + 1; // instance_id_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(hostname_);
      buffer.writeString(instance_id_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(hostname_);
      buffer.readString(instance_id_);

   }

   @Override
   public void set(SystemAvailableMessage from)
   {
      hostname_.delete(0, hostname_.length());
      hostname_.insert(0, from.hostname_);
      instance_id_.delete(0, instance_id_.length());
      instance_id_.insert(0, from.instance_id_);

   }

   public StringBuilder getHostname()
   {
      return hostname_;
   }

   public StringBuilder getInstanceId()
   {
      return instance_id_;
   }


}