/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package system_monitor_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (system_monitor_msgs/SystemServiceLogRefreshMessage):
<pre>{@code
# The name of the systemd service
string service_name
}</pre>
*/
public class SystemServiceLogRefreshMessage implements ROS2Message<SystemServiceLogRefreshMessage>
{
   public static final java.lang.String name = "system_monitor_msgs::msg::dds_::SystemServiceLogRefreshMessage_";

   /**
      The name of the systemd service
   */
   private final StringBuilder service_name_;

   public SystemServiceLogRefreshMessage()
   {
      service_name_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * service_name_.length()) + 1; // service_name_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(service_name_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(service_name_);

   }

   @Override
   public void set(SystemServiceLogRefreshMessage from)
   {
      service_name_.delete(0, service_name_.length());
      service_name_.insert(0, from.service_name_);

   }

   public StringBuilder getServiceName()
   {
      return service_name_;
   }


}