/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC humanoid behavior module.
<p>Source (toolbox_msgs/BehaviorStatusPacket):
<pre>{@code
# This message is part of the IHMC humanoid behavior module.

byte NO_BEHAVIOR_RUNNING = 0
byte BEHAVIOR_RUNNING = 1
byte BEHAVIOR_PAUSED = 2
byte BEHAVIOR_FINISHED_FAILED = 3
byte BEHAVIOR_FINISHED_SUCCESS = 4

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte current_behavior_status 255

# Field default value 255
int8 humanoid_behavior_type}</pre>
*/
public class BehaviorStatusPacket implements ROS2Message<BehaviorStatusPacket>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::BehaviorStatusPacket_";

   public static final byte NO_BEHAVIOR_RUNNING = 0;
   public static final byte BEHAVIOR_RUNNING = 1;
   public static final byte BEHAVIOR_PAUSED = 2;
   public static final byte BEHAVIOR_FINISHED_FAILED = 3;
   public static final byte BEHAVIOR_FINISHED_SUCCESS = 4;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private byte current_behavior_status_;
   /**
      Field default value 255
   */
   private byte humanoid_behavior_type_;

   public BehaviorStatusPacket()
   {
      current_behavior_status_ = (byte) 255;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // current_behavior_status_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // humanoid_behavior_type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(current_behavior_status_);
      buffer.writeByte(humanoid_behavior_type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      current_behavior_status_ = buffer.readByte();
      humanoid_behavior_type_ = buffer.readByte();

   }

   @Override
   public void set(BehaviorStatusPacket from)
   {
      sequence_id_ = from.sequence_id_;
      current_behavior_status_ = from.current_behavior_status_;
      humanoid_behavior_type_ = from.humanoid_behavior_type_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getCurrentBehaviorStatus()
   {
      return current_behavior_status_;
   }

   public void setCurrentBehaviorStatus(byte current_behavior_status_)
   {
      this.current_behavior_status_ = current_behavior_status_;
   }

   public byte getHumanoidBehaviorType()
   {
      return humanoid_behavior_type_;
   }

   public void setHumanoidBehaviorType(byte humanoid_behavior_type_)
   {
      this.humanoid_behavior_type_ = humanoid_behavior_type_;
   }


}