/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC humanoid behavior module.
<p>Source (toolbox_msgs/BehaviorControlModePacket):
<pre>{@code
# This message is part of the IHMC humanoid behavior module.

byte STOP = 0
byte PAUSE = 1
byte RESUME = 2

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte behavior_control_mode_enum_request 255}</pre>
*/
public class BehaviorControlModePacket implements ROS2Message<BehaviorControlModePacket>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::BehaviorControlModePacket_";

   public static final byte STOP = 0;
   public static final byte PAUSE = 1;
   public static final byte RESUME = 2;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private byte behavior_control_mode_enum_request_;

   public BehaviorControlModePacket()
   {
      behavior_control_mode_enum_request_ = (byte) 255;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // behavior_control_mode_enum_request_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(behavior_control_mode_enum_request_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      behavior_control_mode_enum_request_ = buffer.readByte();

   }

   @Override
   public void set(BehaviorControlModePacket from)
   {
      sequence_id_ = from.sequence_id_;
      behavior_control_mode_enum_request_ = from.behavior_control_mode_enum_request_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getBehaviorControlModeEnumRequest()
   {
      return behavior_control_mode_enum_request_;
   }

   public void setBehaviorControlModeEnumRequest(byte behavior_control_mode_enum_request_)
   {
      this.behavior_control_mode_enum_request_ = behavior_control_mode_enum_request_;
   }


}