/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (toolbox_msgs/FootstepPlannerRejectionReasonMessage):
<pre>{@code
# Reason ordinal
uint32 reason

# Rejection percentage
float32 rejection_percentage}</pre>
*/
public class FootstepPlannerRejectionReasonMessage implements ROS2Message<FootstepPlannerRejectionReasonMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::FootstepPlannerRejectionReasonMessage_";

   /**
      Reason ordinal
   */
   private int reason_;
   /**
      Rejection percentage
   */
   private float rejection_percentage_;

   public FootstepPlannerRejectionReasonMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // reason_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // rejection_percentage_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(reason_);
      buffer.writeFloat(rejection_percentage_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      reason_ = buffer.readInt();
      rejection_percentage_ = buffer.readFloat();

   }

   @Override
   public void set(FootstepPlannerRejectionReasonMessage from)
   {
      reason_ = from.reason_;
      rejection_percentage_ = from.rejection_percentage_;

   }

   public int getReason()
   {
      return reason_;
   }

   public void setReason(int reason_)
   {
      this.reason_ = reason_;
   }

   public float getRejectionPercentage()
   {
      return rejection_percentage_;
   }

   public void setRejectionPercentage(float rejection_percentage_)
   {
      this.rejection_percentage_ = rejection_percentage_;
   }


}