/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC footstep planning module.
This message is sent from the planner in order to visualize and debug planner progress
<p>Source (toolbox_msgs/FootstepPlannerCellMessage):
<pre>{@code
# This message is part of the IHMC footstep planning module.
# This message is sent from the planner in order to visualize and debug planner progress

# X index of the cell. See us.ihmc.footstepPlanning.graphSearch.graph.DiscreteFootstep for more information
int32 x_index
# Y index of the cell. See us.ihmc.footstepPlanning.graphSearch.graph.DiscreteFootstep for more information
int32 y_index
}</pre>
*/
public class FootstepPlannerCellMessage implements ROS2Message<FootstepPlannerCellMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::FootstepPlannerCellMessage_";

   /**
      X index of the cell. See us.ihmc.footstepPlanning.graphSearch.graph.DiscreteFootstep for more information
   */
   private int x_index_;
   /**
      Y index of the cell. See us.ihmc.footstepPlanning.graphSearch.graph.DiscreteFootstep for more information
   */
   private int y_index_;

   public FootstepPlannerCellMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // x_index_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // y_index_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(x_index_);
      buffer.writeInt(y_index_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      x_index_ = buffer.readInt();
      y_index_ = buffer.readInt();

   }

   @Override
   public void set(FootstepPlannerCellMessage from)
   {
      x_index_ = from.x_index_;
      y_index_ = from.y_index_;

   }

   public int getXIndex()
   {
      return x_index_;
   }

   public void setXIndex(int x_index_)
   {
      this.x_index_ = x_index_;
   }

   public int getYIndex()
   {
      return y_index_;
   }

   public void setYIndex(int y_index_)
   {
      this.y_index_ = y_index_;
   }


}