/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC height quad tree module
<p>Source (toolbox_msgs/HeightQuadTreeToolboxRequestMessage):
<pre>{@code
# This message is part of the IHMC height quad tree module

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

bool request_clear_quad_tree
bool request_quad_tree_update}</pre>
*/
public class HeightQuadTreeToolboxRequestMessage implements ROS2Message<HeightQuadTreeToolboxRequestMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::HeightQuadTreeToolboxRequestMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private boolean request_clear_quad_tree_;
   private boolean request_quad_tree_update_;

   public HeightQuadTreeToolboxRequestMessage()
   {
      request_clear_quad_tree_ = (boolean) false;
      request_quad_tree_update_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_clear_quad_tree_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_quad_tree_update_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(request_clear_quad_tree_);
      buffer.writeBoolean(request_quad_tree_update_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      request_clear_quad_tree_ = buffer.readBoolean();
      request_quad_tree_update_ = buffer.readBoolean();

   }

   @Override
   public void set(HeightQuadTreeToolboxRequestMessage from)
   {
      sequence_id_ = from.sequence_id_;
      request_clear_quad_tree_ = from.request_clear_quad_tree_;
      request_quad_tree_update_ = from.request_quad_tree_update_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getRequestClearQuadTree()
   {
      return request_clear_quad_tree_;
   }

   public void setRequestClearQuadTree(boolean request_clear_quad_tree_)
   {
      this.request_clear_quad_tree_ = request_clear_quad_tree_;
   }

   public boolean getRequestQuadTreeUpdate()
   {
      return request_quad_tree_update_;
   }

   public void setRequestQuadTreeUpdate(boolean request_quad_tree_update_)
   {
      this.request_quad_tree_update_ = request_quad_tree_update_;
   }


}