/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC whole-body inverse kinematics module.
This message allows to pack and send as a single message a collection of inputs for the kinematics toolbox.
<p>Source (toolbox_msgs/KinematicsToolboxInputCollectionMessage):
<pre>{@code
# This message is part of the IHMC whole-body inverse kinematics module.
# This message allows to pack and send as a single message a collection of inputs for the kinematics toolbox.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Inputs for controlling the center of mass position.
KinematicsToolboxCenterOfMassMessage[<=3] center_of_mass_inputs
# Inputs for controlling rigid-bodies.
KinematicsToolboxRigidBodyMessage[<=20] rigid_body_inputs
# Inputs for controlling 1-DoF joints.
KinematicsToolboxOneDoFJointMessage[<=20] joint_inputs
# Input for overriding the default support polygon with a custom one.
KinematicsToolboxSupportRegionMessage[<=1] contact_state_input}</pre>
*/
public class KinematicsToolboxInputCollectionMessage implements ROS2Message<KinematicsToolboxInputCollectionMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::KinematicsToolboxInputCollectionMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Inputs for controlling the center of mass position.
   */
   private final IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxCenterOfMassMessage> center_of_mass_inputs_;
   /**
      Inputs for controlling rigid-bodies.
   */
   private final IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxRigidBodyMessage> rigid_body_inputs_;
   /**
      Inputs for controlling 1-DoF joints.
   */
   private final IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxOneDoFJointMessage> joint_inputs_;
   /**
      Input for overriding the default support polygon with a custom one.
   */
   private final IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxSupportRegionMessage> contact_state_input_;

   public KinematicsToolboxInputCollectionMessage()
   {
      center_of_mass_inputs_ = new IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxCenterOfMassMessage>(3, toolbox_msgs.msg.dds.KinematicsToolboxCenterOfMassMessage.class);
      rigid_body_inputs_ = new IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxRigidBodyMessage>(20, toolbox_msgs.msg.dds.KinematicsToolboxRigidBodyMessage.class);
      joint_inputs_ = new IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxOneDoFJointMessage>(20, toolbox_msgs.msg.dds.KinematicsToolboxOneDoFJointMessage.class);
      contact_state_input_ = new IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxSupportRegionMessage>(1, toolbox_msgs.msg.dds.KinematicsToolboxSupportRegionMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += center_of_mass_inputs_.calculateSizeBytes(currentAlignment);
      currentAlignment += rigid_body_inputs_.calculateSizeBytes(currentAlignment);
      currentAlignment += joint_inputs_.calculateSizeBytes(currentAlignment);
      currentAlignment += contact_state_input_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      center_of_mass_inputs_.serialize(buffer);
      rigid_body_inputs_.serialize(buffer);
      joint_inputs_.serialize(buffer);
      contact_state_input_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      center_of_mass_inputs_.deserialize(buffer);
      rigid_body_inputs_.deserialize(buffer);
      joint_inputs_.deserialize(buffer);
      contact_state_input_.deserialize(buffer);

   }

   @Override
   public void set(KinematicsToolboxInputCollectionMessage from)
   {
      sequence_id_ = from.sequence_id_;
      center_of_mass_inputs_.set(from.center_of_mass_inputs_);
      rigid_body_inputs_.set(from.rigid_body_inputs_);
      joint_inputs_.set(from.joint_inputs_);
      contact_state_input_.set(from.contact_state_input_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxCenterOfMassMessage> getCenterOfMassInputs()
   {
      return center_of_mass_inputs_;
   }

   public IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxRigidBodyMessage> getRigidBodyInputs()
   {
      return rigid_body_inputs_;
   }

   public IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxOneDoFJointMessage> getJointInputs()
   {
      return joint_inputs_;
   }

   public IDLObjectSequence<toolbox_msgs.msg.dds.KinematicsToolboxSupportRegionMessage> getContactStateInput()
   {
      return contact_state_input_;
   }


}