/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC footstep planning module.
<p>Source (toolbox_msgs/VisibilityGraphsParametersPacket):
<pre>{@code

# This message is part of the IHMC footstep planning module.

float64 DEFAULT_NO_VALUE = -11.1

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

float64 max_inter_region_connection_length -11.1

float64 normal_z_threshold_for_accessible_regions -11.1

float64 navigable_extrusion_distance -11.1

float64 obstacle_extrusion_distance -11.1

float64 obstacle_extrusion_distance_if_not_too_high_to_step -11.1

float64 too_high_to_step_distance -11.1

float64 height_for_max_avoidance -11.1

float64 cluster_resolution -11.1

float64 exploration_distance_from_start_goal -11.1

float64 planar_region_min_area 0.0

uint32 planar_region_min_size 0

# Defines the angle from which two regions are considered orthogonal.
# It is used to determine if a region should be projected onto another as a polygon or a line.
# It should be close to 90 degrees.
# Returns the angle threshold to use to determine if a line or polygon projection method should be used.
float64 region_orthogonal_angle -11.1

# This epsilon is is used when searching to which region the start/goal belongs to.
# A positive value corresponds to growing all the regions before testing if the start/goal is inside.
# Returns the value of the epsilon to use.
float64 search_host_region_epsilon 0.03

float64 can_duck_under_height -11.1

float64 can_easily_step_over_height -11.1

float64 length_for_long_inter_region_edge -11.1

bool perform_post_processing_node_shifting false

bool introduce_midpoints_in_post_processing true

bool compute_orientations_to_avoid_obstacles false

float64 heuristic_weight -11.1

float64 distance_weight -11.1

float64 elevation_weight -11.1

float64 occluded_goal_edge_weight -11.1

float64 weight_for_inter_region_edge -11.1

bool return_best_effort_solution false

bool optimize_for_narrow_passage false}</pre>
*/
public class VisibilityGraphsParametersPacket implements ROS2Message<VisibilityGraphsParametersPacket>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::VisibilityGraphsParametersPacket_";

   public static final double DEFAULT_NO_VALUE = -11.1;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private double max_inter_region_connection_length_;
   private double normal_z_threshold_for_accessible_regions_;
   private double navigable_extrusion_distance_;
   private double obstacle_extrusion_distance_;
   private double obstacle_extrusion_distance_if_not_too_high_to_step_;
   private double too_high_to_step_distance_;
   private double height_for_max_avoidance_;
   private double cluster_resolution_;
   private double exploration_distance_from_start_goal_;
   private double planar_region_min_area_;
   private int planar_region_min_size_;
   /**
      Defines the angle from which two regions are considered orthogonal.
      It is used to determine if a region should be projected onto another as a polygon or a line.
      It should be close to 90 degrees.
      Returns the angle threshold to use to determine if a line or polygon projection method should be used.
   */
   private double region_orthogonal_angle_;
   /**
      This epsilon is is used when searching to which region the start/goal belongs to.
      A positive value corresponds to growing all the regions before testing if the start/goal is inside.
      Returns the value of the epsilon to use.
   */
   private double search_host_region_epsilon_;
   private double can_duck_under_height_;
   private double can_easily_step_over_height_;
   private double length_for_long_inter_region_edge_;
   private boolean perform_post_processing_node_shifting_;
   private boolean introduce_midpoints_in_post_processing_;
   private boolean compute_orientations_to_avoid_obstacles_;
   private double heuristic_weight_;
   private double distance_weight_;
   private double elevation_weight_;
   private double occluded_goal_edge_weight_;
   private double weight_for_inter_region_edge_;
   private boolean return_best_effort_solution_;
   private boolean optimize_for_narrow_passage_;

   public VisibilityGraphsParametersPacket()
   {
      max_inter_region_connection_length_ = (double) -11.1;
      normal_z_threshold_for_accessible_regions_ = (double) -11.1;
      navigable_extrusion_distance_ = (double) -11.1;
      obstacle_extrusion_distance_ = (double) -11.1;
      obstacle_extrusion_distance_if_not_too_high_to_step_ = (double) -11.1;
      too_high_to_step_distance_ = (double) -11.1;
      height_for_max_avoidance_ = (double) -11.1;
      cluster_resolution_ = (double) -11.1;
      exploration_distance_from_start_goal_ = (double) -11.1;
      planar_region_min_area_ = (double) 0.0;
      planar_region_min_size_ = (int) 0;
      region_orthogonal_angle_ = (double) -11.1;
      search_host_region_epsilon_ = (double) 0.03;
      can_duck_under_height_ = (double) -11.1;
      can_easily_step_over_height_ = (double) -11.1;
      length_for_long_inter_region_edge_ = (double) -11.1;
      perform_post_processing_node_shifting_ = (boolean) false;
      introduce_midpoints_in_post_processing_ = (boolean) true;
      compute_orientations_to_avoid_obstacles_ = (boolean) false;
      heuristic_weight_ = (double) -11.1;
      distance_weight_ = (double) -11.1;
      elevation_weight_ = (double) -11.1;
      occluded_goal_edge_weight_ = (double) -11.1;
      weight_for_inter_region_edge_ = (double) -11.1;
      return_best_effort_solution_ = (boolean) false;
      optimize_for_narrow_passage_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // max_inter_region_connection_length_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // normal_z_threshold_for_accessible_regions_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // navigable_extrusion_distance_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // obstacle_extrusion_distance_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // obstacle_extrusion_distance_if_not_too_high_to_step_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // too_high_to_step_distance_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // height_for_max_avoidance_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // cluster_resolution_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // exploration_distance_from_start_goal_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // planar_region_min_area_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // planar_region_min_size_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // region_orthogonal_angle_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // search_host_region_epsilon_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // can_duck_under_height_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // can_easily_step_over_height_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // length_for_long_inter_region_edge_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // perform_post_processing_node_shifting_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // introduce_midpoints_in_post_processing_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // compute_orientations_to_avoid_obstacles_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // heuristic_weight_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // distance_weight_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // elevation_weight_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // occluded_goal_edge_weight_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // weight_for_inter_region_edge_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // return_best_effort_solution_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // optimize_for_narrow_passage_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeDouble(max_inter_region_connection_length_);
      buffer.writeDouble(normal_z_threshold_for_accessible_regions_);
      buffer.writeDouble(navigable_extrusion_distance_);
      buffer.writeDouble(obstacle_extrusion_distance_);
      buffer.writeDouble(obstacle_extrusion_distance_if_not_too_high_to_step_);
      buffer.writeDouble(too_high_to_step_distance_);
      buffer.writeDouble(height_for_max_avoidance_);
      buffer.writeDouble(cluster_resolution_);
      buffer.writeDouble(exploration_distance_from_start_goal_);
      buffer.writeDouble(planar_region_min_area_);
      buffer.writeInt(planar_region_min_size_);
      buffer.writeDouble(region_orthogonal_angle_);
      buffer.writeDouble(search_host_region_epsilon_);
      buffer.writeDouble(can_duck_under_height_);
      buffer.writeDouble(can_easily_step_over_height_);
      buffer.writeDouble(length_for_long_inter_region_edge_);
      buffer.writeBoolean(perform_post_processing_node_shifting_);
      buffer.writeBoolean(introduce_midpoints_in_post_processing_);
      buffer.writeBoolean(compute_orientations_to_avoid_obstacles_);
      buffer.writeDouble(heuristic_weight_);
      buffer.writeDouble(distance_weight_);
      buffer.writeDouble(elevation_weight_);
      buffer.writeDouble(occluded_goal_edge_weight_);
      buffer.writeDouble(weight_for_inter_region_edge_);
      buffer.writeBoolean(return_best_effort_solution_);
      buffer.writeBoolean(optimize_for_narrow_passage_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      max_inter_region_connection_length_ = buffer.readDouble();
      normal_z_threshold_for_accessible_regions_ = buffer.readDouble();
      navigable_extrusion_distance_ = buffer.readDouble();
      obstacle_extrusion_distance_ = buffer.readDouble();
      obstacle_extrusion_distance_if_not_too_high_to_step_ = buffer.readDouble();
      too_high_to_step_distance_ = buffer.readDouble();
      height_for_max_avoidance_ = buffer.readDouble();
      cluster_resolution_ = buffer.readDouble();
      exploration_distance_from_start_goal_ = buffer.readDouble();
      planar_region_min_area_ = buffer.readDouble();
      planar_region_min_size_ = buffer.readInt();
      region_orthogonal_angle_ = buffer.readDouble();
      search_host_region_epsilon_ = buffer.readDouble();
      can_duck_under_height_ = buffer.readDouble();
      can_easily_step_over_height_ = buffer.readDouble();
      length_for_long_inter_region_edge_ = buffer.readDouble();
      perform_post_processing_node_shifting_ = buffer.readBoolean();
      introduce_midpoints_in_post_processing_ = buffer.readBoolean();
      compute_orientations_to_avoid_obstacles_ = buffer.readBoolean();
      heuristic_weight_ = buffer.readDouble();
      distance_weight_ = buffer.readDouble();
      elevation_weight_ = buffer.readDouble();
      occluded_goal_edge_weight_ = buffer.readDouble();
      weight_for_inter_region_edge_ = buffer.readDouble();
      return_best_effort_solution_ = buffer.readBoolean();
      optimize_for_narrow_passage_ = buffer.readBoolean();

   }

   @Override
   public void set(VisibilityGraphsParametersPacket from)
   {
      sequence_id_ = from.sequence_id_;
      max_inter_region_connection_length_ = from.max_inter_region_connection_length_;
      normal_z_threshold_for_accessible_regions_ = from.normal_z_threshold_for_accessible_regions_;
      navigable_extrusion_distance_ = from.navigable_extrusion_distance_;
      obstacle_extrusion_distance_ = from.obstacle_extrusion_distance_;
      obstacle_extrusion_distance_if_not_too_high_to_step_ = from.obstacle_extrusion_distance_if_not_too_high_to_step_;
      too_high_to_step_distance_ = from.too_high_to_step_distance_;
      height_for_max_avoidance_ = from.height_for_max_avoidance_;
      cluster_resolution_ = from.cluster_resolution_;
      exploration_distance_from_start_goal_ = from.exploration_distance_from_start_goal_;
      planar_region_min_area_ = from.planar_region_min_area_;
      planar_region_min_size_ = from.planar_region_min_size_;
      region_orthogonal_angle_ = from.region_orthogonal_angle_;
      search_host_region_epsilon_ = from.search_host_region_epsilon_;
      can_duck_under_height_ = from.can_duck_under_height_;
      can_easily_step_over_height_ = from.can_easily_step_over_height_;
      length_for_long_inter_region_edge_ = from.length_for_long_inter_region_edge_;
      perform_post_processing_node_shifting_ = from.perform_post_processing_node_shifting_;
      introduce_midpoints_in_post_processing_ = from.introduce_midpoints_in_post_processing_;
      compute_orientations_to_avoid_obstacles_ = from.compute_orientations_to_avoid_obstacles_;
      heuristic_weight_ = from.heuristic_weight_;
      distance_weight_ = from.distance_weight_;
      elevation_weight_ = from.elevation_weight_;
      occluded_goal_edge_weight_ = from.occluded_goal_edge_weight_;
      weight_for_inter_region_edge_ = from.weight_for_inter_region_edge_;
      return_best_effort_solution_ = from.return_best_effort_solution_;
      optimize_for_narrow_passage_ = from.optimize_for_narrow_passage_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public double getMaxInterRegionConnectionLength()
   {
      return max_inter_region_connection_length_;
   }

   public void setMaxInterRegionConnectionLength(double max_inter_region_connection_length_)
   {
      this.max_inter_region_connection_length_ = max_inter_region_connection_length_;
   }

   public double getNormalZThresholdForAccessibleRegions()
   {
      return normal_z_threshold_for_accessible_regions_;
   }

   public void setNormalZThresholdForAccessibleRegions(double normal_z_threshold_for_accessible_regions_)
   {
      this.normal_z_threshold_for_accessible_regions_ = normal_z_threshold_for_accessible_regions_;
   }

   public double getNavigableExtrusionDistance()
   {
      return navigable_extrusion_distance_;
   }

   public void setNavigableExtrusionDistance(double navigable_extrusion_distance_)
   {
      this.navigable_extrusion_distance_ = navigable_extrusion_distance_;
   }

   public double getObstacleExtrusionDistance()
   {
      return obstacle_extrusion_distance_;
   }

   public void setObstacleExtrusionDistance(double obstacle_extrusion_distance_)
   {
      this.obstacle_extrusion_distance_ = obstacle_extrusion_distance_;
   }

   public double getObstacleExtrusionDistanceIfNotTooHighToStep()
   {
      return obstacle_extrusion_distance_if_not_too_high_to_step_;
   }

   public void setObstacleExtrusionDistanceIfNotTooHighToStep(double obstacle_extrusion_distance_if_not_too_high_to_step_)
   {
      this.obstacle_extrusion_distance_if_not_too_high_to_step_ = obstacle_extrusion_distance_if_not_too_high_to_step_;
   }

   public double getTooHighToStepDistance()
   {
      return too_high_to_step_distance_;
   }

   public void setTooHighToStepDistance(double too_high_to_step_distance_)
   {
      this.too_high_to_step_distance_ = too_high_to_step_distance_;
   }

   public double getHeightForMaxAvoidance()
   {
      return height_for_max_avoidance_;
   }

   public void setHeightForMaxAvoidance(double height_for_max_avoidance_)
   {
      this.height_for_max_avoidance_ = height_for_max_avoidance_;
   }

   public double getClusterResolution()
   {
      return cluster_resolution_;
   }

   public void setClusterResolution(double cluster_resolution_)
   {
      this.cluster_resolution_ = cluster_resolution_;
   }

   public double getExplorationDistanceFromStartGoal()
   {
      return exploration_distance_from_start_goal_;
   }

   public void setExplorationDistanceFromStartGoal(double exploration_distance_from_start_goal_)
   {
      this.exploration_distance_from_start_goal_ = exploration_distance_from_start_goal_;
   }

   public double getPlanarRegionMinArea()
   {
      return planar_region_min_area_;
   }

   public void setPlanarRegionMinArea(double planar_region_min_area_)
   {
      this.planar_region_min_area_ = planar_region_min_area_;
   }

   public int getPlanarRegionMinSize()
   {
      return planar_region_min_size_;
   }

   public void setPlanarRegionMinSize(int planar_region_min_size_)
   {
      this.planar_region_min_size_ = planar_region_min_size_;
   }

   public double getRegionOrthogonalAngle()
   {
      return region_orthogonal_angle_;
   }

   public void setRegionOrthogonalAngle(double region_orthogonal_angle_)
   {
      this.region_orthogonal_angle_ = region_orthogonal_angle_;
   }

   public double getSearchHostRegionEpsilon()
   {
      return search_host_region_epsilon_;
   }

   public void setSearchHostRegionEpsilon(double search_host_region_epsilon_)
   {
      this.search_host_region_epsilon_ = search_host_region_epsilon_;
   }

   public double getCanDuckUnderHeight()
   {
      return can_duck_under_height_;
   }

   public void setCanDuckUnderHeight(double can_duck_under_height_)
   {
      this.can_duck_under_height_ = can_duck_under_height_;
   }

   public double getCanEasilyStepOverHeight()
   {
      return can_easily_step_over_height_;
   }

   public void setCanEasilyStepOverHeight(double can_easily_step_over_height_)
   {
      this.can_easily_step_over_height_ = can_easily_step_over_height_;
   }

   public double getLengthForLongInterRegionEdge()
   {
      return length_for_long_inter_region_edge_;
   }

   public void setLengthForLongInterRegionEdge(double length_for_long_inter_region_edge_)
   {
      this.length_for_long_inter_region_edge_ = length_for_long_inter_region_edge_;
   }

   public boolean getPerformPostProcessingNodeShifting()
   {
      return perform_post_processing_node_shifting_;
   }

   public void setPerformPostProcessingNodeShifting(boolean perform_post_processing_node_shifting_)
   {
      this.perform_post_processing_node_shifting_ = perform_post_processing_node_shifting_;
   }

   public boolean getIntroduceMidpointsInPostProcessing()
   {
      return introduce_midpoints_in_post_processing_;
   }

   public void setIntroduceMidpointsInPostProcessing(boolean introduce_midpoints_in_post_processing_)
   {
      this.introduce_midpoints_in_post_processing_ = introduce_midpoints_in_post_processing_;
   }

   public boolean getComputeOrientationsToAvoidObstacles()
   {
      return compute_orientations_to_avoid_obstacles_;
   }

   public void setComputeOrientationsToAvoidObstacles(boolean compute_orientations_to_avoid_obstacles_)
   {
      this.compute_orientations_to_avoid_obstacles_ = compute_orientations_to_avoid_obstacles_;
   }

   public double getHeuristicWeight()
   {
      return heuristic_weight_;
   }

   public void setHeuristicWeight(double heuristic_weight_)
   {
      this.heuristic_weight_ = heuristic_weight_;
   }

   public double getDistanceWeight()
   {
      return distance_weight_;
   }

   public void setDistanceWeight(double distance_weight_)
   {
      this.distance_weight_ = distance_weight_;
   }

   public double getElevationWeight()
   {
      return elevation_weight_;
   }

   public void setElevationWeight(double elevation_weight_)
   {
      this.elevation_weight_ = elevation_weight_;
   }

   public double getOccludedGoalEdgeWeight()
   {
      return occluded_goal_edge_weight_;
   }

   public void setOccludedGoalEdgeWeight(double occluded_goal_edge_weight_)
   {
      this.occluded_goal_edge_weight_ = occluded_goal_edge_weight_;
   }

   public double getWeightForInterRegionEdge()
   {
      return weight_for_inter_region_edge_;
   }

   public void setWeightForInterRegionEdge(double weight_for_inter_region_edge_)
   {
      this.weight_for_inter_region_edge_ = weight_for_inter_region_edge_;
   }

   public boolean getReturnBestEffortSolution()
   {
      return return_best_effort_solution_;
   }

   public void setReturnBestEffortSolution(boolean return_best_effort_solution_)
   {
      this.return_best_effort_solution_ = return_best_effort_solution_;
   }

   public boolean getOptimizeForNarrowPassage()
   {
      return optimize_for_narrow_passage_;
   }

   public void setOptimizeForNarrowPassage(boolean optimize_for_narrow_passage_)
   {
      this.optimize_for_narrow_passage_ = optimize_for_narrow_passage_;
   }


}