/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC humanoid behavior module.
<p>Source (toolbox_msgs/WalkToGoalBehaviorPacket):
<pre>{@code
# This message is part of the IHMC humanoid behavior module.

byte WALK_TO_GOAL_ACTION_FIND_PATH = 0
byte WALK_TO_GOAL_ACTION_EXECUTE = 1
byte WALK_TO_GOAL_ACTION_EXECUTE_UNKNOWN = 2
byte WALK_TO_GOAL_ACTION_STOP = 3

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte ROBOT_SIDE_LEFT = 0
byte ROBOT_SIDE_RIGHT = 1

byte walk_to_goal_action 255
float64 x_goal
float64 y_goal
float64 theta_goal

byte goal_robot_side 255}</pre>
*/
public class WalkToGoalBehaviorPacket implements ROS2Message<WalkToGoalBehaviorPacket>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::WalkToGoalBehaviorPacket_";

   public static final byte WALK_TO_GOAL_ACTION_FIND_PATH = 0;
   public static final byte WALK_TO_GOAL_ACTION_EXECUTE = 1;
   public static final byte WALK_TO_GOAL_ACTION_EXECUTE_UNKNOWN = 2;
   public static final byte WALK_TO_GOAL_ACTION_STOP = 3;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   private byte walk_to_goal_action_;
   private double x_goal_;
   private double y_goal_;
   private double theta_goal_;
   private byte goal_robot_side_;

   public WalkToGoalBehaviorPacket()
   {
      walk_to_goal_action_ = (byte) 255;
      goal_robot_side_ = (byte) 255;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // walk_to_goal_action_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // x_goal_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // y_goal_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // theta_goal_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // goal_robot_side_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(walk_to_goal_action_);
      buffer.writeDouble(x_goal_);
      buffer.writeDouble(y_goal_);
      buffer.writeDouble(theta_goal_);
      buffer.writeByte(goal_robot_side_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      walk_to_goal_action_ = buffer.readByte();
      x_goal_ = buffer.readDouble();
      y_goal_ = buffer.readDouble();
      theta_goal_ = buffer.readDouble();
      goal_robot_side_ = buffer.readByte();

   }

   @Override
   public void set(WalkToGoalBehaviorPacket from)
   {
      sequence_id_ = from.sequence_id_;
      walk_to_goal_action_ = from.walk_to_goal_action_;
      x_goal_ = from.x_goal_;
      y_goal_ = from.y_goal_;
      theta_goal_ = from.theta_goal_;
      goal_robot_side_ = from.goal_robot_side_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getWalkToGoalAction()
   {
      return walk_to_goal_action_;
   }

   public void setWalkToGoalAction(byte walk_to_goal_action_)
   {
      this.walk_to_goal_action_ = walk_to_goal_action_;
   }

   public double getXGoal()
   {
      return x_goal_;
   }

   public void setXGoal(double x_goal_)
   {
      this.x_goal_ = x_goal_;
   }

   public double getYGoal()
   {
      return y_goal_;
   }

   public void setYGoal(double y_goal_)
   {
      this.y_goal_ = y_goal_;
   }

   public double getThetaGoal()
   {
      return theta_goal_;
   }

   public void setThetaGoal(double theta_goal_)
   {
      this.theta_goal_ = theta_goal_;
   }

   public byte getGoalRobotSide()
   {
      return goal_robot_side_;
   }

   public void setGoalRobotSide(byte goal_robot_side_)
   {
      this.goal_robot_side_ = goal_robot_side_;
   }


}