/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package vision_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (vision_msgs/BoundingBox2DArray):
<pre>{@code
std_msgs/Header header
vision_msgs/BoundingBox2D[] boxes
}</pre>
*/
public class BoundingBox2DArray implements ROS2Message<BoundingBox2DArray>
{
   public static final java.lang.String name = "vision_msgs::msg::dds_::BoundingBox2DArray_";

   private final std_msgs.msg.dds.Header header_;
   private final IDLObjectSequence<vision_msgs.msg.dds.BoundingBox2D> boxes_;

   public BoundingBox2DArray()
   {
      header_ = new std_msgs.msg.dds.Header();
      boxes_ = new IDLObjectSequence<vision_msgs.msg.dds.BoundingBox2D>(vision_msgs.msg.dds.BoundingBox2D.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += boxes_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      boxes_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      boxes_.deserialize(buffer);

   }

   @Override
   public void set(BoundingBox2DArray from)
   {
      header_.set(from.header_);
      boxes_.set(from.boxes_);

   }

   public std_msgs.msg.dds.Header getHeader()
   {
      return header_;
   }

   public IDLObjectSequence<vision_msgs.msg.dds.BoundingBox2D> getBoxes()
   {
      return boxes_;
   }


}