/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package vision_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A list of 3D detections, for a multi-object 3D detector.
<p>Source (vision_msgs/Detection3DArray):
<pre>{@code
# A list of 3D detections, for a multi-object 3D detector.

std_msgs/Header header

# A list of the detected proposals. A multi-proposal detector might generate
#   this list with many candidate detections generated from a single input.
Detection3D[] detections
}</pre>
*/
public class Detection3DArray implements ROS2Message<Detection3DArray>
{
   public static final java.lang.String name = "vision_msgs::msg::dds_::Detection3DArray_";

   private final std_msgs.msg.dds.Header header_;
   /**
      A list of the detected proposals. A multi-proposal detector might generate
      this list with many candidate detections generated from a single input.
   */
   private final IDLObjectSequence<vision_msgs.msg.dds.Detection3D> detections_;

   public Detection3DArray()
   {
      header_ = new std_msgs.msg.dds.Header();
      detections_ = new IDLObjectSequence<vision_msgs.msg.dds.Detection3D>(vision_msgs.msg.dds.Detection3D.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += detections_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      detections_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      detections_.deserialize(buffer);

   }

   @Override
   public void set(Detection3DArray from)
   {
      header_.set(from.header_);
      detections_.set(from.detections_);

   }

   public std_msgs.msg.dds.Header getHeader()
   {
      return header_;
   }

   public IDLObjectSequence<vision_msgs.msg.dds.Detection3D> getDetections()
   {
      return detections_;
   }


}