/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package exoskeleton_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Message used for syncing the body dimension config files in eva's resources with eva's local config files
<p>Source (exoskeleton_msgs/EvaBodyDimensionsMessage):
<pre>{@code
#Message used for syncing the body dimension config files in eva's resources with eva's local config files

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

int8[<=2048] file_name


# This is the wrench at the foot, with respect to the sole frame
float64 thigh_length
float64 shank_length
uint32 shoe_size_oridinal}</pre>
*/
public class EvaBodyDimensionsMessage implements ROS2Message<EvaBodyDimensionsMessage>
{
   public static final java.lang.String name = "exoskeleton_msgs::msg::dds_::EvaBodyDimensionsMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final IDLByteSequence file_name_;
   /**
      This is the wrench at the foot, with respect to the sole frame
   */
   private double thigh_length_;
   private double shank_length_;
   private int shoe_size_oridinal_;

   public EvaBodyDimensionsMessage()
   {
      file_name_ = new IDLByteSequence(2048);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += file_name_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // thigh_length_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // shank_length_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // shoe_size_oridinal_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      file_name_.serialize(buffer);
      buffer.writeDouble(thigh_length_);
      buffer.writeDouble(shank_length_);
      buffer.writeInt(shoe_size_oridinal_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      file_name_.deserialize(buffer);
      thigh_length_ = buffer.readDouble();
      shank_length_ = buffer.readDouble();
      shoe_size_oridinal_ = buffer.readInt();

   }

   @Override
   public void set(EvaBodyDimensionsMessage from)
   {
      sequence_id_ = from.sequence_id_;
      file_name_.set(from.file_name_);
      thigh_length_ = from.thigh_length_;
      shank_length_ = from.shank_length_;
      shoe_size_oridinal_ = from.shoe_size_oridinal_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLByteSequence getFileName()
   {
      return file_name_;
   }

   public double getThighLength()
   {
      return thigh_length_;
   }

   public void setThighLength(double thigh_length_)
   {
      this.thigh_length_ = thigh_length_;
   }

   public double getShankLength()
   {
      return shank_length_;
   }

   public void setShankLength(double shank_length_)
   {
      this.shank_length_ = shank_length_;
   }

   public int getShoeSizeOridinal()
   {
      return shoe_size_oridinal_;
   }

   public void setShoeSizeOridinal(int shoe_size_oridinal_)
   {
      this.shoe_size_oridinal_ = shoe_size_oridinal_;
   }


}