/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package exoskeleton_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is going to take in data and assign to each muscle channel
<p>Source (exoskeleton_msgs/ExoEMGMessage):
<pre>{@code
# This message is going to take in data and assign to each muscle channel

uint32 id  #message ID

#floats for each muscle channel
float32 frontalisrt
float32 frontalislt
float32 tart
float32 talt
float32 tprt
float32 tplt
float32 masseterrt
float32 masseterlt
float32 scmrt
float32 scmlt
float32 middeltrt
float32 middeltlt
float32 antdeltoidrt
float32 antdeltoidlt
float32 mserratusantrt
float32 mserratusantlt
float32 lattricepsrt
float32 lattricepslt
float32 brachiodrt
float32 brachiodlt
float32 bicepsbrrt
float32 bicepsbrlt
float32 flexcarpurt
float32 flexcarpult
float32 flexcarprrt
float32 flexcarprlt
float32 abductpolrt
float32 abductpollt
float32 extdigrt
float32 extdiglt
float32 pectmajorrt
float32 pectmajorlt
float32 rectabdomuprt
float32 rectabdomuplt
float32 rectabdomlort
float32 rectabdomlolt
float32 extobliquert
float32 extobliquelt
float32 intobliquert
float32 intobliquelt
float32 adductorsrt
float32 adductorslt
float32 soleusrt
float32 soleuslt
float32 tibantrt
float32 tibantlt
float32 peroneusrt
float32 peroneuslt
float32 medgastrort
float32 medgastrolt
float32 latgastrort
float32 latgastrolt
float32 bicepsfemrt
float32 bicepsfemlt
float32 semitendrt
float32 semitendlt
float32 vlort
float32 vlolt
float32 vmort
float32 vmolt
float32 rectusfemrt
float32 rectusfemlt
float32 pelvicfloorrt
float32 pelvicfloorlt
float32 uppertraprt
float32 uppertraplt
float32 middletraprt
float32 middletraplt
float32 lowertraprt
float32 lowertraplt
float32 thoracicrt
float32 thoraciclt
float32 multifidiirt
float32 multifidiilt
float32 glutmaxrt
float32 glutmaxlt
float32 glutmedrt
float32 glutmedlt
float32 latdorsirt
float32 latdorsilt
float32 infraspinrt
float32 infraspinlt
float32 cervicalpsrt
float32 cervicalpslt}</pre>
*/
public class ExoEMGMessage implements ROS2Message<ExoEMGMessage>
{
   public static final java.lang.String name = "exoskeleton_msgs::msg::dds_::ExoEMGMessage_";

   private int id_; // message ID
   /**
      floats for each muscle channel
   */
   private float frontalisrt_;
   private float frontalislt_;
   private float tart_;
   private float talt_;
   private float tprt_;
   private float tplt_;
   private float masseterrt_;
   private float masseterlt_;
   private float scmrt_;
   private float scmlt_;
   private float middeltrt_;
   private float middeltlt_;
   private float antdeltoidrt_;
   private float antdeltoidlt_;
   private float mserratusantrt_;
   private float mserratusantlt_;
   private float lattricepsrt_;
   private float lattricepslt_;
   private float brachiodrt_;
   private float brachiodlt_;
   private float bicepsbrrt_;
   private float bicepsbrlt_;
   private float flexcarpurt_;
   private float flexcarpult_;
   private float flexcarprrt_;
   private float flexcarprlt_;
   private float abductpolrt_;
   private float abductpollt_;
   private float extdigrt_;
   private float extdiglt_;
   private float pectmajorrt_;
   private float pectmajorlt_;
   private float rectabdomuprt_;
   private float rectabdomuplt_;
   private float rectabdomlort_;
   private float rectabdomlolt_;
   private float extobliquert_;
   private float extobliquelt_;
   private float intobliquert_;
   private float intobliquelt_;
   private float adductorsrt_;
   private float adductorslt_;
   private float soleusrt_;
   private float soleuslt_;
   private float tibantrt_;
   private float tibantlt_;
   private float peroneusrt_;
   private float peroneuslt_;
   private float medgastrort_;
   private float medgastrolt_;
   private float latgastrort_;
   private float latgastrolt_;
   private float bicepsfemrt_;
   private float bicepsfemlt_;
   private float semitendrt_;
   private float semitendlt_;
   private float vlort_;
   private float vlolt_;
   private float vmort_;
   private float vmolt_;
   private float rectusfemrt_;
   private float rectusfemlt_;
   private float pelvicfloorrt_;
   private float pelvicfloorlt_;
   private float uppertraprt_;
   private float uppertraplt_;
   private float middletraprt_;
   private float middletraplt_;
   private float lowertraprt_;
   private float lowertraplt_;
   private float thoracicrt_;
   private float thoraciclt_;
   private float multifidiirt_;
   private float multifidiilt_;
   private float glutmaxrt_;
   private float glutmaxlt_;
   private float glutmedrt_;
   private float glutmedlt_;
   private float latdorsirt_;
   private float latdorsilt_;
   private float infraspinrt_;
   private float infraspinlt_;
   private float cervicalpsrt_;
   private float cervicalpslt_;

   public ExoEMGMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // frontalisrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // frontalislt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // tart_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // talt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // tprt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // tplt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // masseterrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // masseterlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // scmrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // scmlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // middeltrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // middeltlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // antdeltoidrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // antdeltoidlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // mserratusantrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // mserratusantlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // lattricepsrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // lattricepslt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // brachiodrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // brachiodlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // bicepsbrrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // bicepsbrlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // flexcarpurt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // flexcarpult_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // flexcarprrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // flexcarprlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // abductpolrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // abductpollt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // extdigrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // extdiglt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // pectmajorrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // pectmajorlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // rectabdomuprt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // rectabdomuplt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // rectabdomlort_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // rectabdomlolt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // extobliquert_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // extobliquelt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // intobliquert_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // intobliquelt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // adductorsrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // adductorslt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // soleusrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // soleuslt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // tibantrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // tibantlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // peroneusrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // peroneuslt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // medgastrort_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // medgastrolt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // latgastrort_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // latgastrolt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // bicepsfemrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // bicepsfemlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // semitendrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // semitendlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // vlort_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // vlolt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // vmort_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // vmolt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // rectusfemrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // rectusfemlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // pelvicfloorrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // pelvicfloorlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // uppertraprt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // uppertraplt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // middletraprt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // middletraplt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // lowertraprt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // lowertraplt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // thoracicrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // thoraciclt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // multifidiirt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // multifidiilt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // glutmaxrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // glutmaxlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // glutmedrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // glutmedlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // latdorsirt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // latdorsilt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // infraspinrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // infraspinlt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // cervicalpsrt_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // cervicalpslt_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(id_);
      buffer.writeFloat(frontalisrt_);
      buffer.writeFloat(frontalislt_);
      buffer.writeFloat(tart_);
      buffer.writeFloat(talt_);
      buffer.writeFloat(tprt_);
      buffer.writeFloat(tplt_);
      buffer.writeFloat(masseterrt_);
      buffer.writeFloat(masseterlt_);
      buffer.writeFloat(scmrt_);
      buffer.writeFloat(scmlt_);
      buffer.writeFloat(middeltrt_);
      buffer.writeFloat(middeltlt_);
      buffer.writeFloat(antdeltoidrt_);
      buffer.writeFloat(antdeltoidlt_);
      buffer.writeFloat(mserratusantrt_);
      buffer.writeFloat(mserratusantlt_);
      buffer.writeFloat(lattricepsrt_);
      buffer.writeFloat(lattricepslt_);
      buffer.writeFloat(brachiodrt_);
      buffer.writeFloat(brachiodlt_);
      buffer.writeFloat(bicepsbrrt_);
      buffer.writeFloat(bicepsbrlt_);
      buffer.writeFloat(flexcarpurt_);
      buffer.writeFloat(flexcarpult_);
      buffer.writeFloat(flexcarprrt_);
      buffer.writeFloat(flexcarprlt_);
      buffer.writeFloat(abductpolrt_);
      buffer.writeFloat(abductpollt_);
      buffer.writeFloat(extdigrt_);
      buffer.writeFloat(extdiglt_);
      buffer.writeFloat(pectmajorrt_);
      buffer.writeFloat(pectmajorlt_);
      buffer.writeFloat(rectabdomuprt_);
      buffer.writeFloat(rectabdomuplt_);
      buffer.writeFloat(rectabdomlort_);
      buffer.writeFloat(rectabdomlolt_);
      buffer.writeFloat(extobliquert_);
      buffer.writeFloat(extobliquelt_);
      buffer.writeFloat(intobliquert_);
      buffer.writeFloat(intobliquelt_);
      buffer.writeFloat(adductorsrt_);
      buffer.writeFloat(adductorslt_);
      buffer.writeFloat(soleusrt_);
      buffer.writeFloat(soleuslt_);
      buffer.writeFloat(tibantrt_);
      buffer.writeFloat(tibantlt_);
      buffer.writeFloat(peroneusrt_);
      buffer.writeFloat(peroneuslt_);
      buffer.writeFloat(medgastrort_);
      buffer.writeFloat(medgastrolt_);
      buffer.writeFloat(latgastrort_);
      buffer.writeFloat(latgastrolt_);
      buffer.writeFloat(bicepsfemrt_);
      buffer.writeFloat(bicepsfemlt_);
      buffer.writeFloat(semitendrt_);
      buffer.writeFloat(semitendlt_);
      buffer.writeFloat(vlort_);
      buffer.writeFloat(vlolt_);
      buffer.writeFloat(vmort_);
      buffer.writeFloat(vmolt_);
      buffer.writeFloat(rectusfemrt_);
      buffer.writeFloat(rectusfemlt_);
      buffer.writeFloat(pelvicfloorrt_);
      buffer.writeFloat(pelvicfloorlt_);
      buffer.writeFloat(uppertraprt_);
      buffer.writeFloat(uppertraplt_);
      buffer.writeFloat(middletraprt_);
      buffer.writeFloat(middletraplt_);
      buffer.writeFloat(lowertraprt_);
      buffer.writeFloat(lowertraplt_);
      buffer.writeFloat(thoracicrt_);
      buffer.writeFloat(thoraciclt_);
      buffer.writeFloat(multifidiirt_);
      buffer.writeFloat(multifidiilt_);
      buffer.writeFloat(glutmaxrt_);
      buffer.writeFloat(glutmaxlt_);
      buffer.writeFloat(glutmedrt_);
      buffer.writeFloat(glutmedlt_);
      buffer.writeFloat(latdorsirt_);
      buffer.writeFloat(latdorsilt_);
      buffer.writeFloat(infraspinrt_);
      buffer.writeFloat(infraspinlt_);
      buffer.writeFloat(cervicalpsrt_);
      buffer.writeFloat(cervicalpslt_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      id_ = buffer.readInt();
      frontalisrt_ = buffer.readFloat();
      frontalislt_ = buffer.readFloat();
      tart_ = buffer.readFloat();
      talt_ = buffer.readFloat();
      tprt_ = buffer.readFloat();
      tplt_ = buffer.readFloat();
      masseterrt_ = buffer.readFloat();
      masseterlt_ = buffer.readFloat();
      scmrt_ = buffer.readFloat();
      scmlt_ = buffer.readFloat();
      middeltrt_ = buffer.readFloat();
      middeltlt_ = buffer.readFloat();
      antdeltoidrt_ = buffer.readFloat();
      antdeltoidlt_ = buffer.readFloat();
      mserratusantrt_ = buffer.readFloat();
      mserratusantlt_ = buffer.readFloat();
      lattricepsrt_ = buffer.readFloat();
      lattricepslt_ = buffer.readFloat();
      brachiodrt_ = buffer.readFloat();
      brachiodlt_ = buffer.readFloat();
      bicepsbrrt_ = buffer.readFloat();
      bicepsbrlt_ = buffer.readFloat();
      flexcarpurt_ = buffer.readFloat();
      flexcarpult_ = buffer.readFloat();
      flexcarprrt_ = buffer.readFloat();
      flexcarprlt_ = buffer.readFloat();
      abductpolrt_ = buffer.readFloat();
      abductpollt_ = buffer.readFloat();
      extdigrt_ = buffer.readFloat();
      extdiglt_ = buffer.readFloat();
      pectmajorrt_ = buffer.readFloat();
      pectmajorlt_ = buffer.readFloat();
      rectabdomuprt_ = buffer.readFloat();
      rectabdomuplt_ = buffer.readFloat();
      rectabdomlort_ = buffer.readFloat();
      rectabdomlolt_ = buffer.readFloat();
      extobliquert_ = buffer.readFloat();
      extobliquelt_ = buffer.readFloat();
      intobliquert_ = buffer.readFloat();
      intobliquelt_ = buffer.readFloat();
      adductorsrt_ = buffer.readFloat();
      adductorslt_ = buffer.readFloat();
      soleusrt_ = buffer.readFloat();
      soleuslt_ = buffer.readFloat();
      tibantrt_ = buffer.readFloat();
      tibantlt_ = buffer.readFloat();
      peroneusrt_ = buffer.readFloat();
      peroneuslt_ = buffer.readFloat();
      medgastrort_ = buffer.readFloat();
      medgastrolt_ = buffer.readFloat();
      latgastrort_ = buffer.readFloat();
      latgastrolt_ = buffer.readFloat();
      bicepsfemrt_ = buffer.readFloat();
      bicepsfemlt_ = buffer.readFloat();
      semitendrt_ = buffer.readFloat();
      semitendlt_ = buffer.readFloat();
      vlort_ = buffer.readFloat();
      vlolt_ = buffer.readFloat();
      vmort_ = buffer.readFloat();
      vmolt_ = buffer.readFloat();
      rectusfemrt_ = buffer.readFloat();
      rectusfemlt_ = buffer.readFloat();
      pelvicfloorrt_ = buffer.readFloat();
      pelvicfloorlt_ = buffer.readFloat();
      uppertraprt_ = buffer.readFloat();
      uppertraplt_ = buffer.readFloat();
      middletraprt_ = buffer.readFloat();
      middletraplt_ = buffer.readFloat();
      lowertraprt_ = buffer.readFloat();
      lowertraplt_ = buffer.readFloat();
      thoracicrt_ = buffer.readFloat();
      thoraciclt_ = buffer.readFloat();
      multifidiirt_ = buffer.readFloat();
      multifidiilt_ = buffer.readFloat();
      glutmaxrt_ = buffer.readFloat();
      glutmaxlt_ = buffer.readFloat();
      glutmedrt_ = buffer.readFloat();
      glutmedlt_ = buffer.readFloat();
      latdorsirt_ = buffer.readFloat();
      latdorsilt_ = buffer.readFloat();
      infraspinrt_ = buffer.readFloat();
      infraspinlt_ = buffer.readFloat();
      cervicalpsrt_ = buffer.readFloat();
      cervicalpslt_ = buffer.readFloat();

   }

   @Override
   public void set(ExoEMGMessage from)
   {
      id_ = from.id_;
      frontalisrt_ = from.frontalisrt_;
      frontalislt_ = from.frontalislt_;
      tart_ = from.tart_;
      talt_ = from.talt_;
      tprt_ = from.tprt_;
      tplt_ = from.tplt_;
      masseterrt_ = from.masseterrt_;
      masseterlt_ = from.masseterlt_;
      scmrt_ = from.scmrt_;
      scmlt_ = from.scmlt_;
      middeltrt_ = from.middeltrt_;
      middeltlt_ = from.middeltlt_;
      antdeltoidrt_ = from.antdeltoidrt_;
      antdeltoidlt_ = from.antdeltoidlt_;
      mserratusantrt_ = from.mserratusantrt_;
      mserratusantlt_ = from.mserratusantlt_;
      lattricepsrt_ = from.lattricepsrt_;
      lattricepslt_ = from.lattricepslt_;
      brachiodrt_ = from.brachiodrt_;
      brachiodlt_ = from.brachiodlt_;
      bicepsbrrt_ = from.bicepsbrrt_;
      bicepsbrlt_ = from.bicepsbrlt_;
      flexcarpurt_ = from.flexcarpurt_;
      flexcarpult_ = from.flexcarpult_;
      flexcarprrt_ = from.flexcarprrt_;
      flexcarprlt_ = from.flexcarprlt_;
      abductpolrt_ = from.abductpolrt_;
      abductpollt_ = from.abductpollt_;
      extdigrt_ = from.extdigrt_;
      extdiglt_ = from.extdiglt_;
      pectmajorrt_ = from.pectmajorrt_;
      pectmajorlt_ = from.pectmajorlt_;
      rectabdomuprt_ = from.rectabdomuprt_;
      rectabdomuplt_ = from.rectabdomuplt_;
      rectabdomlort_ = from.rectabdomlort_;
      rectabdomlolt_ = from.rectabdomlolt_;
      extobliquert_ = from.extobliquert_;
      extobliquelt_ = from.extobliquelt_;
      intobliquert_ = from.intobliquert_;
      intobliquelt_ = from.intobliquelt_;
      adductorsrt_ = from.adductorsrt_;
      adductorslt_ = from.adductorslt_;
      soleusrt_ = from.soleusrt_;
      soleuslt_ = from.soleuslt_;
      tibantrt_ = from.tibantrt_;
      tibantlt_ = from.tibantlt_;
      peroneusrt_ = from.peroneusrt_;
      peroneuslt_ = from.peroneuslt_;
      medgastrort_ = from.medgastrort_;
      medgastrolt_ = from.medgastrolt_;
      latgastrort_ = from.latgastrort_;
      latgastrolt_ = from.latgastrolt_;
      bicepsfemrt_ = from.bicepsfemrt_;
      bicepsfemlt_ = from.bicepsfemlt_;
      semitendrt_ = from.semitendrt_;
      semitendlt_ = from.semitendlt_;
      vlort_ = from.vlort_;
      vlolt_ = from.vlolt_;
      vmort_ = from.vmort_;
      vmolt_ = from.vmolt_;
      rectusfemrt_ = from.rectusfemrt_;
      rectusfemlt_ = from.rectusfemlt_;
      pelvicfloorrt_ = from.pelvicfloorrt_;
      pelvicfloorlt_ = from.pelvicfloorlt_;
      uppertraprt_ = from.uppertraprt_;
      uppertraplt_ = from.uppertraplt_;
      middletraprt_ = from.middletraprt_;
      middletraplt_ = from.middletraplt_;
      lowertraprt_ = from.lowertraprt_;
      lowertraplt_ = from.lowertraplt_;
      thoracicrt_ = from.thoracicrt_;
      thoraciclt_ = from.thoraciclt_;
      multifidiirt_ = from.multifidiirt_;
      multifidiilt_ = from.multifidiilt_;
      glutmaxrt_ = from.glutmaxrt_;
      glutmaxlt_ = from.glutmaxlt_;
      glutmedrt_ = from.glutmedrt_;
      glutmedlt_ = from.glutmedlt_;
      latdorsirt_ = from.latdorsirt_;
      latdorsilt_ = from.latdorsilt_;
      infraspinrt_ = from.infraspinrt_;
      infraspinlt_ = from.infraspinlt_;
      cervicalpsrt_ = from.cervicalpsrt_;
      cervicalpslt_ = from.cervicalpslt_;

   }

   public int getId()
   {
      return id_;
   }

   public void setId(int id_)
   {
      this.id_ = id_;
   }

   public float getFrontalisrt()
   {
      return frontalisrt_;
   }

   public void setFrontalisrt(float frontalisrt_)
   {
      this.frontalisrt_ = frontalisrt_;
   }

   public float getFrontalislt()
   {
      return frontalislt_;
   }

   public void setFrontalislt(float frontalislt_)
   {
      this.frontalislt_ = frontalislt_;
   }

   public float getTart()
   {
      return tart_;
   }

   public void setTart(float tart_)
   {
      this.tart_ = tart_;
   }

   public float getTalt()
   {
      return talt_;
   }

   public void setTalt(float talt_)
   {
      this.talt_ = talt_;
   }

   public float getTprt()
   {
      return tprt_;
   }

   public void setTprt(float tprt_)
   {
      this.tprt_ = tprt_;
   }

   public float getTplt()
   {
      return tplt_;
   }

   public void setTplt(float tplt_)
   {
      this.tplt_ = tplt_;
   }

   public float getMasseterrt()
   {
      return masseterrt_;
   }

   public void setMasseterrt(float masseterrt_)
   {
      this.masseterrt_ = masseterrt_;
   }

   public float getMasseterlt()
   {
      return masseterlt_;
   }

   public void setMasseterlt(float masseterlt_)
   {
      this.masseterlt_ = masseterlt_;
   }

   public float getScmrt()
   {
      return scmrt_;
   }

   public void setScmrt(float scmrt_)
   {
      this.scmrt_ = scmrt_;
   }

   public float getScmlt()
   {
      return scmlt_;
   }

   public void setScmlt(float scmlt_)
   {
      this.scmlt_ = scmlt_;
   }

   public float getMiddeltrt()
   {
      return middeltrt_;
   }

   public void setMiddeltrt(float middeltrt_)
   {
      this.middeltrt_ = middeltrt_;
   }

   public float getMiddeltlt()
   {
      return middeltlt_;
   }

   public void setMiddeltlt(float middeltlt_)
   {
      this.middeltlt_ = middeltlt_;
   }

   public float getAntdeltoidrt()
   {
      return antdeltoidrt_;
   }

   public void setAntdeltoidrt(float antdeltoidrt_)
   {
      this.antdeltoidrt_ = antdeltoidrt_;
   }

   public float getAntdeltoidlt()
   {
      return antdeltoidlt_;
   }

   public void setAntdeltoidlt(float antdeltoidlt_)
   {
      this.antdeltoidlt_ = antdeltoidlt_;
   }

   public float getMserratusantrt()
   {
      return mserratusantrt_;
   }

   public void setMserratusantrt(float mserratusantrt_)
   {
      this.mserratusantrt_ = mserratusantrt_;
   }

   public float getMserratusantlt()
   {
      return mserratusantlt_;
   }

   public void setMserratusantlt(float mserratusantlt_)
   {
      this.mserratusantlt_ = mserratusantlt_;
   }

   public float getLattricepsrt()
   {
      return lattricepsrt_;
   }

   public void setLattricepsrt(float lattricepsrt_)
   {
      this.lattricepsrt_ = lattricepsrt_;
   }

   public float getLattricepslt()
   {
      return lattricepslt_;
   }

   public void setLattricepslt(float lattricepslt_)
   {
      this.lattricepslt_ = lattricepslt_;
   }

   public float getBrachiodrt()
   {
      return brachiodrt_;
   }

   public void setBrachiodrt(float brachiodrt_)
   {
      this.brachiodrt_ = brachiodrt_;
   }

   public float getBrachiodlt()
   {
      return brachiodlt_;
   }

   public void setBrachiodlt(float brachiodlt_)
   {
      this.brachiodlt_ = brachiodlt_;
   }

   public float getBicepsbrrt()
   {
      return bicepsbrrt_;
   }

   public void setBicepsbrrt(float bicepsbrrt_)
   {
      this.bicepsbrrt_ = bicepsbrrt_;
   }

   public float getBicepsbrlt()
   {
      return bicepsbrlt_;
   }

   public void setBicepsbrlt(float bicepsbrlt_)
   {
      this.bicepsbrlt_ = bicepsbrlt_;
   }

   public float getFlexcarpurt()
   {
      return flexcarpurt_;
   }

   public void setFlexcarpurt(float flexcarpurt_)
   {
      this.flexcarpurt_ = flexcarpurt_;
   }

   public float getFlexcarpult()
   {
      return flexcarpult_;
   }

   public void setFlexcarpult(float flexcarpult_)
   {
      this.flexcarpult_ = flexcarpult_;
   }

   public float getFlexcarprrt()
   {
      return flexcarprrt_;
   }

   public void setFlexcarprrt(float flexcarprrt_)
   {
      this.flexcarprrt_ = flexcarprrt_;
   }

   public float getFlexcarprlt()
   {
      return flexcarprlt_;
   }

   public void setFlexcarprlt(float flexcarprlt_)
   {
      this.flexcarprlt_ = flexcarprlt_;
   }

   public float getAbductpolrt()
   {
      return abductpolrt_;
   }

   public void setAbductpolrt(float abductpolrt_)
   {
      this.abductpolrt_ = abductpolrt_;
   }

   public float getAbductpollt()
   {
      return abductpollt_;
   }

   public void setAbductpollt(float abductpollt_)
   {
      this.abductpollt_ = abductpollt_;
   }

   public float getExtdigrt()
   {
      return extdigrt_;
   }

   public void setExtdigrt(float extdigrt_)
   {
      this.extdigrt_ = extdigrt_;
   }

   public float getExtdiglt()
   {
      return extdiglt_;
   }

   public void setExtdiglt(float extdiglt_)
   {
      this.extdiglt_ = extdiglt_;
   }

   public float getPectmajorrt()
   {
      return pectmajorrt_;
   }

   public void setPectmajorrt(float pectmajorrt_)
   {
      this.pectmajorrt_ = pectmajorrt_;
   }

   public float getPectmajorlt()
   {
      return pectmajorlt_;
   }

   public void setPectmajorlt(float pectmajorlt_)
   {
      this.pectmajorlt_ = pectmajorlt_;
   }

   public float getRectabdomuprt()
   {
      return rectabdomuprt_;
   }

   public void setRectabdomuprt(float rectabdomuprt_)
   {
      this.rectabdomuprt_ = rectabdomuprt_;
   }

   public float getRectabdomuplt()
   {
      return rectabdomuplt_;
   }

   public void setRectabdomuplt(float rectabdomuplt_)
   {
      this.rectabdomuplt_ = rectabdomuplt_;
   }

   public float getRectabdomlort()
   {
      return rectabdomlort_;
   }

   public void setRectabdomlort(float rectabdomlort_)
   {
      this.rectabdomlort_ = rectabdomlort_;
   }

   public float getRectabdomlolt()
   {
      return rectabdomlolt_;
   }

   public void setRectabdomlolt(float rectabdomlolt_)
   {
      this.rectabdomlolt_ = rectabdomlolt_;
   }

   public float getExtobliquert()
   {
      return extobliquert_;
   }

   public void setExtobliquert(float extobliquert_)
   {
      this.extobliquert_ = extobliquert_;
   }

   public float getExtobliquelt()
   {
      return extobliquelt_;
   }

   public void setExtobliquelt(float extobliquelt_)
   {
      this.extobliquelt_ = extobliquelt_;
   }

   public float getIntobliquert()
   {
      return intobliquert_;
   }

   public void setIntobliquert(float intobliquert_)
   {
      this.intobliquert_ = intobliquert_;
   }

   public float getIntobliquelt()
   {
      return intobliquelt_;
   }

   public void setIntobliquelt(float intobliquelt_)
   {
      this.intobliquelt_ = intobliquelt_;
   }

   public float getAdductorsrt()
   {
      return adductorsrt_;
   }

   public void setAdductorsrt(float adductorsrt_)
   {
      this.adductorsrt_ = adductorsrt_;
   }

   public float getAdductorslt()
   {
      return adductorslt_;
   }

   public void setAdductorslt(float adductorslt_)
   {
      this.adductorslt_ = adductorslt_;
   }

   public float getSoleusrt()
   {
      return soleusrt_;
   }

   public void setSoleusrt(float soleusrt_)
   {
      this.soleusrt_ = soleusrt_;
   }

   public float getSoleuslt()
   {
      return soleuslt_;
   }

   public void setSoleuslt(float soleuslt_)
   {
      this.soleuslt_ = soleuslt_;
   }

   public float getTibantrt()
   {
      return tibantrt_;
   }

   public void setTibantrt(float tibantrt_)
   {
      this.tibantrt_ = tibantrt_;
   }

   public float getTibantlt()
   {
      return tibantlt_;
   }

   public void setTibantlt(float tibantlt_)
   {
      this.tibantlt_ = tibantlt_;
   }

   public float getPeroneusrt()
   {
      return peroneusrt_;
   }

   public void setPeroneusrt(float peroneusrt_)
   {
      this.peroneusrt_ = peroneusrt_;
   }

   public float getPeroneuslt()
   {
      return peroneuslt_;
   }

   public void setPeroneuslt(float peroneuslt_)
   {
      this.peroneuslt_ = peroneuslt_;
   }

   public float getMedgastrort()
   {
      return medgastrort_;
   }

   public void setMedgastrort(float medgastrort_)
   {
      this.medgastrort_ = medgastrort_;
   }

   public float getMedgastrolt()
   {
      return medgastrolt_;
   }

   public void setMedgastrolt(float medgastrolt_)
   {
      this.medgastrolt_ = medgastrolt_;
   }

   public float getLatgastrort()
   {
      return latgastrort_;
   }

   public void setLatgastrort(float latgastrort_)
   {
      this.latgastrort_ = latgastrort_;
   }

   public float getLatgastrolt()
   {
      return latgastrolt_;
   }

   public void setLatgastrolt(float latgastrolt_)
   {
      this.latgastrolt_ = latgastrolt_;
   }

   public float getBicepsfemrt()
   {
      return bicepsfemrt_;
   }

   public void setBicepsfemrt(float bicepsfemrt_)
   {
      this.bicepsfemrt_ = bicepsfemrt_;
   }

   public float getBicepsfemlt()
   {
      return bicepsfemlt_;
   }

   public void setBicepsfemlt(float bicepsfemlt_)
   {
      this.bicepsfemlt_ = bicepsfemlt_;
   }

   public float getSemitendrt()
   {
      return semitendrt_;
   }

   public void setSemitendrt(float semitendrt_)
   {
      this.semitendrt_ = semitendrt_;
   }

   public float getSemitendlt()
   {
      return semitendlt_;
   }

   public void setSemitendlt(float semitendlt_)
   {
      this.semitendlt_ = semitendlt_;
   }

   public float getVlort()
   {
      return vlort_;
   }

   public void setVlort(float vlort_)
   {
      this.vlort_ = vlort_;
   }

   public float getVlolt()
   {
      return vlolt_;
   }

   public void setVlolt(float vlolt_)
   {
      this.vlolt_ = vlolt_;
   }

   public float getVmort()
   {
      return vmort_;
   }

   public void setVmort(float vmort_)
   {
      this.vmort_ = vmort_;
   }

   public float getVmolt()
   {
      return vmolt_;
   }

   public void setVmolt(float vmolt_)
   {
      this.vmolt_ = vmolt_;
   }

   public float getRectusfemrt()
   {
      return rectusfemrt_;
   }

   public void setRectusfemrt(float rectusfemrt_)
   {
      this.rectusfemrt_ = rectusfemrt_;
   }

   public float getRectusfemlt()
   {
      return rectusfemlt_;
   }

   public void setRectusfemlt(float rectusfemlt_)
   {
      this.rectusfemlt_ = rectusfemlt_;
   }

   public float getPelvicfloorrt()
   {
      return pelvicfloorrt_;
   }

   public void setPelvicfloorrt(float pelvicfloorrt_)
   {
      this.pelvicfloorrt_ = pelvicfloorrt_;
   }

   public float getPelvicfloorlt()
   {
      return pelvicfloorlt_;
   }

   public void setPelvicfloorlt(float pelvicfloorlt_)
   {
      this.pelvicfloorlt_ = pelvicfloorlt_;
   }

   public float getUppertraprt()
   {
      return uppertraprt_;
   }

   public void setUppertraprt(float uppertraprt_)
   {
      this.uppertraprt_ = uppertraprt_;
   }

   public float getUppertraplt()
   {
      return uppertraplt_;
   }

   public void setUppertraplt(float uppertraplt_)
   {
      this.uppertraplt_ = uppertraplt_;
   }

   public float getMiddletraprt()
   {
      return middletraprt_;
   }

   public void setMiddletraprt(float middletraprt_)
   {
      this.middletraprt_ = middletraprt_;
   }

   public float getMiddletraplt()
   {
      return middletraplt_;
   }

   public void setMiddletraplt(float middletraplt_)
   {
      this.middletraplt_ = middletraplt_;
   }

   public float getLowertraprt()
   {
      return lowertraprt_;
   }

   public void setLowertraprt(float lowertraprt_)
   {
      this.lowertraprt_ = lowertraprt_;
   }

   public float getLowertraplt()
   {
      return lowertraplt_;
   }

   public void setLowertraplt(float lowertraplt_)
   {
      this.lowertraplt_ = lowertraplt_;
   }

   public float getThoracicrt()
   {
      return thoracicrt_;
   }

   public void setThoracicrt(float thoracicrt_)
   {
      this.thoracicrt_ = thoracicrt_;
   }

   public float getThoraciclt()
   {
      return thoraciclt_;
   }

   public void setThoraciclt(float thoraciclt_)
   {
      this.thoraciclt_ = thoraciclt_;
   }

   public float getMultifidiirt()
   {
      return multifidiirt_;
   }

   public void setMultifidiirt(float multifidiirt_)
   {
      this.multifidiirt_ = multifidiirt_;
   }

   public float getMultifidiilt()
   {
      return multifidiilt_;
   }

   public void setMultifidiilt(float multifidiilt_)
   {
      this.multifidiilt_ = multifidiilt_;
   }

   public float getGlutmaxrt()
   {
      return glutmaxrt_;
   }

   public void setGlutmaxrt(float glutmaxrt_)
   {
      this.glutmaxrt_ = glutmaxrt_;
   }

   public float getGlutmaxlt()
   {
      return glutmaxlt_;
   }

   public void setGlutmaxlt(float glutmaxlt_)
   {
      this.glutmaxlt_ = glutmaxlt_;
   }

   public float getGlutmedrt()
   {
      return glutmedrt_;
   }

   public void setGlutmedrt(float glutmedrt_)
   {
      this.glutmedrt_ = glutmedrt_;
   }

   public float getGlutmedlt()
   {
      return glutmedlt_;
   }

   public void setGlutmedlt(float glutmedlt_)
   {
      this.glutmedlt_ = glutmedlt_;
   }

   public float getLatdorsirt()
   {
      return latdorsirt_;
   }

   public void setLatdorsirt(float latdorsirt_)
   {
      this.latdorsirt_ = latdorsirt_;
   }

   public float getLatdorsilt()
   {
      return latdorsilt_;
   }

   public void setLatdorsilt(float latdorsilt_)
   {
      this.latdorsilt_ = latdorsilt_;
   }

   public float getInfraspinrt()
   {
      return infraspinrt_;
   }

   public void setInfraspinrt(float infraspinrt_)
   {
      this.infraspinrt_ = infraspinrt_;
   }

   public float getInfraspinlt()
   {
      return infraspinlt_;
   }

   public void setInfraspinlt(float infraspinlt_)
   {
      this.infraspinlt_ = infraspinlt_;
   }

   public float getCervicalpsrt()
   {
      return cervicalpsrt_;
   }

   public void setCervicalpsrt(float cervicalpsrt_)
   {
      this.cervicalpsrt_ = cervicalpsrt_;
   }

   public float getCervicalpslt()
   {
      return cervicalpslt_;
   }

   public void setCervicalpslt(float cervicalpslt_)
   {
      this.cervicalpslt_ = cervicalpslt_;
   }


}