/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package exoskeleton_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the Exoskeleton Metabolic Estimation Interface
This message acts as a go-between between Java and Python.
<p>Source (exoskeleton_msgs/MetabolicMessage):
<pre>{@code
#This message is part of the Exoskeleton Metabolic Estimation Interface
#This message acts as a go-between between Java and Python.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Current metabolic rate plus the change from the previous metabolic rate
float64 metabolic_rate
float64 delta_metabolic_rate}</pre>
*/
public class MetabolicMessage implements ROS2Message<MetabolicMessage>
{
   public static final java.lang.String name = "exoskeleton_msgs::msg::dds_::MetabolicMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Current metabolic rate plus the change from the previous metabolic rate
   */
   private double metabolic_rate_;
   private double delta_metabolic_rate_;

   public MetabolicMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // metabolic_rate_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // delta_metabolic_rate_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeDouble(metabolic_rate_);
      buffer.writeDouble(delta_metabolic_rate_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      metabolic_rate_ = buffer.readDouble();
      delta_metabolic_rate_ = buffer.readDouble();

   }

   @Override
   public void set(MetabolicMessage from)
   {
      sequence_id_ = from.sequence_id_;
      metabolic_rate_ = from.metabolic_rate_;
      delta_metabolic_rate_ = from.delta_metabolic_rate_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public double getMetabolicRate()
   {
      return metabolic_rate_;
   }

   public void setMetabolicRate(double metabolic_rate_)
   {
      this.metabolic_rate_ = metabolic_rate_;
   }

   public double getDeltaMetabolicRate()
   {
      return delta_metabolic_rate_;
   }

   public void setDeltaMetabolicRate(double delta_metabolic_rate_)
   {
      this.delta_metabolic_rate_ = delta_metabolic_rate_;
   }


}