/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package exoskeleton_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the Tufftread to Eva Exoskeleton Interface
This message acts as a go-between between the Tufftread treadmill controller and Eva
<p>Source (exoskeleton_msgs/TreadmillMessage):
<pre>{@code
#This message is part of the Tufftread to Eva Exoskeleton Interface
#This message acts as a go-between between the Tufftread treadmill controller and Eva

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte START_BELT_TIMEOUT_ENABLED = 0
byte START_BELT_TIMEOUT_DISABLED = 1
byte STOP_BELT = 2
byte SET_SPEED = 3
byte SET_ELEVATION = 4
byte AUTO_STOP = 5
byte AUTO_MINIMUM = 6
byte ACK_FLAG_TOGGLE = 7
byte BELT_STATUS = 8
byte GET_CURRENT_SPEED = 9
byte GET_CURRENT_ELEVATION = 10
byte GET_COMMANDED_SPEED = 11
byte GET_COMMANDED_ELEVATION = 12

# bool to dictate activation of communication between the treadmill and the computer. If true, activate and if false, deactivate
bool activate

# byte to decide current action based on the previously defined byte values
byte action 

# This is the data being sent to and from the treadmill. Speed is in MPH and incline is in percent incline
float64 speed
float64 incline

}</pre>
*/
public class TreadmillMessage implements ROS2Message<TreadmillMessage>
{
   public static final java.lang.String name = "exoskeleton_msgs::msg::dds_::TreadmillMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   public static final byte START_BELT_TIMEOUT_ENABLED = 0;
   public static final byte START_BELT_TIMEOUT_DISABLED = 1;
   public static final byte STOP_BELT = 2;
   public static final byte SET_SPEED = 3;
   public static final byte SET_ELEVATION = 4;
   public static final byte AUTO_STOP = 5;
   public static final byte AUTO_MINIMUM = 6;
   public static final byte ACK_FLAG_TOGGLE = 7;
   public static final byte BELT_STATUS = 8;
   public static final byte GET_CURRENT_SPEED = 9;
   public static final byte GET_CURRENT_ELEVATION = 10;
   public static final byte GET_COMMANDED_SPEED = 11;
   public static final byte GET_COMMANDED_ELEVATION = 12;
   /**
      bool to dictate activation of communication between the treadmill and the computer. If true, activate and if false, deactivate
   */
   private boolean activate_;
   /**
      byte to decide current action based on the previously defined byte values
   */
   private byte action_;
   /**
      This is the data being sent to and from the treadmill. Speed is in MPH and incline is in percent incline
   */
   private double speed_;
   private double incline_;

   public TreadmillMessage()
   {
      activate_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // activate_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // action_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // speed_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // incline_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(activate_);
      buffer.writeByte(action_);
      buffer.writeDouble(speed_);
      buffer.writeDouble(incline_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      activate_ = buffer.readBoolean();
      action_ = buffer.readByte();
      speed_ = buffer.readDouble();
      incline_ = buffer.readDouble();

   }

   @Override
   public void set(TreadmillMessage from)
   {
      sequence_id_ = from.sequence_id_;
      activate_ = from.activate_;
      action_ = from.action_;
      speed_ = from.speed_;
      incline_ = from.incline_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getActivate()
   {
      return activate_;
   }

   public void setActivate(boolean activate_)
   {
      this.activate_ = activate_;
   }

   public byte getAction()
   {
      return action_;
   }

   public void setAction(byte action_)
   {
      this.action_ = action_;
   }

   public double getSpeed()
   {
      return speed_;
   }

   public void setSpeed(double speed_)
   {
      this.speed_ = speed_;
   }

   public double getIncline()
   {
      return incline_;
   }

   public void setIncline(double incline_)
   {
      this.incline_ = incline_;
   }


}